### PR TITLE
development/jupyter-nbclassic: Update for 0.5.3

### PR DESCRIPTION
**Pull request by isaackwy**

### CODE REVIEW

**Comment by aclemons** [comment]
sbopkglint complains about broken symlink here for me. Does this happen for you?

**Comment by isaackwy** [comment]
I don't have this issue.

I am using sbo-maintainer-tools 0.6.2.
This was my output from sbopkglint:
```
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /tmp/jupyter-nbclassic-0.5.3-x86_64-1_SBo.tgz to /tmp/sbopkglint.DO5vm2 ...OK
Running pre-doinst test...OK
Installing /tmp/jupyter-nbclassic-0.5.3-x86_64-1_SBo.tgz to /tmp/sbopkglint.DO5vm2 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...usr/share/applications/jupyter-nbclassic.desktop: hint: value "Development;Education;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== jupyter-nbclassic-0.5.3-x86_64-1_SBo.tgz: All tests passed
```

**Comment by aclemons** [comment]
Sorry, of course. We had this discussion before. I need to install all dependencies when validating the package with `sbopkglint`.

**Comment by aclemons** [comment]
LGTM - staged to my branch

**Pull request closed without merging**
