### PR TITLE
Update sunvox to v2.1.1c

### PR DESCRIPTION
**Pull request by jbarrett**
Thanks!

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build audio/sunvox

**Comment by willysr** [comment]
@sbo-bot: build audio/sunvox

**Comment by willysr** [comment]
@sbo-bot: build audio/sunvox

**Comment by jbarrett** [comment]
`/usr/doc/sunvox-2.1.1c` is a symlink to `/usr/share/sunvox/docs/` - this approach isn't without precedent, e.g. elvis.

Let me know if you need a change here.

Also wondering if the test should follow symlinks?

Thanks!

**Comment by willysr** [comment]
@jbarrett  probably better to move them into /usr/doc/PRGNAM-VERSION

**Comment by willysr** [comment]
@sbo-bot: build audio/sunvox

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
