### PR TITLE
python/python3-cairocffi: updated for version 1.7.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
@sbo-bot: build python/python3-cairocffi

**Comment by willysr** [comment]
@sbo-bot: build desktop/qtile

**Comment by willysr** [comment]
@sbo-bot: build graphics/CairoSVG

**Comment by willysr** [comment]
@sbo-bot: build system/image-analyzer

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
