### PR TITLE
development/global: Updated for version 6.6.13

### PR DESCRIPTION
**Pull request by ardrabczyk**
Signed-off-by: Arkadiusz Drabczyk <arkadiusz@drabczyk.org>

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/global

**Comment by ardrabczyk** [comment]
hmm, I ran sbolint before opening a PR, I'll look into sbopkglint report

**Comment by willysr** [comment]
merged

**Comment by ardrabczyk** [comment]
@willysr you said _merged_ but it isn't merged yet?

**Comment by willysr** [comment]
https://git.slackbuilds.org/slackbuilds/commit/?id=570549269

**Comment by ardrabczyk** [comment]
ok, I see, thx. How often are you synchronizing this GH repository?

**Comment by willysr** [comment]
every public update, which is normally at weekend

**Comment by ardrabczyk** [comment]
I see that you've already fixed 10-docs issues on your branch, I've also fixed 60-usr_info here and will push it here next week when this PR is merged into master.

**Comment by willysr** [comment]
you can push it here, i will merge it again no problem

**Comment by ardrabczyk** [comment]
thx, pushed

**Comment by willysr** [comment]
Pushed as https://git.slackbuilds.org/slackbuilds/commit/?id=643b8e8be

**Pull request closed without merging**
