### PR TITLE
development/sonarqube: Updated for version 10.3.0.82913.

### PR DESCRIPTION
**Pull request by gperon**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/sonarqube

**Comment by willysr** [comment]
@gperon can you check this submission?

**Comment by gperon** [comment]
ciao @willysr,  I fixed the submission thanks

**Comment by willysr** [comment]
@gperon i would suggest to write detailed README in another file, eg. README.SBo
README is just to display what the package is in the website

**Comment by gperon** [comment]
added README.SBo

**Comment by willysr** [comment]
@sbo-bot: build development/sonarqube

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
