### PR TITLE
python/python3-virtualenv: Version bump to 20.26.4

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-virtualenv

**Comment by bassmadrigal** [comment]
@sbo-bot: build development/pre-commit

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pylint-venv

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-tox

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
