### PR TITLE
academic/root: Updated for version 6.32.04 (+fix 32 bit)

### PR DESCRIPTION
**Pull request by arabusov**
Added a patch from the 6.34 fixes branch to fix the issue [#15738](https://github.com/root-project/root/issues/15738). It shall be removed later when we switch to the 6.34 branch.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build academic/root

**Comment by willysr** [comment]
@sbo-bot: build academic/root

**Comment by arabusov** [comment]
It seems the doinst script should be removed.

**Comment by willysr** [comment]
can you push it on your branch?

**Comment by willysr** [comment]
@sbo-bot: build academic/root

**Comment by willysr** [comment]
@arabusov it seems you didn't delete them from SlackBuild itself

**Comment by arabusov** [comment]
@willysr true, I fixed it now

**Comment by willysr** [comment]
@sbo-bot: build academic/root

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
