### PR TITLE
Picard

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
This is really affecting my program's functionality..
As I said Jermey already let me maintain his builds, he doesn't use Slackware anymore
Also dependencies provided in python3 so nothing would go wrong;
Please merge.

Regards, Pouria

### CODE REVIEW

**Comment by willysr** [comment]
i haven't seen any other scripts that depends on that 2 new scripts

**Comment by RSKYS** [comment]
Picard requires these
And it's not just going to build on python2 anymore
Trust me, I patched python files with .diff to get it build with python2, it just didn't give a damn
If I could anything to not add new dependencies, I wouldn't hesitate
And I have these files for some few weeks now ready for submit..

**Comment by RSKYS** [comment]
> i haven't seen any other scripts that depends on that 2 new scripts

My other option was to add python3 install at fasteners and monotonic themselves,
Well, didn't turn out good last time.

**Comment by RSKYS** [comment]
I respect any decision you make about dependencies.

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
@RSKYS It seems you haven't talked to Jeremy about taking over Picard?

**Comment by rworkman** [comment]
> As I said Jermey already let me maintain his builds, he doesn't use Slackware anymore

The above statement is a really good way to find yourself ignored by us permanently - it is completely unacceptable to lie to us.
https://lists.slackbuilds.org/pipermail/slackbuilds-users/2022-February/026287.html

**Pull request closed without merging**
