### PR TITLE
development/rustup: Updated for version 1.27.1.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by willysr** [comment]
@aclemons is this working well with new rust16 ?

**Comment by aclemons** [comment]
> @aclemons is this working well with new rust16 ?

Yes, I tested it on my machine locally, but I will check it again here too.

**Comment by aclemons** [comment]
@sbo-bot: build development/rustup

**Comment by aclemons** [comment]
@sbo-bot: build system/system76-power

**Comment by willysr** [comment]
looks good @aclemons

**Comment by willysr** [comment]
@aclemons does this depends on new rust? or can it work with current rust16 we have in our repo now?
i think @pghvlaans want to wait until the last 2 scripts works with new rust

**Comment by aclemons** [comment]
Yes, it works with the existing version. When I first opened the PR, I had tested it with rust16 on master. I pushed the new rust16 to this branch temporarily to confirm it was still fine (but Gene had also already tested it with that version too).

**Comment by willysr** [comment]
ok

**Pull request merged**
