### PR TITLE
python/python3-formencode: updated for version 2.1.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-formencode

**Comment by Ythogtha** [comment]
That's because the docs are nit generated, they require Sphinx, but it's optional.
So the Slackbuild does not fail, but there are empty directories.
I'll push an update later to check and remove those empty dirs, when doc is not generated.

**Comment by Ythogtha** [comment]
Ok, updated, you can re-check it !

**Comment by willysr** [comment]
@sbo-bot: build python/python3-formencode

**Comment by willysr** [comment]
@Ythogtha this PR also change games/warzone2100, can you fix that?

**Comment by Ythogtha** [comment]
> @Ythogtha this PR also change games/warzone2100, can you fix that?

@willysr , sorry, looks like I made a gitstake...
Fixed !

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
