### PR TITLE
games/Mindustry: updated for version 146

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
sbo-bot: build games/Mindustry

**Comment by aclemons** [comment]
@sbo-bot: build games/Mindustry

**Comment by aclemons** [comment]
@Ythogtha This failed to build on 32bit. Should it still work there?

Snip of the log:
```
Mindustry-145.1/tools/src/mindustry/tools/ScriptMainGenerator.java
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
No Android SDK found. Skipping Android module.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Mindustry-145.1'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find packer-b718875065.jar (com.github.Anuken.Arc:packer:b718875065).
     Searched in the following locations:
         https://jitpack.io/com/github/Anuken/Arc/packer/b718875065/packer-b718875065.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```

**Comment by Ythogtha** [comment]
For now, here I am : there is a 32bit windows build, so it should be possible for it to build on 32bits.
Despite what sbopkglint suggest, this can't be noarch, because while being a jar, it ships some libs.so, like SDL2, inside the final jar.
The 32bits build fails while trying to link to a libarc.so, which seems to be internal to Mindustry. The 64 builds ships a libarc64.so ans even dlls.
The binary builds are not available for linux32.

And finally I'm not familiar wirh gradle, which looks like a black box of dark java magic.
I don't dabble with these obscure and dangerous powers...

I've tried with zulu-openjdk17 and Open JDK17, it's the exact same result.

I may try a few things, but I guess I'll end up flagging it UNSUPPORTED for 32bits...

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 games/Mindustry

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
