### PR TITLE
network/rspamd: Updated for version 2.7

### PR DESCRIPTION
**Pull request by earies**

### CODE REVIEW

**Comment by willysr** [comment]
please rebase against latest master changes affecting rspamd

**Comment by earies** [comment]
@willysr I'm not sure where you are seeing any conflicts here as this is already rebased against master.  I've only just included another edit that was missed previously

**Comment by willysr** [comment]
git am -s 893.patch 
Applying: network/rspamd: Updated for version 2.7
error: patch failed: network/rspamd/rspamd.SlackBuild:25
error: network/rspamd/rspamd.SlackBuild: patch does not apply
error: patch failed: network/rspamd/rspamd.info:1
error: network/rspamd/rspamd.info: patch does not apply
Patch failed at 0001 network/rspamd: Updated for version 2.7
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

**Comment by willysr** [comment]
in master it has been updated to 2.7

**Comment by earies** [comment]
I'm not sure which master you are referring to here but definitely not this repo

https://github.com/SlackBuildsOrg/slackbuilds/blob/master/network/rspamd/rspamd.info

As is still on 2.6

**Comment by willysr** [comment]
ohh i think i haven't pushed it to github. 
main repo is here: https://git.slackbuilds.org/slackbuilds/
Github/GitLab is just a mirror

**Comment by willysr** [comment]
i have just pushed it

**Comment by willysr** [comment]
oh wait, it's in my branch, not in master

**Pull request closed without merging**
