### PR TITLE
games/warzone2100: updated for version 4.3.3

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
```
# buildpkg x86_64 games/warzone2100
Fetching origin
HEAD is now at d43b26723b libraries/physfs: Fix github tarball handling.
sbolint: warzone2100 checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 12:47:09 GMT 2023
revision: d43b26723bfafb414978310f7e6f934418afa705
title:    libraries/physfs: Fix github tarball handling.

================================================================================
games/warzone2100                                                       12:47:57
================================================================================

Calculating dependencies ...
Dependency tree:
games/warzone2100 (update for version 4.3.3)
  libraries/physfs (updated)

Building games/warzone2100 (update for version 4.3.3) ----------------- 12:47:57
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
physfs-3.2.0-x86_64-1_SBo: library to provide abstract access to various archives ....................................................................................................................................................................................... [ 410K]
Running warzone2100.SlackBuild ...                                  ETA 12:54:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./warzone2100.SlackBuild
Build time 407 sec, peak load 15.80, peak memory 5459M, peak tmp 1891M
Built ok:  warzone2100-4.3.3-x86_64-1_SBo.txz                           12:55:00
Testing package warzone2100-4.3.3-x86_64-1_SBo.txz ... done.
Test installing warzone2100-4.3.3-x86_64-1_SBo.txz ...
warzone2100-4.3.3-x86_64-1_SBo: a real-time 3D strategy game ............................................................................................................................................................................................................ [ 464M]
Unmounting chroot ... done.
Backed up: warzone2100-4.3.2-x86_64-1_SBo.txz
:-) games/warzone2100 Updated for version 4.3.3 (-:

================================================================================
SUMMARY                                                                 12:55:35
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_12:47:57.log
Runtime:     0h 7m 39s
Updated:     1
  games/warzone2100/warzone2100-4.3.3-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/x86_64/games/warzone2100/warzone2100-4.3.3-x86_64-1_SBo.txz to /tmp/sbopkglint.SnciqG ...OK
Running test: 05-basic-sanity...
--- missing required directory: usr/doc/warzone2100-4.3.3
--- forbidden directory exists: usr/share/doc
--- missing required file: usr/doc/warzone2100-4.3.3/warzone2100.SlackBuild
FAILED
Running test: 10-docs...find: ‘usr/doc’: No such file or directory
OK
Running test: 15-noarch...OK
Running test: 20-arch...--- ELF object(s) not stripped:

-rwxr-xr-x 1 root root 208856648 Jan  3 12:53 usr/games/warzone2100
FAILED
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! warzone2100-4.3.3-x86_64-1_SBo.txz: 4 failures
```

**Comment by aclemons** [comment]
@Ythogtha can you check that doc dir please?

**Comment by Ythogtha** [comment]
PR updated, docs are now in /usr/doc/warzone2100-4.3.3/

**Comment by aclemons** [comment]
LGTM - staged to my branch. I'm assuming the ELF objects were not stripped on purpose.

```
# buildpkg i586 games/warzone2100
sbolint: warzone2100 checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 21:56:29 GMT 2023
revision: 60ed8c01a716f601364881b61116ee16b5a5ebcd
title:    games/warzone2100: Updated for version 4.3.3.

================================================================================
games/warzone2100                                                       21:56:42
================================================================================

Calculating dependencies ...
Dependency tree:
games/warzone2100 (update for version 4.3.3)
  libraries/physfs (updated)

Building games/warzone2100 (update for version 4.3.3) ----------------- 21:56:42
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
physfs-3.2.0-i586-1_SBo: library to provide abstract access to various archives ......................................................................................................................................................................................... [ 420K]
Running warzone2100.SlackBuild ...                                  ETA 22:03:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./warzone2100.SlackBuild
Build time 575 sec, peak load 61.67, peak memory 3634M, peak tmp 1644M
Built ok:  warzone2100-4.3.3-i586-1_SBo.txz                             22:06:41
Testing package warzone2100-4.3.3-i586-1_SBo.txz ... done.
Test installing warzone2100-4.3.3-i586-1_SBo.txz ...
warzone2100-4.3.3-i586-1_SBo: a real-time 3D strategy game .............................................................................................................................................................................................................. [ 452M]
Unmounting chroot ... done.
Backed up: warzone2100-4.3.2-i586-1_SBo.txz
:-) games/warzone2100 Updated for version 4.3.3 (-:

================================================================================
SUMMARY                                                                 22:07:21
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_21:56:41.log
Runtime:     0h 10m 40s
Updated:     1
  games/warzone2100/warzone2100-4.3.3-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/i586/games/warzone2100/warzone2100-4.3.3-i586-1_SBo.txz to /tmp/sbopkglint.LZDReX ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...
--- ELF object(s) not stripped:
-rwxr-xr-x 1 root root 196402824 Jan  3 22:04 usr/games/warzone2100
FAILED
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! warzone2100-4.3.3-i586-1_SBo.txz: 1 failures
```

**Pull request closed without merging**
