### PR TITLE
academic/fastqc: Updated to version 0.12.1

### PR DESCRIPTION
**Pull request by brobr**

### CODE REVIEW

**Comment by aclemons** [comment]
This built, but the package seems broken?:

```
# sbopkglint /var/lib/slackrepo/SBo/packages/15.0/x86_64/academic/fastqc/fastqc-0.11.9-noarch-6_SBo.txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/slackrepo/SBo/packages/15.0/x86_64/academic/fastqc/fastqc-0.11.9-noarch-6_SBo.txz to /tmp/sbopkglint.tAvp7O ...OK
Running pre-doinst test...OK
Installing /var/lib/slackrepo/SBo/packages/15.0/x86_64/academic/fastqc/fastqc-0.11.9-noarch-6_SBo.txz to /tmp/sbopkglint.tAvp7O ...OK
Running test: 05-basic-sanity...
--- package root dir contains non-directory: Help
--- package contains broken relative symlinks:
lrwxrwxrwx 1 root root 28 Apr 14 13:51 ./Help -> ../../share/java/fastqc/Help
___ note: package contains empty dirs, are these necessary?
ls: cannot access './usr/share/java/fastqc/Help/1': No such file or directory
ls: cannot access 'Introduction/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/1': No such file or directory
ls: cannot access 'Introduction/.svn/tmp/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/2': No such file or directory
ls: cannot access 'Basic': No such file or directory
ls: cannot access 'Operations/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/2': No such file or directory
ls: cannot access 'Basic': No such file or directory
ls: cannot access 'Operations/.svn/tmp/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/3': No such file or directory
ls: cannot access 'Analysis': No such file or directory
ls: cannot access 'Modules/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/3': No such file or directory
ls: cannot access 'Analysis': No such file or directory
ls: cannot access 'Modules/.svn/tmp/props': No such file or directory
FAILED
Running test: 10-docs...
___ note: install instructions found, is this relevant for binary package users?: usr/doc/fastqc-0.11.9/INSTALL.txt
OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! fastqc-0.11.9-noarch-6_SBo.txz: 2 failures
```

**Comment by brobr** [comment]
Hi Andrew,

Thanks for testing, but something seems wrong; the version that should
be built is 0.12.1...? It works at my end (with Java(TM) SE Runtime
Environment 18.9 (build 11.0.17+10-LTS-269))

># sbopkglint
>/var/lib/slackrepo/SBo/packages/15.0/x86_64/academic/fastqc/fastqc-0.11.9-noarch-6_SBo.txz

**Comment by aclemons** [comment]
Yes, sorry. I had two docker container running - i586 and x86_64. I built it first on i586 and then mistakenly sent you the output from sbopkglint on the old version in x86_64.

Here is the output for the new package:

```
# sbopkglint /var/lib/slackrepo/SBo/packages/15.0/i586/academic/fastqc/fastqc-0.12.1-noarch-1_SBo.txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/slackrepo/SBo/packages/15.0/i586/academic/fastqc/fastqc-0.12.1-noarch-1_SBo.txz to /tmp/sbopkglint.XgrKvZ ...OK
Running pre-doinst test...OK
Installing /var/lib/slackrepo/SBo/packages/15.0/i586/academic/fastqc/fastqc-0.12.1-noarch-1_SBo.txz to /tmp/sbopkglint.XgrKvZ ...OK
Running test: 05-basic-sanity...
--- package root dir contains non-directory: Help
--- package contains broken relative symlinks:
lrwxrwxrwx 1 root root 28 Apr 14 14:14 ./Help -> ../../share/java/fastqc/Help
___ note: package contains empty dirs, are these necessary?
ls: cannot access './usr/share/java/fastqc/Help/1': No such file or directory
ls: cannot access 'Introduction/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/1': No such file or directory
ls: cannot access 'Introduction/.svn/tmp/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/2': No such file or directory
ls: cannot access 'Basic': No such file or directory
ls: cannot access 'Operations/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/2': No such file or directory
ls: cannot access 'Basic': No such file or directory
ls: cannot access 'Operations/.svn/tmp/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/3': No such file or directory
ls: cannot access 'Analysis': No such file or directory
ls: cannot access 'Modules/.svn/props': No such file or directory
ls: cannot access './usr/share/java/fastqc/Help/3': No such file or directory
ls: cannot access 'Analysis': No such file or directory
ls: cannot access 'Modules/.svn/tmp/props': No such file or directory
FAILED
Running test: 10-docs...
___ note: install instructions found, is this relevant for binary package users?: usr/doc/fastqc-0.12.1/INSTALL.txt
OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! fastqc-0.12.1-noarch-1_SBo.txz: 2 failures
```

But given my previous output, it seems the old package had the same issue.

**Comment by aclemons** [comment]
Maybe you can check on that for your next update. I'll approve this one - seems to just be docs broken.

**Pull request closed without merging**
