### PR TITLE
User/ar tourter/libspatialite

### PR DESCRIPTION
**Pull request by ArTourter**
includes new librttopo package. I will also submit it via the form but since it is a new dependency for libspatialite, I am adding it to this PR

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build gis/libspatialite

**Comment by willysr** [comment]
@sbo-bot: build gis/libspatialite

**Comment by willysr** [comment]
@sbo-bot: build gis/librttopo

**Comment by willysr** [comment]
@ArTourter i think the DOWNLOAD url is not reachable via wget

**Comment by aclemons** [comment]
I fixed it in #3963 - you get two different tarballs depending on whether you use something that respects the content disposition header or not. I don't think this is a correct incantation of the URL for gitea links like there is for github to make them always be the same, so I updated the script to handle either.

**Comment by aclemons** [comment]
> > @ArTourter i think the DOWNLOAD url is not reachable via wget
> 
> weird! I have no problem from here:

If you download with your browser, you will get a file named: librttopo-librttopo-1.1.0.tar.gz

**Comment by aclemons** [comment]
@sbo-bot: build gis/libspatialite

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
staged to `github` branch

**Pull request closed without merging**
