### PR TITLE
Nix v2.4 + Tauon

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
I'll explain everything later.
I'm still testing everything; gonna be huge amount of changes..
This update was ABSOLUTE PAIN, they didn't really gave me lot of options.

### CODE REVIEW

**Comment by RSKYS** [comment]
Before other commits, I need to know status of following builds:
development/mrustc
office/lowdown
I made HUGE modify to mrustrc to get it work, also lowdown has little bit messes.
They seem left unmaintained, can I take them over?
You can see changes I had no choice to do [here.](https://github.com/RSKYS/SBo-git/pull/23/files)

Regards,
Pouria.

**Comment by RSKYS** [comment]
Before other commits, I need to know status of following builds:
development/mrustc
office/lowdown
I made HUGE modify to mrustc to get it work, also lowdown has little bit messes.
They seem left unmaintained, can I take them over? if not, I really need to modify them, so I don't know what otherwise.
You can see changes need to get done earlier a bit [here.](https://github.com/RSKYS/SBo-git/pull/23/files)

Regards,
Pouria.

**Comment by willysr** [comment]
mrustc is still actively maintained by Andrew, which is also SBo admin
lowdown is not actively maintained by the original maintainer i guess, based on git history

**Comment by RSKYS** [comment]
Oh then I need to offer some changes to Andrew;
I don't know, maybe seperating build is better solution.

**Comment by RSKYS** [comment]
It seems I don't need whole rust lib, as it really doesn't dependency resolve nix after all thiis;
I only need to seperate mdbook for it
Let's see

**Comment by RSKYS** [comment]
Phew,
okay I didn't really had to take that over anyway.
But if I don't apply my fix for office/lowdown, I cannot get nix to build;
I'll open request if I don't hit any issue this time.

Regards, Pouria.

**Comment by RSKYS** [comment]
It is ready

**Comment by RSKYS** [comment]
Last one is for Tauon

**Comment by RSKYS** [comment]
I'm sorry Willy, but with recent update of reverting back python3.9, Presence is fixed
I'm gonna update dependencies again.

Regards, Pouria.

**Comment by willysr** [comment]
i pushed telegram to 3.2.1 i think in my branch

**Comment by RSKYS** [comment]
mdbook
lowdown
nix

Were my nix builds ok?

**Comment by willysr** [comment]
please make permission 644, not 755

**Comment by RSKYS** [comment]
> please make permission 644, not 755
Which one?
Uh, mdbook requires to run directly via command by nix due build process
I can move it to opt and symlink it to bin,
Just tell me what to do

**Comment by RSKYS** [comment]
I close this thread, will PR nix and tauon seperately,
This request got a little messed up

**Comment by willysr** [comment]
the SlackBuild should be 644, not 755

**Pull request closed without merging**
