### PR TITLE
system/nix: Some extra hardcoded assurance.

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
I [realized late](https://github.com/SlackBuildsOrg/slackbuilds/pull/7040#issuecomment-2212332973) that it's started to spam root partition, again.
I'm not really happy with this, not at all; first patch updated.
2.13.6 was fine, but this needed extra hard adjustments.

Could you please test this? we'll think about it's merge later.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by RSKYS** [comment]
Seems it requires even dirtier trick..
No worries, I'm testing it on my own system personally + ci
If I corrected it, I'll push again and tell you to test it.

Thank you

**Comment by RSKYS** [comment]
Okay, I think I got it.
Please test this, thanks.

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by RSKYS** [comment]
Nice
That fixed it

**Comment by willysr** [comment]
do you want to merge this instead of https://git.slackbuilds.org/slackbuilds/commit/?id=4847d7829 ?

**Comment by RSKYS** [comment]
Yes please
Tell me what to do

**Comment by willysr** [comment]
merged

**Comment by RSKYS** [comment]
@willysr Sorry but one more thing:

image

Could you please verify that Larry Haja is active maintainer or not?
I sent this email almost 2 weeks ago.
I have no rush for this package, I just wanna know what should I do next.

**Comment by willysr** [comment]
i think he is inactive at this moment

**Comment by RSKYS** [comment]
I'll wait another week or two then, then with your permission, I'll take over.

**Pull request closed without merging**
