### PR TITLE
Fix Bumps

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
Non of these builds are mine, but they're whether old and unmaintained or use python2.. RIP
Worse of them all was picard, which requires PyQt4..
Jermey already told me he doesn't use Slackware much and granted me authorization for modifies.
I actually want to take over neither of them, just modified them for my needs as much as necessary which in this case is Tauon direct me to picard window for music tag edits;
Please merge

Regards,
Pouria.

### CODE REVIEW

**Comment by RSKYS** [comment]
Oh seems other ones from previous branch came along too. I close previous pull.

**Comment by RSKYS** [comment]
Is there any problem with this pull request?

**Comment by willysr** [comment]
Did you check other packages that depends on fasteners? does it break other packages by switching to python3?

**Comment by RSKYS** [comment]
Oh that,
Seems duplicity might get into issue with it;
Since my case only works with python3 I added 2 support alongside it too.

**Comment by RSKYS** [comment]
Is there any other problem?

**Comment by RSKYS** [comment]
Please notify me if there's problem with this merge
It's never taken this long
My last commits haven't even merged to master, they're all at "willysr" branch
And procedure will take way longer if this remains here, and not get merged to one of the branch at official SBo..
Can you tell me what's wrong?

**Comment by ArTourter** [comment]
@RSKYS  please refrain from pushing. We are all doing this in our spare time. releases will occur when they do, at the discretion of the admins. If it takes longer than you expect, then so bit it.

As for what is wrong with your merges, I cannot comment on what @willysr  thinks, but you are in part updating packages for which you are not the maintainer, for which you have said you do not wish to become the maintainer,... So maybe, the maintainers have something to say about this.

Additionally, your commits do not comply with the established practices of the group, e.g, the version to which the package is being updated is not specified (look at the changelog, "dir/package: updated for version x.y.z" is the usual format); the pull request contains multiple commits which needs to be checked one at a time; ....  @willysr also asked you if dependees were affected by your changes, and you said at least one might, without you providing more details or a fix for this issue; we cannot really update packages while dependees may get broken by the change since Slackware doesn't offer dependency checking; Slackbuilds maintainers/admins should try and ensure that all packages work within the repo. 

I do not speak for @willysr, but the more you push for your changes to be merge, with all the things mentioned above, the less the will of the admins may be to make the effort of working through it. In theory, submissions are closed until 15.0 is released, all this git PR facility is only provided to help out. If people abuse this, we might all lose out if it is close due to it being more hassle than it is worth.

just my 2p worth.

**Comment by RSKYS** [comment]
> @RSKYS please refrain from pushing. We are all doing this in our spare time. releases will occur when they do, at the discretion of the admins. If it takes longer than you expect, then so bit it.

I have these mostly ready, in spare time in past.
I don't except push I just want to talk about it
As you see my changes not breaking anything and I don't know what's the problem.


> Additionally, your commits do not comply with the established practices of the group, e.g, the version to which the package is being updated is not specified (look at the changelog, "dir/package: updated for version x.y.z" is the usual format); the pull request contains multiple commits which needs to be checked one at a time; .... @willysr also asked you if dependees were affected by your changes, and you said at least one might, without you providing more details or a fix for this issue; we cannot really update packages while dependees may get broken by the change since Slackware doesn't offer dependency checking; Slackbuilds maintainers/admins should try and ensure that all packages work within the repo.

Yes I quickly searched through all repo to see what's depended on fastenets just how @willysr told me;
I already have seperated repo for myself I don't use SBo really, but I do this out of passion for everybody and well only programs I've brought to Slackware;
If they make changes in time, I don't need to interfere.
There were so many things, I just committed as less as I could to get everything work.


> I do not speak for @willysr, but the more you push for your changes to be merge, with all the things mentioned above, the less the will of the admins may be to make the effort of working through it. In theory, submissions are closed until 15.0 is released, all this git PR facility is only provided to help out. If people abuse this, we might all lose out if it is close due to it being more hassle than it is worth.

I'm not trying to abuse anything gosh,
I just want them work with my program
Fine since I receive no official answer, what did you expect me to do?
Close it?
Yes I'm also annoyed by waiting, I'll close it.

**Comment by willysr** [comment]
you are changing from python2 to python3 and that's a big change as there are other packages that depends on fasters (https://slackbuilds.org/advsearch.php?q=fasteners&stype=revdep1). You need to convince us to take the change, but what if it breaks other packages? We would have to revert or make changes to other packages. Like @ArTourter said, we do this on our spare time since it's a voluntary work. Your PR is considered fast. I usually approve them weekly during normal cycle.

As for minor bump i don't mind taking them, but for new script or major changes, it's better to wait until the repo is settled. Current is still a moving target....

**Comment by RSKYS** [comment]
Yes, I saw and added python2 to fasterenrs
You can [see all final changes as well](https://github.com/SlackBuildsOrg/slackbuilds/pull/1039/files)

Nevermind, I closed it, the more I see it open, the more it distracts me and that's not really what I want.

**Pull request closed without merging**
