### PR TITLE
network/amavisd-new: Updated for version 2.13.1.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build network/amavisd-new

**Comment by willysr** [comment]
@pyllyukko can you retest this?

**Comment by pyllyukko** [comment]
> @pyllyukko can you retest this?

Fixed a bunch of stuff. Try now?

**Comment by willysr** [comment]
@sbo-bot: build network/amavisd-new

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
