### PR TITLE
Remove personal info.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
I'd like to remove my location and email info. If possible, I would prefer this to be completely scrubbed, but I understand that rewriting git history is messy/dangerous/non-ideal, so if this method is preferred it's still a better state than things are today.

CC:
@willysr

### CODE REVIEW

**Comment by willysr** [comment]
@ryanpcmcquen it's prefered to do it 1 commit per script or if you want to do it in one commit, it would have to wait until next development cycle

**Comment by willysr** [comment]
@ryanpcmcquen LibreOffice is now maintained by @cwilling not me

**Comment by willysr** [comment]
your changes in 60f8d6e is changing a lot of scripts that no longer maintained by you

**Comment by ryanpcmcquen** [comment]
@willysr sorry, I originally made the edits on a case insensitive filesystem, things should be resolved now and the changes should only be targeted to my old scripts.

**Comment by ryanpcmcquen** [comment]
@willysr I don't mind waiting until another cycle.

**Comment by willysr** [comment]
since we don't know when will the cycle begins, I will close this PR for now as there will be a lot of changes and I'm expecting major conflicts

**Comment by ryanpcmcquen** [comment]
@willysr can we re-open this now?

**Comment by willysr** [comment]
we are not yet open for next cycle
it will start when Patrick announced Beta on next Slackware release (which we don't know when)

**Comment by ryanpcmcquen** [comment]
Hmmm, I don't want to wait years. I still get a lot of spam to these emails and I wonder if this is why because these addresses do not exist in other places on the web.

**Comment by willysr** [comment]
you can make a PR for this, but 1 script per commit so that when public update happens, it will pick up those scripts individually. It will take some time to do the PR, so please do it in new PR (do not use this as this is based on old master branch).

**Comment by ryanpcmcquen** [comment]
Thank you.

**Comment by ryanpcmcquen** [comment]
@willysr are we close to the next cycle now?

**Comment by willysr** [comment]
No, Patrick hasn't labeled any Alpha yet

**Comment by ryanpcmcquen** [comment]
@willysr checking in again, is the beta for 15.1 out?

**Comment by willysr** [comment]
@ryanpcmcquen nope, you can always check the changelog :)

**Pull request closed without merging**
