### PR TITLE
New Additions

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/build2
@sbo-bot: build network/sngrep
@sbo-bot: build development/notepadnext
@sbo-bot: build graphics/qcustomplot

**Comment by willysr** [comment]
@sbo-bot: build development/build2

**Comment by willysr** [comment]
@sbo-bot: build development/notepadnext

**Comment by willysr** [comment]
@sbo-bot: build graphics/qcustomplot

**Comment by aclemons** [comment]
Sorry, forgot to restart the docker daemon after upgrading docker in this weeks update

**Comment by aclemons** [comment]
@sbo-bot: build development/build2

**Comment by aclemons** [comment]
@sbo-bot: build network/sngrep

**Comment by aclemons** [comment]
@sbo-bot: build graphics/qcustomplot

**Comment by willysr** [comment]
> # sbopkglint i586 development/build2
> 
> ```
> --- shared lib(s) in wrong dir for ARCH:
> -rw-r--r-- 1 root root 576348 Oct  9 13:08 usr/lib64/libbpkg-0.16.so
> -rw-r--r-- 1 root root 5099668 Oct  9 13:08 usr/lib64/libbuild2-0.16.so
> -rw-r--r-- 1 root root 198336 Oct  9 13:08 usr/lib64/libbuild2-autoconf-0.16-0.2.so
> -rw-r--r-- 1 root root 128848 Oct  9 13:08 usr/lib64/libbuild2-bash-0.16-0.16.so
> -rw-r--r-- 1 root root 412184 Oct  9 13:08 usr/lib64/libbuild2-bin-0.16-0.16.so
> -rw-r--r-- 1 root root 83552 Oct  9 13:08 usr/lib64/libbuild2-c-0.16-0.16.so
> -rw-r--r-- 1 root root 1463108 Oct  9 13:08 usr/lib64/libbuild2-cc-0.16-0.16.so
> -rw-r--r-- 1 root root 202708 Oct  9 13:08 usr/lib64/libbuild2-cli-0.16-0.16.so
> -rw-r--r-- 1 root root 136856 Oct  9 13:08 usr/lib64/libbuild2-cxx-0.16-0.16.so
> -rw-r--r-- 1 root root 124832 Oct  9 13:08 usr/lib64/libbuild2-in-0.16-0.16.so
> -rw-r--r-- 1 root root 257012 Oct  9 13:08 usr/lib64/libbuild2-kconfig-0.16-0.3.so
> -rw-r--r-- 1 root root 194636 Oct  9 13:08 usr/lib64/libbuild2-version-0.16-0.16.so
> -rw-r--r-- 1 root root 1147584 Oct  9 13:08 usr/lib64/libbutl-0.16.so
> -rw-r--r-- 1 root root 149432 Oct  9 13:08 usr/lib64/libodb-2.5.0-b.25.so
> -rw-r--r-- 1 root root 215380 Oct  9 13:08 usr/lib64/libodb-sqlite-2.5.0-b.25.so
> -rw-r--r-- 1 root root 50964 Oct  9 13:08 usr/lib64/libpkg-config-0.1.so
> -rw-r--r-- 1 root root 1473072 Oct  9 13:08 usr/lib64/libsqlite3-1.so
> --- ELF binaries/libraries should be executable:
> -rw-r--r-- 1 root root 576348 Oct  9 13:08 usr/lib64/libbpkg-0.16.so
> -rw-r--r-- 1 root root 5099668 Oct  9 13:08 usr/lib64/libbuild2-0.16.so
> -rw-r--r-- 1 root root 198336 Oct  9 13:08 usr/lib64/libbuild2-autoconf-0.16-0.2.so
> -rw-r--r-- 1 root root 128848 Oct  9 13:08 usr/lib64/libbuild2-bash-0.16-0.16.so
> -rw-r--r-- 1 root root 412184 Oct  9 13:08 usr/lib64/libbuild2-bin-0.16-0.16.so
> -rw-r--r-- 1 root root 83552 Oct  9 13:08 usr/lib64/libbuild2-c-0.16-0.16.so
> -rw-r--r-- 1 root root 1463108 Oct  9 13:08 usr/lib64/libbuild2-cc-0.16-0.16.so
> -rw-r--r-- 1 root root 202708 Oct  9 13:08 usr/lib64/libbuild2-cli-0.16-0.16.so
> -rw-r--r-- 1 root root 136856 Oct  9 13:08 usr/lib64/libbuild2-cxx-0.16-0.16.so
> -rw-r--r-- 1 root root 124832 Oct  9 13:08 usr/lib64/libbuild2-in-0.16-0.16.so
> -rw-r--r-- 1 root root 257012 Oct  9 13:08 usr/lib64/libbuild2-kconfig-0.16-0.3.so
> -rw-r--r-- 1 root root 194636 Oct  9 13:08 usr/lib64/libbuild2-version-0.16-0.16.so
> -rw-r--r-- 1 root root 1147584 Oct  9 13:08 usr/lib64/libbutl-0.16.so
> -rw-r--r-- 1 root root 149432 Oct  9 13:08 usr/lib64/libodb-2.5.0-b.25.so
> -rw-r--r-- 1 root root 215380 Oct  9 13:08 usr/lib64/libodb-sqlite-2.5.0-b.25.so
> -rw-r--r-- 1 root root 50964 Oct  9 13:08 usr/lib64/libpkg-config-0.1.so
> -rw-r--r-- 1 root root 1473072 Oct  9 13:08 usr/lib64/libsqlite3-1.so
> FAILED
> Running test: 25-lafiles...OK
> Running test: 30-manpages...OK
> Running test: 35-desktop...OK
> Running test: 40-newconfig...OK
> Running test: 45-doinst...OK
> Running test: 50-icons...OK
> Running test: 60-usr_info...OK
> Running test: 65-python...OK
> Running test: 70-tmp_path...OK
> Running test: 75-static_libs...OK
> Running test: 85-perl...OK
> !!! build2-0.16.0-i586-1_SBo.txz: 2 failures⛔️
> ```

i think this is caused by the 01-destlibdir.patch which changed everything to /usr/lib64 where as this script support for x86 architecture as well. This needs to be fixed first

**Comment by willysr** [comment]
@sbo-bot: build development/nodepadnext

**Comment by willysr** [comment]
@sbo-bot: build development/notepadnext

**Pull request closed without merging**
