### PR TITLE
network/discord: Updated for version 0.0.16.

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
Discord 0.0.15 revoked for almost more than 3 months.
I've tried to contact the maintainer, no any respond for a week,
I mean atleast he can say "SlackBuilds is closed" or "Need extra care", anything.

I'm also tracking certain issue with pypresence to see if there's any problem with it, python3.10 or Discord itself;
I'll wait a little bit longer to see what should we do about this..

Regards,
Pouria.

### CODE REVIEW

**Comment by willysr** [comment]
Jeremy is still active maintaining his scripts so i will keep him as maintainer but i will take the version bump

**Comment by RSKYS** [comment]
Yeah.. that's why I didn't really want to take over,
But where can I suggest him this?
> mkdir -p $PKG/opt
mv $PKG/usr/share/discord $PKG/opt/
rm -f $PKG/usr/share/pixmaps/$PRGNAM.png
mv $PKG/opt/discord/$PRGNAM.png $PKG/usr/share/pixmaps/
rm -f $PKG/opt/discord/$PRGNAM.desktop $PKG/usr/share/applications/$PRGNAM.desktop
cp $CWD/$PRGNAM.desktop $PKG/usr/share/applications/

It'd be not bad moving to /opt
I hope he check his email later

**Comment by RSKYS** [comment]
I set him back to maintainer by the way.
Can I merge now?
Let him decide if he like the changes or not, is something like this possible?

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
