### PR TITLE
desktop/nwg-hello: Updated for version 0.2.1.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**
added new python3-build dependency for the changed build method.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-hello

**Comment by willysr** [comment]
@mac-a-r0ni well, it failed

**Comment by mac-a-r0ni** [comment]
@willysr I pushed the fix, apologies on the missed dep.

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-hello

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
