### PR TITLE
Switch academic/root to cmake

### PR DESCRIPTION
**Pull request by arabusov**
This will allow us to compile ROOT v6.14 or higher. Current version
is v6.24-06. Many thanks to ponce for fixing some typos in this update.

### CODE REVIEW

**Comment by willysr** [comment]
Please don't remove the new template

**Comment by arabusov** [comment]
@willysr could you please clarify what do you mean? Specifically, [this](https://slackbuilds.org/templates/cmake-template.SlackBuild) template?

**Comment by willysr** [comment]
https://git.slackbuilds.org/templates/tree/cmake-template.SlackBuild

**Comment by arabusov** [comment]
@willysr what I did was based on the previous version of the script (thus, I didn't remove any template), and what you are proposing is to rewrite the script completely from scratch based on the template. It will take some time.

**Comment by willysr** [comment]
No, you just need to make changes needed without having to remove the old code since it has been updated to comply with the new template

**Comment by arabusov** [comment]
@willysr Ok, it seems in summer 2021 there were some updates I missed (fd9245fe0afce3ede6aa51b99d981bdf0552f9d2, 63daf9f79a0016bbf3a712a1d1bdcfdcb724fded), am I right?

**Comment by arabusov** [comment]
@willysr using keyword "root" is not appropriate for searching in the repos, it's better to look at the file log itself: https://git.slackbuilds.org/slackbuilds/log/academic/root/root.SlackBuild

Here I see three commits from Heinz Wiesinger I didn't take into account. I'll fix my pull request accordingly.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
