### PR TITLE
development/gitlab-cli: Updated for version 1.43.0

### PR DESCRIPTION
**Pull request by DinizBortolotto**
development/gitlab-cli: Updated for version 1.43.0

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/gitlab-cli

**Comment by willysr** [comment]
merged

**Comment by DinizBortolotto** [comment]
@willysr could you please check if something gone wrong with this PR?
SlackBuilds.org still showing version 1.42.0 for gitlab-cli
[https://slackbuilds.org/repository/15.0/development/gitlab-cli/](url)

**Comment by willysr** [comment]
i might have missed this PR since i accidentally force pushed some changes and your PR is overwritten. i will get it fixed by next public update

**Pull request closed without merging**
