### PR TITLE
system/ipmitool: Updated version 1.8.19

### PR DESCRIPTION
**Pull request by emman**
I updated to the latest version and removed patches that are now included in this release.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/ipmitool

**Comment by willysr** [comment]
@emman this failed to find the source

**Comment by willysr** [comment]
@emman it would be easier to grab the source from github
https://github.com/ipmitool/ipmitool

**Comment by emman** [comment]
Thanks a lot @willysr , I changed the url to use github, it compiles fine with slackrepo, and passes the sbolint and sbopkglint checks.

**Comment by willysr** [comment]
@sbo-bot: build system/ipmitool

**Comment by willysr** [comment]
@emman this script seems to be downloading something during build
can you try running the script with unshare -n ipmitool.SlackBuild ?

**Comment by emman** [comment]
Hi @willysr , yes, the compilation process needs to download the IANA PEN database (it weighs 4.6MB, I didn't want to add this file to the source). Slackrepo compiles correctly if I change the CHROOT configuration variable to "n". Any suggestions on how to solve the problem?

I tried running unshare -n ipmitool.Slackbuild and it fails in name resolution

_--2024-11-02 11:19:45-- https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers
Resolving www.iana.org (www.iana.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.iana.org’
FAILED to download the IANA PEN database

Thanks.

**Comment by willysr** [comment]
@emman we try to avoid downloading something in the background, so please make sure you put them into the DOWNLOAD section and extract them during build
i will close this PR and please rebase your changes from latest master

**Pull request closed without merging**
