### PR TITLE
multimedia/sickchill: Tweak rc file and remove dep version req

### PR DESCRIPTION
**Pull request by bassmadrigal**
Due to this update, [this commit](bf9012a) for #5451 will need to be slightly tweaked once the SQLAlchemy-wip branch is ready to be accepted.

### CODE REVIEW

**Comment by willysr** [comment]
should i put them in SQLAlchemy-wip branch instead?

**Comment by bassmadrigal** [comment]
No, the fixes are unrelated to that branch.

If it doesn't get pushed this week, I can submit a new commit after the public update to replace the one in that branch.

**Comment by willysr** [comment]
it's fine, i can merge it this week
i'm just busy testing new webkit2gtk{4.1}

**Comment by willysr** [comment]
@sbo-bot: build multimedia/sickchill

**Comment by bassmadrigal** [comment]
Whoops! I thought I had checked the build before submitting, but I guess I didn't. It should build now.

**Comment by willysr** [comment]
@sbo-bot: build multimedia/sickchill

**Comment by willysr** [comment]
@bassmadrigal since SQLAlchemy-wip branch is merged, this failed to build against those commits

**Comment by willysr** [comment]
@sbo-bot: build multimedia/sickchill

**Comment by willysr** [comment]
hmm.. i can't apply the patch from this PR cleanly on top of my branch

**Comment by willysr** [comment]
@sbo-bot: build multimedia/sickchill

**Comment by bassmadrigal** [comment]
> hmm.. i can't apply the patch from this PR cleanly on top of my branch

I haven't worked with multiple branches like that in GitHub, so I'm not sure the best way to try and fix it (but I'm open to guidance on how to do it).

If it's easier, we can just close this PR and I can submit a new PR after the public update with the SQLAlchemy update so there are no merge conflicts.

**Comment by willysr** [comment]
ok

**Pull request closed without merging**
