### PR TITLE
Updated for 10.1, and modified some user and group settings, as requested

### PR DESCRIPTION
**Pull request by cduston44**

### CODE REVIEW

**Comment by willysr** [comment]
Hi, please make the permission changes in the SlackBuild, not in the git. 
Files in git stays in 644 permission
also, please use TMP=${TMP:-/tmp/SBo}

**Comment by aclemons** [comment]
> please use TMP=${TMP:-/tmp/SBo}

I think I ran across this recently with this build - I think it won't work if TMP is set `/tmp/SBo`

see https://github.com/SlackBuildsOrg/slackbuilds/commit/ab754938838124ebb2f8a6df46bf55357059be67

**Comment by willysr** [comment]
ah ok, then i guess i didn't read the comment

**Comment by willysr** [comment]
@sbo-bot: build x86_64

**Comment by willysr** [comment]
@sbo-bot: build academic/sage

**Comment by willysr** [comment]
i think this is a minor issue @aclemons ?

**Comment by aclemons** [comment]
> i think this is a minor issue @aclemons ?

Agreed. The file ownership in the package has been like this already. See this comment:

https://github.com/SlackBuildsOrg/slackbuilds/pull/3043#issuecomment-1661997328


The symlink errors were there in version 10.0:

```sh
# sbopkglint sage-10.0-x86_64-1_SBo.txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding sage-10.0-x86_64-1_SBo.txz to /tmp/SBo/sbopkglint.uNZ9Rk ...OK
Running pre-doinst test...OK
Installing sage-10.0-x86_64-1_SBo.txz to /tmp/SBo/sbopkglint.uNZ9Rk ...OK
Running test: 05-basic-sanity...
--- package contains broken absolute symlinks:
lrwxrwxrwx 1 root root 71 Sep 25 21:43 ./opt/sage/local/var/lib/sage/venv-python3.9/share/jupyter/nbextensions/threejs-sage -> /tmp/SBo/slackrepo.NefNoN/build_sage/sage-10.0/local/share/threejs-sage
___ note: package contains symlinks outside the package (which is OK, if intentional):
lrwxrwxrwx 1 root root 16 Sep 25 21:43 ./opt/sage/local/var/lib/sage/venv-python3.9/bin/python3 -> /usr/bin/python3
--- package contains broken relative symlinks:
lrwxrwxrwx 1 root root 13 Sep 25 21:43 ./opt/sage/build/pkgs/sagelib/src/Pipfile-dist -> ../../Pipfile
lrwxrwxrwx 1 root root 28 Sep 25 21:43 ./opt/sage/pkgs/sage-conf_pypi/sage_root/.homebrew-build-env -> ../../../.homebrew-build-env
lrwxrwxrwx 1 root root 13 Sep 25 21:43 ./opt/sage/pkgs/sage-conf_pypi/sage_root/build/pkgs/sagelib/src/Pipfile-dist -> ../../Pipfile
lrwxrwxrwx 1 root root 13 Sep 25 21:43 ./opt/sage/pkgs/sagemath-standard/Pipfile-dist -> ../../Pipfile
___ note: package contains empty dirs, are these necessary?
drwxr-xr-x 2 root root 6 Aug  1 12:56 ./opt/sage/local/etc
drwxr-xr-x 2 root root 6 Aug  1 13:01 ./opt/sage/local/include/ecl/gc/private
drwxr-xr-x 2 root root 6 Aug  1 12:58 ./opt/sage/local/lib/gap/bin
drwxr-xr-x 2 root root 6 Aug  1 12:58 ./opt/sage/local/share/gap/pkg
drwxr-xr-x 2 root root 6 Aug  1 12:56 ./opt/sage/local/var/lib/sage/scripts
drwxr-xr-x 2 root root 6 Aug  1 12:56 ./opt/sage/local/var/lib/sage/venv-python3.9/include
drwxr-xr-x 2 root root 6 Aug  1 13:18 ./opt/sage/local/var/lib/sage/venv-python3.9/var/tmp/sage/build
drwxr-xr-x 2 root root 6 Aug  1 13:16 ./opt/sage/local/var/tmp/sage/build
drwxr-xr-x 2 root root 6 Aug  1 12:56 ./usr/share/pixmaps
FAILED
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...
--- ELF binaries/libraries should be executable:
-rw-r--r-- 1 root root 51600 Aug  1 13:26 opt/sage/local/lib/libcliquer.so.1.0.21
FAILED
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...usr/share/applications/sage-notebook.desktop: hint: value "Education;Science;Math;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
OK
Running test: 40-newconfig...
--- doinst.sh doesn't handle .new config files:
-rw-r--r-- 1 root root 65409 Aug  1 12:56 ./opt/sage/local/lib/gap/pkg/atlasrep/gap/utils.gi.new
FAILED
Running test: 45-doinst...OK
Running test: 50-icons...OK
Running test: 60-usr_info...OK
Running test: 65-python...OK
Running test: 70-tmp_path...OK
Running test: 75-static_libs...OK
Running test: 85-perl...OK
!!! sage-10.0-x86_64-1_SBo.txz: 4 failures
```

The .new file detection looks like a false-positive from sbo-maintainer-tools here.

I gather the author has already tested the package and it works, so that would be the important part imho.

**Comment by cduston44** [comment]
Author here - I'm afraid I don't understand most of this, but I will try...

The package does run, so perhaps that file detection thing is in error.

As far as the permissions go, I thought I fixed it - everything is 644 except the profile.d, which needs executable permissions (744), right? Or should I do something like changing the permissions at install time?

The lack of icons comes from these lines in install.sh:

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
if [ -x /usr/bin/gtk-update-icon-cache ]; then
/usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
fifi

icon-theme.cache doesn't exist on my machine, but I can remove them if needed.

Does that cover it?

CLD

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
