### PR TITLE
development/avrdude: Updated for version 8.0.

### PR DESCRIPTION
**Pull request by newHeiko**

### CODE REVIEW

**Comment by newHeiko** [comment]
Seems like avr8-burn-o-mat does not work with recent avrdude versions. I failed to check with earlier versions, so I don't know how long it hasn't worked, but I see positive reports with avrdude 6 and it fails (configuration can't find a programmer) with avrdude 7.3.

Since nobody ever complained (that I know of), I'd rather keep updating avrdude to support more recent microcontrollers and programmers than getting back to a working avr8-burn-o-mat.

Thoughts?

Heiko

**Comment by willysr** [comment]
@sbo-bot: build development/avrdude

**Comment by willysr** [comment]
@newHeiko we need to make sure all the other scripts that depends on this PR works as usual

**Comment by willysr** [comment]
@sbo-bot: build development/avr8-burn-o-mat

**Comment by willysr** [comment]
well, it builds just fine
merged

**Pull request closed without merging**
