### PR TITLE
3 version bumps and one README update

### PR DESCRIPTION
**Pull request by bassmadrigal**
network/discord: Version bump to 0.0.30
libraries/rarfile: Version bump to 4.1
multimedia/inputstream.adaptive: Version bump to 20.3.13

python/python3-llvmlite: Upgrade not possible note & SlackBuild cleanup
\- No build # bump needed

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 network/discord

**Comment by aclemons** [comment]
@sbo-bot: build libraries/rarfile

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-llvmlite

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/inputstream.adaptive

**Comment by aclemons** [comment]
network/discord is fine for a binary repackaging

**Comment by aclemons** [comment]
> chmod 755 $PKG/usr/lib64/kodi/addons/inputstream.adaptive/libssd_wv.so

@bassmadrigal Could you update this to use LIBDIRSUFFIX please?

**Comment by aclemons** [comment]
In the interest of getting this in the weekly update, I'll adjust this.

**Comment by bassmadrigal** [comment]
Dang, I try and improve my builds by using sbopkglint, which causes me to notice an issue that needs fixing, but I then make a rookie mistake of not using LUBDIRSUFFIX for that fix.

Thanks for the catch and fix!

**Pull request merged**
