### PR TITLE
graphics/graphviz: updated for version 7.0.5

### PR DESCRIPTION
**Pull request by Ythogtha**
Looks like packages requiring it are OK.

### CODE REVIEW

**Comment by aclemons** [comment]
```
Installing /var/lib/slackrepo/SBo/packages/15.0/i586/graphics/graphviz/graphviz-7.0.5-i586-2_SBo.txz to /tmp/sbopkglint.DtWTv8 ...--- forbidden directory exists: usr/share/doc
```

**Comment by aclemons** [comment]
Could you check this doc dir please?

**Comment by Ythogtha** [comment]
You're right, it was leaving an empty /usr/share/doc/ directory, I reorganized the moving of docs in the Slackbuild, it is now OK !

**Comment by aclemons** [comment]
```
# buildpkg i586 graphics/graphviz
sbolint: graphviz checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Thu Jan  5 11:07:50 GMT 2023
revision: 1d81d8671fcd7ca86d9c3edcd6ca2ca07c24916b
title:    graphics/graphviz: Updated for version 7.0.5.

================================================================================
graphics/graphviz                                                       11:12:40
================================================================================

Calculating dependencies ... 
Hints for graphics/graphviz:
  ADDREQUIRES="gts DevIL ocaml"
Dependency tree:
graphics/graphviz (update for version 7.0.5)
  libraries/gts (ok)
  libraries/DevIL (ok)
  development/ocaml (ok)

Building graphics/graphviz (update for version 7.0.5) ----------------- 11:12:41
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
ocaml-4.13.1-i586-2_SBo: A functional programming language ............. [ 405M]
DevIL-1.8.0-i586-5_SBo: image library .................................. [ 2.7M]
gts-0.7.6-i586-4_SBo: GNU Triangulated Surface Library ................. [ 1.3M]
Running graphviz.SlackBuild ...                                     ETA 11:14:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./graphviz.SlackBuild
Build time 91 sec, peak load 8.62, peak memory 176M, peak tmp 148M
Built ok:  graphviz-7.0.5-i586-1_SBo.txz                                11:14:22
Testing package graphviz-7.0.5-i586-1_SBo.txz ... done.
Test installing graphviz-7.0.5-i586-1_SBo.txz ...
graphviz-7.0.5-i586-1_SBo: Graph Visualization ......................... [  13M]
Unmounting chroot ... done.
Backed up: graphviz-3.0.0-i586-2_SBo.txz
:-) graphics/graphviz Updated for version 7.0.5 (-:

================================================================================
SUMMARY                                                                 11:14:25
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-05_11:12:39.log
Runtime:     0h 1m 46s
Updated:     1
  graphics/graphviz/graphviz-7.0.5-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/i586/graphics/graphviz/graphviz-7.0.5-i586-1_SBo.txz to /tmp/sbopkglint.ZKcqhB ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== graphviz-7.0.5-i586-1_SBo.txz: All tests passed
```

```
# buildpkg x86_64 graphics/graphviz
sbolint: graphviz checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Thu Jan  5 11:07:50 GMT 2023
revision: 1d81d8671fcd7ca86d9c3edcd6ca2ca07c24916b
title:    graphics/graphviz: Updated for version 7.0.5.

================================================================================
graphics/graphviz                                                       11:22:39
================================================================================

Calculating dependencies ... 
Hints for graphics/graphviz:
  ADDREQUIRES="gts DevIL ocaml"
Dependency tree:
graphics/graphviz (update for version 7.0.5)
  libraries/gts (ok)
  libraries/DevIL (ok)
  development/ocaml (ok)

Building graphics/graphviz (update for version 7.0.5) ----------------- 11:22:40
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
ocaml-4.13.1-x86_64-2_SBo: A functional programming language ........... [ 430M]
DevIL-1.8.0-x86_64-5_SBo: image library ................................ [ 2.7M]
gts-0.7.6-x86_64-4_SBo: GNU Triangulated Surface Library ............... [ 1.5M]
Running graphviz.SlackBuild ...                                     ETA 11:24:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./graphviz.SlackBuild
Build time 83 sec, peak load 4.58, peak memory 224M, peak tmp 148M
Built ok:  graphviz-7.0.5-x86_64-1_SBo.txz                              11:24:12
Testing package graphviz-7.0.5-x86_64-1_SBo.txz ... done.
Test installing graphviz-7.0.5-x86_64-1_SBo.txz ...
graphviz-7.0.5-x86_64-1_SBo: Graph Visualization ....................... [  13M]
Unmounting chroot ... done.
Backed up: graphviz-3.0.0-x86_64-2_SBo.txz
:-) graphics/graphviz Updated for version 7.0.5 (-:

================================================================================
SUMMARY                                                                 11:24:14
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-05_11:22:39.log
Runtime:     0h 1m 35s
Updated:     1
  graphics/graphviz/graphviz-7.0.5-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/x86_64/graphics/graphviz/graphviz-7.0.5-x86_64-1_SBo.txz to /tmp/sbopkglint.RvRAaK ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== graphviz-7.0.5-x86_64-1_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
LGTM - staged to my branch. I'll rebuild the whole repo now to make sure none of the builds using graphviz fail to build.

**Comment by aclemons** [comment]
ok - 37 builds failed, but none due to graphviz. Of course, I have only checked that things compile, not that they work.

**Pull request closed without merging**
