### PR TITLE
Update librewolf

### PR DESCRIPTION
**Pull request by kovmir**

### CODE REVIEW

**Comment by aclemons** [comment]
This fails sbopkglint checks:

```
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/network/librewolf/librewolf-112.0.2-x86_64-1_SBo.txz to /tmp/sbopkglint.Tvr4Fx ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/network/librewolf/librewolf-112.0.2-x86_64-1_SBo.txz to /tmp/sbopkglint.Tvr4Fx ...OK
Running test: 05-basic-sanity...
lrwxrwxrwx 1 root root 48 May 12 13:39 ./usr/share/librewolf-112.0.2/Changelog.md -> ../../../opt/librewolf-112.0.2/docs/Changelog.md
lrwxrwxrwx 1 root root 42 May 12 13:39 ./usr/share/librewolf-112.0.2/LICENSE -> ../../../opt/librewolf-112.0.2/LICENSE.txt
lrwxrwxrwx 1 root root 40 May 12 13:39 ./usr/share/librewolf-112.0.2/appimg-README.md -> ../../../opt/librewolf-112.0.2/README.md
FAILED
--- package contains broken relative symlinks:
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! librewolf-112.0.2-x86_64-1_SBo.txz: 1 failures
```

The previous version was fine:

```
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/network/librewolf/librewolf-111.0-x86_64-1_SBo.txz to /tmp/sbopkglint.XmyH8t ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/network/librewolf/librewolf-111.0-x86_64-1_SBo.txz to /tmp/sbopkglint.XmyH8t ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== librewolf-111.0-x86_64-1_SBo.txz: All tests passed
```

Could you check please?

**Comment by kovmir** [comment]
There you go, fixed broken symlinks.

**Comment by willysr** [comment]
can you squash this commit into a single commit with proper commit message?
category/script: Updated for version XXX

**Comment by kovmir** [comment]
Is that ok?

**Comment by willysr** [comment]
this one should not happened: 
Merge branch 'SlackBuildsOrg:master' into master

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
