### PR TITLE
libraries/CGAL: Updated for version 5.6

### PR DESCRIPTION
**Pull request by wsdookadr**

### CODE REVIEW

**Comment by wsdookadr** [comment]
@sbo-bot: build libraries/CGAL

**Comment by willysr** [comment]
@sbo-bot: build libraries/CGAL

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
i think i made a mistake on this
CGAL is supposed to be kept at 4.2
we have CGAL5 for version 5.6 already, so this PR is no longer needed

**Pull request closed without merging**
