### PR TITLE
academic/root: Updated for version 6.30/08, removed gsl_shared flag.

### PR DESCRIPTION
**Pull request by arabusov**

### CODE REVIEW

**Comment by arabusov** [comment]
@sbo-bot: build academic/root

**Comment by willysr** [comment]
@sbo-bot: build academic/root

**Comment by willysr** [comment]
@arabusov this failed to build

**Comment by arabusov** [comment]
@willysr what access rights are required for `/etc/ld.so.conf` and `/etc/ld.so.conf.d`? On my system I have 644 and 755, shall I set them explicitly in the Slackbuild?

**Comment by willysr** [comment]
that's the correct permission

**Comment by willysr** [comment]
i think you can mark it as x86_64 only

**Comment by arabusov** [comment]
> that's the correct permission

Ok. But why the "sanity" test reports
```
--- forbidden directory exists: etc/ld.so.conf.d
--- forbidden file: etc/ld.so.conf
```

**Comment by willysr** [comment]
you need to ask Urchlay for that. He is the one that build the sbolint and sbopkglint tool

**Comment by arabusov** [comment]
> i think you can mark it as x86_64 only

Occasionally, I use TP X31, a very nice machine, and it would be nice to have ROOT there as well. I'll try to figure out why it fails with newer ROOT version. Btw, the ROOT team managed to compile it for 32 bit Windows: https://root.cern/releases/release-63008/

**Comment by willysr** [comment]
i will merge this with x86_64 only for now.

**Pull request closed without merging**
