### PR TITLE
libraries/folly: Updated for version 20220722_437b29d

### PR DESCRIPTION
**Pull request by earies**

### CODE REVIEW

**Comment by aclemons** [comment]
This fails to build for me on an up to date, clean x86_64 machine.

**Comment by aclemons** [comment]
Snippet from the build lg
```
[ 38%] Building CXX object CMakeFiles/folly_base.dir/folly/experimental/io/IoUringBackend.cpp.o
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:548:18: error: non-type template parameters of class type only available with ‘-std=c++20’ or ‘-std=gnu++20’
  548 | template <class T...>
      |                  ^~~
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:549:17: error: ‘ProvidedBufferRing’ was not declared in this scope
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                 ^~~~~~~~~~~~~~~~~~
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:549:35: error: template argument 1 is invalid
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                                   ^
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:549:35: error: template argument 2 is invalid
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp: In constructor ‘folly::IoUringBackend::IoUringBackend(folly::IoUringBackend::Options)’:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:734:22: error: ‘IORING_SETUP_COOP_TASKRUN’ was not declared in this scope
  734 |     params_.flags |= IORING_SETUP_COOP_TASKRUN;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp: In lambda function:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:774:11: error: ‘io_uring_register_ring_fd’ was not declared in this scope; did you mean ‘io_uring_register_eventfd’?
  774 |       if (io_uring_register_ring_fd(&ioRing_) < 0) {
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |           io_uring_register_eventfd
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp: In constructor ‘folly::IoUringBackend::IoUringBackend(folly::IoUringBackend::Options)’:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:827:45: error: no matching function for call to ‘makeProvidedBufferRing(folly::IoUringBackend*, uint16_t, size_t&, int&, int&)’
  827 |     bufferProvider_ = makeProvidedBufferRing(
      |                       ~~~~~~~~~~~~~~~~~~~~~~^
  828 |         this,
      |         ~~~~~                                
  829 |         nextBufferProviderGid(),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
  830 |         options.initalProvidedBuffersCount,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  831 |         sizeShift,
      |         ~~~~~~~~~~                           
  832 |         ringShift);
      |         ~~~~~~~~~~                           
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:549:37: note: candidate: ‘template<<typeprefixerror>...<anonymous> > int folly::{anonymous}::makeProvidedBufferRing()’
  549 | std::unique_ptr<ProvidedBufferRing> makeProvidedBufferRing() {
      |                                     ^~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:549:37: note:   template argument deduction/substitution failed:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:827:45: note:   candidate expects 0 arguments, 5 provided
  827 |     bufferProvider_ = makeProvidedBufferRing(
      |                       ~~~~~~~~~~~~~~~~~~~~~~^
  828 |         this,
      |         ~~~~~                                
  829 |         nextBufferProviderGid(),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~             
  830 |         options.initalProvidedBuffersCount,
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
  831 |         sizeShift,
      |         ~~~~~~~~~~                           
  832 |         ringShift);
      |         ~~~~~~~~~~                           
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp: In member function ‘void folly::IoUringBackend::cancel(folly::IoUringBackend::IoSqeBase*)’:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:1474:3: error: ‘io_uring_prep_cancel64’ was not declared in this scope; did you mean ‘io_uring_prep_cancel’?
 1474 |   io_uring_prep_cancel64(sqe, (uint64_t)ioSqe, 0);
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   io_uring_prep_cancel
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:1476:26: error: ‘IORING_FEAT_CQE_SKIP’ was not declared in this scope; did you mean ‘IORING_FEAT_NODROP’?
 1476 |   if (params_.features & IORING_FEAT_CQE_SKIP) {
      |                          ^~~~~~~~~~~~~~~~~~~~
      |                          IORING_FEAT_NODROP
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:1477:19: error: ‘IOSQE_CQE_SKIP_SUCCESS’ was not declared in this scope
 1477 |     sqe->flags |= IOSQE_CQE_SKIP_SUCCESS;
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp: In member function ‘bool folly::IoUringBackend::kernelHasNonBlockWriteFixes() const’:
/tmp/SBo/1fAHcf/build_folly/folly-437b29dd062a40c741b2147827025a2f413b76c7/folly/experimental/io/IoUringBackend.cpp:1830:29: error: ‘IORING_FEAT_LINKED_FILE’ was not declared in this scope
 1830 |   return params_.features & IORING_FEAT_LINKED_FILE;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/folly_base.dir/build.make:1686: CMakeFiles/folly_base.dir/folly/experimental/io/IoUringBackend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:193: CMakeFiles/folly_base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by willysr** [comment]
any update @earies  ?

**Comment by willysr** [comment]
no update since last month, closing this for now

**Pull request closed without merging**
