### PR TITLE
multimedia/spot: Updated for version 0.4.1

### PR DESCRIPTION
**Pull request by perrin4869**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build multimedia/spot

**Comment by willysr** [comment]
@sbo-bot: build multimedia/spot

**Comment by willysr** [comment]
i don't think this can be compiled under Slackware 15.0 as it requires newer glib2

**Comment by perrin4869** [comment]
Yeah I was fearing it might be the case, guess I'll close this for now.
Just out of curiosity, do you know why rust16 is failing to find the shared lib?

**Pull request closed without merging**
