### PR TITLE
update yabridge and libraries

### PR DESCRIPTION
**Pull request by noisecode3**
I have tested compiling other software for the libs, but I want to test more vst3sdk. I think I had problems compiling lilv or some dependency of it, please check it out. Happy new year !!

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by noisecode3** [comment]
oh sorry i forgot to fixed that, https://github.com/chriskohlhoff/asio/archive/asio-1-28-2/asio-1.28.2.tar.gz I should be asio-1-28-2 that was the tag problem.

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by willysr** [comment]
@noisecode3 still failed here

**Comment by willysr** [comment]
@sbo-bot: build libraries/vst3sdk

**Comment by willysr** [comment]
@sbo-bot: build audio/clap

**Comment by noisecode3** [comment]
asio-1.28.2.tar.gz that fails is weird it works for me with wget

**Comment by willysr** [comment]
@sbo-bot: build libraries/asio

**Comment by noisecode3** [comment]
ye that's weird I'm building it right now. I not sure right now

**Comment by noisecode3** [comment]
its a link redirect renaming thing ?

**Comment by willysr** [comment]
@sbo-bot: build libraries/bitsery

**Comment by willysr** [comment]
@sbo-bot: build libraries/ghc_filesystem

**Comment by noisecode3** [comment]
Okej but then we might use this link https://github.com/chriskohlhoff/asio/archive/refs/tags/asio-1-28-2.tar.gz but i have to change - into . the horror, other suggestions?

**Comment by willysr** [comment]
@sbo-bot: build libraries/function2

**Comment by noisecode3** [comment]
asio-1.28.2.tar.gz: Cannot open: No such file or directory 
something is just off with that i have the file right here for my link

**Comment by willysr** [comment]
@noisecode3 probably better to remove make test in function2 ?

**Comment by willysr** [comment]
@sbo-bot: build libraries/ghc_filesystem

**Comment by willysr** [comment]
@sbo-bot: build libraries/tomlplusplus

**Comment by aclemons** [comment]
> @noisecode3 probably better to remove make test in function2 ?

Relevant issue I opened 1 year ago today it seems:

https://github.com/Naios/function2/issues/57

**Comment by willysr** [comment]
so we just need to fix function2 (remove make test) and find the correct URL for yabridge

**Comment by aclemons** [comment]
The correct url for asio is:

https://github.com/chriskohlhoff/asio/archive/asio-1-28-2/asio-asio-1-28-2.tar.gz

the project name (asio) + the tag name (asio-1-28-2) with .tar.gz.

**Comment by willysr** [comment]
@sbo-bot: build libraries/asio

**Comment by noisecode3** [comment]
> > @noisecode3 probably better to remove make test in function2 ?
> 
> Relevant issue I opened 1 year ago today it seems:
> 
> [Naios/function2#57](https://github.com/Naios/function2/issues/57)
Oh shit, but if it don't pass the test on slackware32 its not really stable. Of course one should be able to ignore it and build the package anyway. But should be warned a little bit. I make the test optional. I should investigate if am building it correctly on 32-bit. tomorrow

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by willysr** [comment]
> > > @noisecode3 probably better to remove make test in function2 ?
> > 
> > 
> > Relevant issue I opened 1 year ago today it seems:
> > [Naios/function2#57](https://github.com/Naios/function2/issues/57)
> > Oh shit, but if it don't pass the test on slackware32 its not really stable. Of course one should be able to ignore it and build the package anyway. But should be warned a little bit. I make the test optional. I should investigate if am building it correctly on 32-bit. tomorrow

I removed the test for now to merge this PR. You can send more PR once public update is done if you have found the solution to run the tests properly in x86

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
