### PR TITLE
academic/qucs: minor change + update DEPS

### PR DESCRIPTION
**Pull request by Fellypao**
- Add qt4 to REQUIRES
- Added "source /etc/profile.d/qt4.sh" to qucs.SlackBuild, as suggested in the libraries/qt4/README_SBo.txt file

### CODE REVIEW

**Comment by willysr** [comment]
This patch failed for me
```
Applying: academic/getdp: Updated for version 3.4.0
error: patch failed: academic/getdp/README:6
error: academic/getdp/README: patch does not apply
error: patch failed: academic/getdp/getdp.SlackBuild:1
error: academic/getdp/getdp.SlackBuild: patch does not apply
error: patch failed: academic/getdp/getdp.info:1
error: academic/getdp/getdp.info: patch does not apply
Patch failed at 0001 academic/getdp: Updated for version 3.4.0
```

**Comment by willysr** [comment]
I think it's because too many changes happening already on master branch and you haven't rebased your changes against latest master branch

**Comment by Fellypao** [comment]
I don't know git very well, but `git rebase master` returns:
_Current branch master is up to date._

For some unknown reason, my master branch was 6 commits ahead SlackBuildsOrg:master
That is, the commits 
ce3f434 6ddac03 11c0191 435e08a a928a1b 
from PR #1102, were not recognized as merged into SlackBuildsOrg:master in my side.

The only commit I did today was 43f9bca, in academic/qucs.

Anyway, last time I tried to deal with rebase I failed miserably... so, I prefer to close this PR and send by email the changes made on academic/qucs.

**Comment by willysr** [comment]
you should make your changes on a separate branch and leave master branch to always sync with SBo mirrors
so here's the flow
checkout latest master branch
make local branch
make changes and commit
push changes
submit PR

**Comment by willysr** [comment]
ok i took the single commit and push it to my branch

**Comment by Fellypao** [comment]
> you should make your changes on a separate branch and leave master branch to always sync with SBo mirrors
> so here's the flow
> checkout latest master branch
> make local branch
> make changes and commit
> push changes
> submit PR

Ok. Thank you for the tips. I'll try this way next time.

**Pull request closed without merging**
