### PR TITLE
winetricks and protonup update

### PR DESCRIPTION
**Pull request by noisecode3**
Hi, I tried to update protontricks but when I did I was faced with systemd error and it would just hang.
This was from compiling from https://pypi.org/project/protontricks/#files
It need some hacking, maybe its own Slackware fork.

I have tested winetricks and protonup and they work no problem :) here you go

```
protontricks --gui
pressure-vessel-wrap[18811]: W: libsystemd.so.0: cannot open shared object file: No such file or directory
winetricks GUI enabled, using zenity 3.44.0
pressure-vessel-adverb[18996]: W: sd_journal_stream_fd: No such file or directory
steam-runtime-launcher-service[19021]: E: Can't find session bus: Error spawning command line `dbus-launch --autolaunch=b5bd4716759322502f3753aa62f0eedf --binary-syntax --close-stderr': Failed to execute child process "dbus-launch" (No such file or directory)
```

### CODE REVIEW

**Comment by willysr** [comment]
@isaackwy can you check on this PR on winetricks?

**Comment by willysr** [comment]
as of protonup, can you contact the maintainer first?
we basically do not allow non-maintainer to update without confirmation from the original maintainer.

**Comment by isaackwy** [comment]
Hi Martin (noisecode3), Hi Willy.

1. I am not updating winetricks.
When I verify the signature of the latest winetricks tarball (20230212), I receive a bad signature. Output below:
```
gpg --verify 20230212.tar.gz.asc
gpg: assuming signed data in `20230212.tar.gz'
gpg: Signature made Sun 12 Feb 2023 01:42:12 AM PST using RSA key ID 053F0749
gpg: BAD signature from "Austin English <austinenglish@gmail.com>"
```
2. I was able to build and install protontricks on my system (using 1.9.0, the version at SlackBuilds.org).
However, upon running protontricks, I received a different error (see step 3 below).
3. protontricks said that my system was unable to find the package vdf. Either you (Martin) or Damian Perticone (maintainer of protontricks) need to upload python3-vdf to SlackBuilds.org.
(Truncated output below):
``` 
File "/usr/lib64/python3.9/site-packages/protontricks/steam.py", line 9, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
```

**Comment by willysr** [comment]
@isaackwy see this issue: https://github.com/Winetricks/winetricks/issues/2024

**Comment by isaackwy** [comment]
Thanks Willy. It's up to the upstream author (austin987) to release a new version of winetricks that signs correctly.
Github now "generate[s] tarballs on demand without storing them permenantly" - jre-wine suggested using an external zip command to create a local tarball identical to github's generated one.

I'll wait a few days for that next version.

**Pull request closed without merging**
