### PR TITLE
Fix + few updates

### PR DESCRIPTION
**Pull request by RSKYS**

### CODE REVIEW

**Comment by RSKYS** [comment]
Hi Willy,
I'm sorry but I need to discuss something with you.
In next release of Tauon Music Box, I want to [add this](https://github.com/RSKYS/SBo-git/tree/current/system/pipewire-pulse) as dependency as well.
The reason I was holding back, was because Tauon was holding audio 16bit back, Now with support of 24bit, using pulseaudio is meaningless
And I'm at development of Tauon myself, would it be possible I add it?

Regards,
Pouria

**Review by willysr — COMMENTED** [review]
The name of this script is python3-tekore, not tekore

**Comment by willysr** [comment]
same goes with python3-plexapi

**Comment by RSKYS** [comment]
Ah I knew it'd become problem
Let me send a fix

**Comment by RSKYS** [comment]
Done.
Can you tell me your opinion [about this?](https://github.com/SlackBuildsOrg/slackbuilds/pull/1058#issuecomment-974807368)

**Comment by willysr** [comment]
it's still listed as python-tekore, instead of python3-tekore

**Comment by RSKYS** [comment]
> it's still listed as python-tekore, instead of python3-tekore

Is it really need to be "python3"?
Because It's mentioning it's python
Maybe python insist on "python2" in Slackware?

**Comment by RSKYS** [comment]
Alright I'll change it..

**Comment by RSKYS** [comment]
There we go

**Comment by willysr** [comment]
we want to make it consistent with the script name, so it should be staying at python3-xx
as for the other script, i have no comment at this point. As long as it works and don't interrupt Slackware's way of handling audio, it should be fine.

**Comment by RSKYS** [comment]
I just submit it when the release comes,
And yeah I was doing it on purpose but they're both python3-xx now

**Comment by RSKYS** [comment]
I just submit it when the release comes,
And yeah I was doing it on purpose but they're both python3-xx now
As well you asked
Please merge.

**Comment by RSKYS** [comment]
> we want to make it consistent with the script name, so it should be staying at python3-xx
as for the other script, i have no comment at this point. As long as it works and don't interrupt Slackware's way of handling audio, it should be fine.

I just submit it when release comes, we will discuss it then!

**Comment by RSKYS** [comment]
> as for the other script, i have no comment at this point. As long as it works and don't interrupt Slackware's way of handling audio, it should be fine.

I just submit it when release comes, we will discuss it then!

**Comment by RSKYS** [comment]
> we want to make it consistent with the script name, so it should be staying at python3-xx

Yeah I was doing it on purpose but they're both python3-xx now
As well you asked
Please merge.

**Pull request closed without merging**
