### PR TITLE
python/python3-keyring: Update for 25.1.0

### PR DESCRIPTION
**Pull request by isaackwy**
1. Include fourtysixandtwo's new "export PYTHONPATH" command
2. Add commenting (for describing the necessity of "export PYTHONPATH")

### CODE REVIEW

**Comment by willysr** [comment]
this has been partially patched by @fourtysixand2 in this commit
https://git.slackbuilds.org/slackbuilds/commit/?id=952a2aa6d
can you push the version update only? otherwise it will be conflict when i merge it later

**Comment by isaackwy** [comment]
I rebased accordingly (there are now no edits to "export PYTHONPATH").
Should I remove the additional comment as well?

**Comment by willysr** [comment]
yes please
or if you want safer option, cherry-pick his commit and then push your update
this way, your changes is based on his latest commit

**Comment by willysr** [comment]
@sbo-bot: build python/python3-keyring

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
