### PR TITLE
system/rasdaemon: Updated for version 0.8.2

### PR DESCRIPTION
**Pull request by perrin4869**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/rasdaemon

**Comment by willysr** [comment]
@perrin4869 this failed to build, you may no longer need the patch

**Comment by perrin4869** [comment]
right, sorry about that! I thought maybe it is still required in slackware 15, but should have checked first.. let's try again

**Comment by willysr** [comment]
@sbo-bot: build system/rasdaemon

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
