### PR TITLE
python/python3-pytest: Version bump to 8.3.1

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pytest

**Comment by aclemons** [comment]
@sbo-bot: build academic/rpy2

**Comment by aclemons** [comment]
@sbo-bot: build python/i3ipc

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-cinemagoer

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-openstep-plist

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-pytest-cov

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-pytest-runner

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-userpath

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
