### PR TITLE
system/docker-compose: Updated for version 2.22.0

### PR DESCRIPTION
**Pull request by earies**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 system/docker-compose

**Comment by aclemons** [comment]
Let me check on the error details here later to see if it is your error or a problem with my build env.

**Comment by aclemons** [comment]
```
[...]
go: downloading github.com/go-openapi/jsonpointer v0.19.5
# github.com/docker/compose/v2/pkg/compose
pkg/compose/up.go:64:23: undefined: sync.OnceFunc
note: module requires Go 1.21
make: *** [Makefile:57: build] Error 1
system/docker-compose: docker-compose.SlackBuild failed (status 2)      09:25:50
Unmounting chroot ...
:-( system/docker-compose FAILED )-:
```

Looks like this needs go 1.21, so is blocked until google-go-lang in the repo is upgraded:

https://github.com/docker/compose/blob/v2.22.0/go.mod#L3

**Comment by willysr** [comment]
i accidentally took this PR and push it into master :(

**Pull request closed without merging**
