### PR TITLE
Please update jupyter-nbformat, jupyter-client and jupyterlab

### PR DESCRIPTION
**Pull request by isaackwy**

### CODE REVIEW

**Comment by aclemons** [comment]
I've staged these to my branch, thanks. While testing, I noticed that jupyterlab_server writes outside of DESTDIR. Could you check this and open a PR to rectify?

```
/usr/lib64/python3.9/site-packages/gi
/usr/lib64/python3.9/site-packages/gi/__pycache__
/usr/lib64/python3.9/site-packages/gi/overrides/__pycache__
/usr/lib64/python3.9/site-packages/gi/repository
/usr/lib64/python3.9/site-packages/gi/repository/__pycache__
```

These files were changed on the host system building the package.

**Comment by isaackwy** [comment]
What you just showed me were directories.
Which files specifically had changed on your host system?
(Maybe please attach a log file).

I'll check more carefully on this issue in 1 or 2 days.

**Comment by aclemons** [comment]
Sure, I have a clean VM where I built your package. I first installed all the dependencies, and then for example, if I checked the directories /usr/lib64/python3.9/site-packages/gi/overrides/ and /usr/lib64/python3.9/site-packages/gi/overrides/__pycache__/ before I build `jupyterlab_server`. Then I built the package and checked those directories again:

```diff
 diff -u before after
--- before      2022-05-04 11:42:30.620292550 +1200
+++ after       2022-05-04 11:42:39.530217847 +1200
@@ -1,7 +1,7 @@
 root@05f10867565c:/tmp/jupyterlab_server# ls -la /usr/lib64/python3.9/site-packages/gi/overrides/
 total 256
 drwxr-xr-x 3 root root   253 Nov  3 00:44 ./
-drwxr-xr-x 4 root root  4096 Nov  3 00:44 ../
+drwxr-xr-x 5 root root  4096 May  3 23:42 ../
 -rw-r--r-- 1 root root 47444 Nov  3 00:55 BlockDev.py
 -rw-r--r-- 1 root root  3563 Sep 18  2021 GExiv2.py
 -rw-r--r-- 1 root root  2242 Aug 25  2019 GIMarshallingTests.py
@@ -14,11 +14,15 @@
 -rw-r--r-- 1 root root  8427 Nov 18 18:00 IBus.py
 -rw-r--r-- 1 root root  1774 May  2  2020 Pango.py
 -rw-r--r-- 1 root root 12819 Mar 19  2021 __init__.py
-drwxr-xr-x 2 root root    66 Nov 18 18:00 __pycache__/
+drwxr-xr-x 2 root root   180 May  3 23:42 __pycache__/
 -rw-r--r-- 1 root root  1705 Aug 25  2019 keysyms.py
 root@05f10867565c:/tmp/jupyterlab_server# ls -la /usr/lib64/python3.9/site-packages/gi/overrides/__pycache__/
-total 16
-drwxr-xr-x 2 root root   66 Nov 18 18:00 ./
-drwxr-xr-x 3 root root  253 Nov  3 00:44 ../
--rw-r--r-- 1 root root 5910 Nov 18 18:00 IBus.cpython-39.opt-1.pyc
--rw-r--r-- 1 root root 5910 Nov 18 18:00 IBus.cpython-39.pyc
+total 88
+drwxr-xr-x 2 root root   180 May  3 23:42 ./
+drwxr-xr-x 3 root root   253 Nov  3 00:44 ../
+-rw-r--r-- 1 root root 22683 May  3 23:42 GLib.cpython-39.pyc
+-rw-r--r-- 1 root root 17189 May  3 23:42 GObject.cpython-39.pyc
+-rw-r--r-- 1 root root 15979 May  3 23:42 Gio.cpython-39.pyc
+-rw-r--r-- 1 root root  5910 Nov 18 18:00 IBus.cpython-39.opt-1.pyc
+-rw-r--r-- 1 root root  5910 Nov 18 18:00 IBus.cpython-39.pyc
+-rw-r--r-- 1 root root 10668 May  3 23:42 __init__.cpython-39.pyc
```

They are just cache files, and it is perhaps unavoidable that they get created, but I thought I would mention them. I build with an overlayfs and report if any files outside of TMP are changed.

**Comment by aclemons** [comment]
If they are unavoidable, I will filter them out of my report.

**Comment by isaackwy** [comment]
I uninstalled and reinstalled jupyterlab_server... the changes are not happening on my computer.

**Comment by aclemons** [comment]
Ok, I think it probably just means that the cache files were already there for you, so the actual build did not create them again. I think we can ignore this. I will filter these types of files out of my report. Thanks for checking

**Pull request closed without merging**
