### PR TITLE
libraries/re2: Update for 2023_11_01 (+new maintainer)

### PR DESCRIPTION
**Pull request by isaackwy**
I don't think Larry Hajali is maintaining SlackBuilds anymore. I don't mind if maintenance is returned to him, though (for context, I already took over spyder).

re2 is a build dependency for python3-grpcio (which in return is a dependency of opensnitch).
I plan on uploading opensnitch within a few weeks.

I tried compiling mtxclient and running nheko with the updated re2 - I have not faced any issues or problems.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build libraries/re2

**Comment by willysr** [comment]
@isaackwy i think this need new dep?

**Comment by isaackwy** [comment]
> @isaackwy i think this need new dep?

The "new dep" in question is abseil-cpp.

Truncated output (if building without abseil-cpp).
```
Perhaps you should add the directory containing `absl_synchronization.pc'
to the PKG_CONFIG_PATH environment variable
No package 'absl_synchronization' found
g++ -c -o obj/re2/bitmap256.o  -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I.   -DRE2_USE_ICU  -DUSEPCRE -O2 -fPIC -DNDEBUG re2/bitmap256.cc
In file included from ./re2/bitmap256.h:14,
                 from re2/bitmap256.cc:5:
./util/logging.h:16:10: fatal error: absl/base/attributes.h: No such file or directory
   16 | #include "absl/base/attributes.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:205: obj/re2/bitmap256.o] Error 1
```

abseil-cpp will be added to SlackBuilds.org in next week's cycle.
I will rebase this PR shortly (and add abseil-cpp as a new dependency).

**Comment by willysr** [comment]
@sbo-bot: build libraries/re2

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
