### PR TITLE
libraries/webkit2gtk4.1: Updated for version 2.46.0.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/webkit2gtk4.1

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/webkit2gtk4.1

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/gambas3

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/wxPython4

**Comment by willysr** [comment]
@sbo-bot: build x86_64 network/epiphany

**Comment by willysr** [comment]
@sbo-bot: build x86_64 network/luakit

**Comment by willysr** [comment]
@sbo-bot: build x86_64 network/vimb

**Comment by willysr** [comment]
@aclemons do you use vimb?
this script failed to build against latest webkit2gtk and maintainer is MIA and we are the last 2 committers on this

**Comment by aclemons** [comment]
Sorry, I don't use it. I think I was just fixing a build break when I touched it in 22eacdd1b007ea391f80c17f8e15ba69bcaeeb6e

**Pull request closed without merging**
