### PR TITLE
python/python3-platformdirs: Version bump to 4.3.6

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-platformdirs

**Comment by bassmadrigal** [comment]
@sbo-bot: build development/jupyter_core

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-black

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pipx

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pooch

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pylint

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-requests-cache

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-virtualenv

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/subliminal

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
