### PR TITLE
python/constantly: removed (use python3-constantly)

### PR DESCRIPTION
**Pull request by Ythogtha**
Do not merge before having validated and added python3-constantly, from the submit page.

### CODE REVIEW

**Review by aclemons — APPROVED** [review]
confirmed, no references to `constantly` in REQUIRES anywhere

**Comment by willysr** [comment]
@Ythogtha it's probably better to put removed so i can notice it during public update to remove it from database

**Comment by Ythogtha** [comment]
Ok like that ?

**Comment by willysr** [comment]
i hope it's under 72 character or urchlay will complain later lol

**Comment by willysr** [comment]
merged as @aclemons already merged python3-constantly

**Pull request closed without merging**
