### PR TITLE
Version Bump python3-pdm-backend to 2.2.1 & python3-pdm to 2.15.0

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot build python/python3-pdm-backend

**Comment by bassmadrigal** [comment]
@sbo-bot build python/python3-pdm

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm-backend

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
