### PR TITLE
gis/gdal: Updated for version 3.8.5.

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build gis/gdal

**Comment by ArTourter** [comment]
hmm I am confused, I didn't add libheif as a dependency. It compiles fine without it, although it is an optional dependency. Where did libheif come from?

**Comment by aclemons** [comment]
> Where did libheif come from?

The bot is usually configured to build with all optional dependencies, if they are already known. Sometimes needs manual adjusting when they change since it is not automated.

For the build failure, let me pull in the fix for x265 on this branch. willy already fixed it on his.

**Comment by aclemons** [comment]
@sbo-bot: build gis/gdal

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
