### PR TITLE
development/arduino-cli: Added (tool to manage arduino).

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/arduino-cli

**Comment by willysr** [comment]
@earies : can you fix this issues?

**Comment by earies** [comment]
> @earies : can you fix this issues?

Since this is initial import - can you apply the patch from here:

https://github.com/earies/slackbuilds/commit/8690960fcf30e9f5e1624d43a12ea8c8cdfe6dc9.patch

**Comment by willysr** [comment]
i don't think that is the correct fix

the main issue is this
Running test: 05-basic-sanity...
--- package root dir contains non-directory: LICENSE.txt
--- package root dir contains non-directory: arduino-cli
FAILED

**Comment by earies** [comment]
> i don't think that is the correct fix
> 
> the main issue is this Running test: 05-basic-sanity... --- package root dir contains non-directory: LICENSE.txt --- package root dir contains non-directory: arduino-cli FAILED

I validated the above (see below) - the following line resolves the issue you mention

https://github.com/earies/slackbuilds/commit/8690960fcf30e9f5e1624d43a12ea8c8cdfe6dc9#diff-ce08ff0eddb992225437f0c2be771a40e742d4a5b24358dc0eb963a70e3ccc7fR62

Latest sources are here:

https://github.com/earies/slackbuilds/tree/master/development/arduino-cli

```
$ cat /var/log/packages/arduino-cli-0.34.2-x86_64-1_SBo 
PACKAGE NAME:     arduino-cli-0.34.2-x86_64-1_SBo
COMPRESSED PACKAGE SIZE:     14M
UNCOMPRESSED PACKAGE SIZE:     28M
PACKAGE LOCATION: arduino-cli-0.34.2-x86_64-1_SBo.tgz
PACKAGE DESCRIPTION:
arduino-cli: arduino-cli
arduino-cli:
arduino-cli: Arduino CLI is an all-in-one solution that provides Boards/Library
arduino-cli: Managers, sketch builder, board detection, uploader, and many other
arduino-cli: tools needed to use any Arduino compatible board and platform from
arduino-cli: command line or machine interfaces.
arduino-cli:
arduino-cli:
arduino-cli: Homepage: https://github.com/arduino/arduino-cli
arduino-cli:
arduino-cli:
FILE LIST:
./
install/
install/slack-desc
usr/
usr/bin/
usr/bin/arduino-cli
usr/doc/
usr/doc/arduino-cli-0.34.2/
usr/doc/arduino-cli-0.34.2/LICENSE.txt
usr/doc/arduino-cli-0.34.2/arduino-cli.SlackBuild
```

**Comment by willysr** [comment]
for git repository, the permission should be 644 not 755

**Comment by earies** [comment]
> for git repository, the permission should be 644 not 755

This was already addressed in the repo above - will just resubmit through slackbuilds.org upload as the initial process is not accommodating for any changes post submission.  Is there no way to just use git PRs for initial submission vs. the tgz upload?

**Comment by willysr** [comment]
I'm afraid it's not possible since the database is populated during submission was made via form and not from git. That's why we only accept PR for updates, assuming the script has been accepted before.

The only possible situation is where we are at development stage before next stable repository is still being developed. At that time, we can put anything via git and it will be initially populated during first public announcement for next repo

**Pull request closed without merging**
