### PR TITLE
graphics/graphviz: updated for version 12.0.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
@sbo-bot: build graphics/graphviz

**Comment by willysr** [comment]
There are a lot of BREAKING part mentioned in their Changelog
https://gitlab.com/graphviz/graphviz/-/blob/main/CHANGELOG.md

**Comment by Ythogtha** [comment]
@willysr There are no more major releases for Graphviz, they decided for a versioning in Firefox's style, with updating often the major version number.
So it's hard to know when things might break.

I'm sorry for not having looked enough into it, I wont be able to work on the PR for 10 days, but I'll get back to it.

**Comment by willysr** [comment]
You just need to run the build command for every reverse dependencies for graphviz

**Comment by Ythogtha** [comment]
In a week 😉

**Comment by willysr** [comment]
@sbo-bot: build development/egypt

**Comment by willysr** [comment]
@sbo-bot: build graphics/pencil2d

**Comment by willysr** [comment]
@sbo-bot: build graphics/pygraphviz

**Comment by willysr** [comment]
@sbo-bot: build graphics/xdot

**Comment by willysr** [comment]
@sbo-bot: build libraries/libjxl

**Comment by willysr** [comment]
@sbo-bot: build libraries/libyang

**Comment by willysr** [comment]
@sbo-bot: build libraries/log4c

**Comment by willysr** [comment]
@sbo-bot: build libraries/properties-cpp

**Comment by willysr** [comment]
@sbo-bot: build libraries/uriparser

**Comment by willysr** [comment]
@sbo-bot: build libraries/waylandpp

**Comment by willysr** [comment]
@sbo-bot: build multimedia/ffmpegfs

**Comment by willysr** [comment]
@sbo-bot: build multimedia/olive

**Comment by willysr** [comment]
@sbo-bot: build network/w3af

**Comment by willysr** [comment]
@sbo-bot: build office/xournalpp

**Comment by willysr** [comment]
@sbo-bot: build python/pydot

**Comment by willysr** [comment]
@sbo-bot: build system/nagvis

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by willysr** [comment]
@sbo-bot: build system/ntopng

**Comment by willysr** [comment]
merged

**Comment by Ythogtha** [comment]
@willysr oh, ok, that's a way to do it !
I'll think of it in the future, I could even do it from the phone, thanks.

**Comment by RSKYS** [comment]
@willysr @Ythogtha I assume it wouldn't be safe if graphviz get updated to 12.1.2, right?

**Pull request closed without merging**
