### PR TITLE
Presence fix

### PR DESCRIPTION
**Pull request by RSKYS**
Found conflict you were talking about.
It should only affect .info now.

Has natsort v8.0.0 merged too?

### CODE REVIEW

**Comment by willysr** [comment]
i removed the commit from my branch already, so this PR is no longer needed

**Comment by RSKYS** [comment]
Have you changed it to "streamline music player" and other about and slak-desc changes?

**Comment by RSKYS** [comment]
I believe if you remove that commit, those will disappear to

**Comment by RSKYS** [comment]
Oh or maybe not, thanks

**Comment by RSKYS** [comment]
Can you provide me branch with latest commit of tauonmb from git.slackbuilds.org?

Best regards, Pouria.

**Comment by willysr** [comment]
it's on master

**Comment by RSKYS** [comment]
I'm going to clone it locally, website doesn't show changes,
I can't find it atleast.

**Comment by RSKYS** [comment]
Hi Willy,
I'm sure you haven't merged it, I just cloned it locally
The PR is one before even Presence removal;

Please [check this.](https://github.com/SlackBuildsOrg/slackbuilds/pull/1015/files)
This should be the build on master
you haven't added change I made for locale
This commit was the one even before Presence removal

Regards,
Pouria

**Pull request closed without merging**
