### PR TITLE
office/navi: Update for version 2.23.0

### PR DESCRIPTION
**Pull request by Tonus1**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build office/navi

**Comment by willysr** [comment]
@Tonus1 please follow the URL pattern from previous revision.

**Comment by Tonus1** [comment]
I thought my amend commit would first get to my repo. Actually testing the build in my VM. Will tell when finished.

**Comment by Tonus1** [comment]
Builded fine.

**Comment by willysr** [comment]
@sbo-bot: build office/navi

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
