### PR TITLE
development/textadept: updated for version 12.2

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
Should I allow it to download during build now @Ythogtha ?

# Build snip

<details>

```sh
-- Using src='https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip'
CMake Error at singleapp-subbuild/singleapp-populate-prefix/src/singleapp-populate-stamp/download-singleapp-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  Closing connection



          --- LOG END ---
          error: downloading 'https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  Closing connection



          --- LOG END ---
          error: downloading 'https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  Closing connection



          --- LOG END ---
          error: downloading 'https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  Closing connection



          --- LOG END ---
          error: downloading 'https://github.com/itay-grudev/SingleApplication/archive/refs/tags/v3.4.0.zip' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

  Closing connection
```

</details>

**Comment by Ythogtha** [comment]
> Should I allow it to download during build now @Ythogtha ?

Nope, the file should be there, it's in the textadept.info file, maybe it's looking for some different name, I'll look into it.

**Comment by Ythogtha** [comment]
Ok, that one's a pain.
The build find the local file, then don't use it and builds using the file elsewhere.
If I create a link there also, it finds the file, but removes and re-download it because it cannot check the hash.
Which is something that's not done for other packages.
I don't know what to do here, it is dark cmake magic on a high level, and I'm not padawan enough there...
I guess let's allow network, and hope they'll better their build for next version.
I may even open a ticket uostream about this issue, for offline build.

**Comment by aclemons** [comment]
Ok no problem. I will adjust the hints to allow network access for this one. Thanks

**Comment by aclemons** [comment]
@sbo-bot: build development/textadept

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
