### PR TITLE
system/mpollux-digisign-client: Updated for version 4.2.6.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by pyllyukko** [comment]
Linter complains, but there are different versions for `x86` and `x86_64`. We could also do it as:

```
VERSION=${VERSION:-4.2.6b_8414}

...

if [ "${ARCH}" = "i586" ]
then
  VERSION=4.2.6_8401
fi
```

So it would "default" to `x86_64`.

But that's not optimal either.

**Comment by willysr** [comment]
that's strange to release similar name with just 1 character difference

**Comment by willysr** [comment]
> Linter complains, but there are different versions for `x86` and `x86_64`. We could also do it as:
> 
> ```
> VERSION=${VERSION:-4.2.6b_8414}
> 
> ...
> 
> if [ "${ARCH}" = "i586" ]
> then
>   VERSION=4.2.6_8401
> fi
> ```
> 
> So it would "default" to `x86_64`.
> 
> But that's not optimal either.

this is better solution i guess, we can assume the default is people are using x86_64

**Comment by willysr** [comment]
can the VERSION in .info be adjusted so that it has same value with VERSION in x86_64 arch?

**Comment by aclemons** [comment]
Does upstream every release multiple versions with the same triplet but different suffix? If not, maybe the version of the slackware package can just be the same for both architectures, but the script uses the source version for each arch to extract?

**Comment by willysr** [comment]
since no revision since 2 weeks ago, i'll close this one

**Pull request closed without merging**
