### PR TITLE
sbotools: maintainer and fork change; update

### PR DESCRIPTION
**Pull request by pghvlaans**
As discussed on the mailing list. The `sbotools3` repo and page will remain up until after the public update.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/sbotools

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
@pghvlaans 
i think you need to update the README

> sbotools is incompatible with sbotools3 (briefly on SlackBuilds.org).
> Removing sbotools3 before installing sbotools is advised.

this will be incorrect as sbotools3 will be removed in this public update

**Comment by pghvlaans** [comment]
I added that bit for anyone who installed sbotools3 in the last few weeks, but the latest commit makes it clearer that it isn't there anymore. I'll delete the paragraph altogether next time sbotools is updated.

**Pull request closed without merging**
