### PR TITLE
development/jupyter_packaging: Update for 0.12.3

### PR DESCRIPTION
**Pull request by isaackwy**
pyproject.toml claims to require setuptools >= 60.2.0:
```
dependencies = [
    "packaging",
    "tomlkit",
    "setuptools>=60.2.0",
    "wheel",
    "deprecation",
]
```

However, this is because jupyter_packaging 0.12.0 has updated the StaticModule import. That is, jupyter_packaging/setupbase.py has changed from:
```
from setuptools.config import StaticModule
```

To:
```
try:
    from setuptools.config import StaticModule
except ImportError:
    # setuptools>=61.0.0
    from setuptools.config.expand import StaticModule
```

Therefore, jupyter_packaging can build and run with setuptools 57.5.0 (the version provided by Slackware 15.0).
See https://github.com/jupyter/jupyter-packaging/pull/131 for more details.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/jupyter_packaging

**Comment by willysr** [comment]
@isaackwy this failed

**Comment by isaackwy** [comment]
Hi Willy. I added python3-hatchling as another dependency.
Please try again.

**Comment by willysr** [comment]
@sbo-bot: build development/jupyter_packaging

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
