### PR TITLE
graphics/blender: Version bump to 4.2.2

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/blender

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/blender

**Comment by bassmadrigal** [comment]
@sbo-bot: build x86_64 graphics/blender

**Comment by bassmadrigal** [comment]
@sbo-bot: build x86_64 graphics/yafaray-blender

**Comment by bassmadrigal** [comment]
Let's try this again...

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
