### PR TITLE
New maintainer for several packages

### PR DESCRIPTION
**Pull request by nick8325**
I'm taking over a few packages (see mailing list). I also took the chance to update to the latest autotools-template and version bump xfce4-volumed-pulse. Let me know if you prefer to see this split up into multiple pull requests.

desktop/xfce4-volumed-pulse: New maintainer, version bump.
desktop/xfce4-cpufreq-plugin: New maintainer.
desktop/murrine-themes: New maintainer.
desktop/xfwm4-themes: New maintainer.
desktop/gtk-xfce-engine: New maintainer.

### CODE REVIEW

**Comment by willysr** [comment]
please use 1 commit per changes per script
thanks

**Comment by nick8325** [comment]
Split up into one commit per package now.

**Comment by nick8325** [comment]
Oops sorry, may have misread your message, would you like them split up further into e.g. one commit for "New maintainer", one commit for version bump, etc?

**Comment by aclemons** [comment]
This is fine. Just one commit per package, i.e. don't touch two scripts in one commit.

**Comment by aclemons** [comment]
@sbo-bot: build desktop/xfce4-cpufreq-plugin

**Comment by aclemons** [comment]
@sbo-bot: build desktop/gtk-xfce-engine

**Comment by aclemons** [comment]
@sbo-bot: build desktop/xfce4-volumed-pulse

**Comment by aclemons** [comment]
@sbo-bot: build desktop/murrine-themes

**Comment by aclemons** [comment]
@sbo-bot: build desktop/xfwm4-themes

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
