### PR TITLE
July updates + Taking over maintainership of spotify dependencies / sub-dependencies

### PR DESCRIPTION
**Pull request by RezaT4795**
Note: I've already contacted and taken the maintainership of `spotify` from [Edinaldo P. Silva](mailto:edps.mundognu@gmail.com) long time ago. He also sent me another email later and asked me to maintain `spotify`'s dependencies and sub-dependencies which are:
`libayatana-appindicator`, `libayatana-indicator`, `ayatana-ido` and `libcurl-gnutls`.

- libraries/libcurl-gnutls: Updated for version 8.9.0.
- libraries/libcurl-gnutls: Taking over maintainership.
- libraries/ayatana-ido: Updated for version 0.10.3.
- libraries/ayatana-ido: Taking over maintainership.
- libraries/libayatana-indicator: Taking over maintainership.
- libraries/libayatana-appindicator: Taking over maintainership.
- development/dotnet-sdk-8.0: Updated for version 8.0.303.
- development/dotnet-runtime-8.0: Updated for version 8.0.7.
- development/aspnetcore-runtime-8.0: Updated for version 8.0.7.
- development/dotnet-sdk-7.0: Updated for version 7.0.410.
- development/dotnet-runtime-7.0: Updated for version 7.0.20.
- development/aspnetcore-runtime-7.0: Updated for version 7.0.20.
- development/dotnet-sdk-6.0: Updated for version 6.0.424.
- development/dotnet-runtime-6.0: Updated for version 6.0.32.
- libraries/aspnetcore-runtime-6.0: Updated for version 6.0.32.
- network/windscribe: Updated for version 2.10.15.
- system/powershell: Updated for version 7.4.4.
- network/nordvpn: Updated for version 3.18.3.
- network/anydesk: Updated for version 6.3.2.
- system/android-udev-rules: Updated for version 2024.06.25.
- multimedia/spotify: Updated for version 1.2.42.290.

### CODE REVIEW

**Comment by willysr** [comment]
@RezaT4795 can you make 1 commit per PR or group-related commits and move the rest to another PR?
it's hard to run checks when there are a lot of unrelated commits in 1 PR

**Comment by RezaT4795** [comment]
> @RezaT4795 can you make 1 commit per PR or group-related commits and move the rest to another PR?
> 
> it's hard to run checks when there are a lot of unrelated commits in 1 PR
> 
> 

Sure thing, I will make category-based PRs tomorrow.
But all commits are version updates. I don't know what you mean by unrelated commits.

**Comment by RezaT4795** [comment]
@willysr btw, I also submitted a new package named 'rider' via submission form in the website. Now it's not in the pending queue, and not in the ready queue either. What happened?

**Comment by willysr** [comment]
> > @RezaT4795 can you make 1 commit per PR or group-related commits and move the rest to another PR?
> > 
> > it's hard to run checks when there are a lot of unrelated commits in 1 PR
> > 
> > 
> 
> Sure thing, I will make category-based PRs tomorrow.
> But all commits are version updates. I don't know what you mean by unrelated commits. 

Unrelated means it's not depending one to another

**Comment by willysr** [comment]
> @willysr btw, I also submitted a new package named 'rider' via submission form in the website. Now it's not in the pending queue, and not in the ready queue either. What happened?

It's pushed as a new PR so we can check it using github CI

**Comment by willysr** [comment]
#7265

**Pull request closed without merging**
