### PR TITLE
academic/sage: Updated for version 10.0

### PR DESCRIPTION
**Pull request by cduston44**
Still trying to make this work...rebased my master with upstream. Shows only commit difference is this one, hope it works....

### CODE REVIEW

**Comment by willysr** [comment]
can you fix the commit to use academic/sage: Updated for version 10.0 ?

**Comment by cduston44** [comment]
> can you fix the commit to use academic/sage: Updated for version 10.0 ?

I changed the title, if that's what you're after.

**Comment by willysr** [comment]
the commit message, not the title :)

**Comment by cduston44** [comment]
Ok, it says that now!

**Comment by willysr** [comment]
@aclemons can you review this PR?

**Comment by aclemons** [comment]
Ok, this took me a couple of tries, but I built it on both i586 and x86_64.

I did not notice that the files in the package don't all have the correct owner and group. Some are root:root but others are 1000:1000 and still others are 501:games. This is not an issue with this change. The version of the script in the repo also produces a package like this. Could you look into updating this for the next time you submit an update?

This change is now staged on my branch.

**Comment by cduston44** [comment]
I will make a note of that, and try my best to understand why and change it if possible.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Pull request closed without merging**
