### PR TITLE
perl/perl-Module-Install: Updated for version 1.21

### PR DESCRIPTION
**Pull request by mab974**
not sure 'make test' is necessary 
for all users or just for maintainer ?

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Module-Install

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Audio-FLAC-Header

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Class-ReturnValue

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Curses-UI

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Encode-HanExtra

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Gtk2-Notify

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Locale-Msgfmt

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-MIME-tools

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-MP3-Info

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Module-Manifest

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Syntax-Highlight-Engine-Kate

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Task-Weaken

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Test-Script

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Test-utf8

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Text-Password-Pronounceable

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-WWW-Curl

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-XML-SAX-Writer

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-ZMQ-Constants

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-crypt-dh-gmp

**Comment by willysr** [comment]
@mab974 this caused 4 scripts to fail
perl/perl-Locale-Msgfmt
perl/perl-Module-Manifest
perl/perl-Test-Script
perl/perl-WWW-Curl

can you update those 4 scripts as well on this PR?

**Comment by willysr** [comment]
perl-Locale-Msgfmt didn't fail before this update
See https://github.com/SlackBuildsOrg/slackbuilds/issues/5827#issuecomment-2081529509

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-WWW-Curl

**Comment by willysr** [comment]
ok, 1 down, three left 
perl/perl-Locale-Msgfmt
perl/perl-Module-Manifest
perl/perl-Test-Script

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Module-Manifest

**Comment by mab974** [comment]
3 same error s
can't locate inc/Module/Install/DSL.pm

from changelog of Module::Install: 
1.21  2023-04-28
  - fix tests broken by Module::Install::DSL removal

1.20  2023-04-27
  - Module::Install::DSL has been removed, as its use is highly discouraged.

**Comment by willysr** [comment]
problem is that other scripts are not updated so they keep using this module, so i removed them instead

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
