### PR TITLE
Mab974 - Update raku and zef

### PR DESCRIPTION
**Pull request by mab974**
MoarVM, nqp and rakudo updated for 2023.10
zef updated for 0.20.0

### CODE REVIEW

**Comment by willysr** [comment]
@mab974
@sbo-bot: build perl/MoarVM
@sbo-bot: build perl/nqp
@sbo-bot: build perl/rakudo
@sbo-bot: build perl/zef

**Comment by willysr** [comment]
@sbo-bot: build perl/MoarVM

**Comment by willysr** [comment]
@sbo-bot: build perl/nqp

**Comment by willysr** [comment]
@sbo-bot: build perl/rakudo

**Comment by willysr** [comment]
@sbo-bot: build perl/zef

**Comment by willysr** [comment]
@mab974 : it seems zef MD5SUM is incorrect and also for nqp, the executables need to be stripped

**Comment by mab974** [comment]
Ok it’s noted. Thanks Willy !

**Pull request closed without merging**
