### PR TITLE
development/SQLAlchemy: Updated for version 2.0.28.

### PR DESCRIPTION
**Pull request by fourtysixand2**
I believe we can upgrade to 2.0.x now.  I'd like to keep this as a WIP for at least a week unless no one has any concerns.

Here's a list of the builds that have issues with the upgrade:

- sickchill
  - have emailed maintainer to remove patch to make it work with SQLAlchemy 1.x
- buildbot
  - seems to run fine, but has warning
    - buildbot 3.11.0 has requirement sqlalchemy<1.5,>=1.3.0, but you have sqlalchemy 2.0.28.
  - have emailed maintainer for further testing

Slackbuilds suggested for removal:
- alembic (python2 only and previously broken)
  - replaced by python3-alembic.  
  - maintainer is not active (3 years)
- Pyfa
  - unless someone would like to take it over and upgrade it
  - maintainer is not active (4 years)
- sqlalchemy-migrate
  - Kyle has given ok to remove as it is no longer a dep of pytrainer
  - no updates to project since 2019.
- gourmet (python2)
  - believe it is broken, SQLAlchemy's python2 support was removed before I took it over
  - maintainer is not active (9 years)

Here is the remaining list of builds that have SQLAlchemy as a dep.  Basic testing shows no issues:

- flexget
- python3-cinemagoer
- zope.sqlalchemy
- python3-paginate_sqlalchemy
- python3-obspy
- slpkg
- python3-Flask-SQLAlchemy
- pytrainer
- python3-alembic
- python3-mailman
- Kallithea
- kallithea-frontend
- buildbot-badges
- pychess
- python3-ipython-sql

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/SQLAlchemy

**Comment by willysr** [comment]
merged into SQLAlchemy-wip branch

**Comment by Ythogtha** [comment]
> > merged into SQLAlchemy-wip branch
> 
> @Ythogtha found some issues with the upgrade in regards to Kallithea and buildbot. Keep as WIP in the meantime.

@willysr @fourtysixand2 : Everything is fixed for Kallithea, and Buildbot, and this can be merged.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
