### PR TITLE
misc/bitwarden-desktop: Updated for version 2023.10.1.

### PR DESCRIPTION
**Pull request by maravtdm**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build misc/bitwarden-desktop

**Comment by willysr** [comment]
@sbo-bot: build multimedia/haruna

**Comment by willysr** [comment]
i think this PR is not rebased against latest master
haruna was already pushed to master branch last week

**Comment by aclemons** [comment]
@sbo-bot: build misc/bitwarden-desktop

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 network/element-desktop

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
