### PR TITLE
multimedia/HandBrake: Version bump to 1.8.0 and new maintainer

### PR DESCRIPTION
**Pull request by bassmadrigal**
Received permission from Klaatu to take over maintenance and add copyright notice.

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/HandBrake

**Comment by bassmadrigal** [comment]
Well, crap. I didn't realize it didn't build on 32bit. I'll have to try and spin up a VM to see if it can be tweaked to work or if it needs to be made 64bit only.

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/HandBrake

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
