### PR TITLE
network/whalebird: Update for 5.0.2

### PR DESCRIPTION
**Pull request by isaackwy**
Instead of building from source, whalebird now repackages the rpm binary.

This is the error I received from building whalebird 5.0.2 from source:
``` error /var/tmp/pamac-build-eman/whalebird/src/whalebird-desktop-5.0.2/node_modules/better-sqlite3: Command failed. ```

P.S. I may need more dependencies (ex. http-parser, libminizip, re2, snappy). The Arch Linux AUR PKGBUILD provides a reference:
https://aur.archlinux.org/packages/whalebird-bin

### CODE REVIEW

**Comment by aclemons** [comment]
@willysr Should we rather rename this to `whalebird-bin` instead?

**Comment by isaackwy** [comment]
No - I am not maintaining a separate SlackBuild named whalebird (that builds from source) compared with a whalebird-bin (that repackages the binary).

**Comment by aclemons** [comment]
Sorry I was not clear. I meant since this is now going to a binary repackaging going forward, I think we should rename it in the db to `whalebird-bin`. i.e. remove `whalebird` and add `whalebird-bin` to follow the convention.

**Comment by isaackwy** [comment]
Okay... you can rename whalebird to whalebird-bin if you like.
Why this rename specifically though? There are other SlackBuilds that merely repackage binaries, that don't end with "-bin".

**Comment by aclemons** [comment]
That's why I wanted Willy's wisdom and second opinion here. He'll have better idea than I do as to whether we should be gently pushing the convention along.

Currently it's normally either `-bin` as a suffix - or a case differences like `libreoffice` vs `LibreOffice` in the office group. In this case though, my initial thought was since it was changing type after submission, it would be better to change the name so it is really clear to anyone who was using it that it had fundamentally changed. Anyway, let's see what he says.

**Comment by willysr** [comment]
if someone would take charge of building whalebird from source in the future, then renaming with -bin suffix is ideal, but if there's no one will do that, i'd say stick with the same name.

**Comment by isaackwy** [comment]
I won't maintain whalebird (source build) in the future.

**Comment by aclemons** [comment]
```
# buildpkg x86_64 network/whalebird
sbolint: whalebird checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar 31 09:59:43 GMT 2023
revision: 1aa2344e692f70ffcb584dc5b3ea922d04b5dd36
title:    network/whalebird: Updated for version 5.0.2, binary repackaging.

================================================================================
network/whalebird                                                       10:00:47
================================================================================

Calculating dependencies ... 
Hints for network/whalebird:
  PRAGMA="need_net"

Building network/whalebird (update for version 5.0.2) ----------------- 10:00:47
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Pragma: need_net
Running whalebird.SlackBuild ...                                    ETA 10:05:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./whalebird.SlackBuild
Build time 91 sec, peak load 1.67, peak memory 1757M, peak tmp 404M
Built ok:  whalebird-5.0.2-x86_64-1_SBo.txz                             10:02:20
Testing package whalebird-5.0.2-x86_64-1_SBo.txz ... done.
Test installing whalebird-5.0.2-x86_64-1_SBo.txz ...
whalebird-5.0.2-x86_64-1_SBo: Mastondon, Pleroma and Misskey client .... [ 373M]
Unmounting chroot ... done.
Backed up: whalebird-5.0.1-x86_64-2_SBo.txz
:-) network/whalebird Updated for version 5.0.2 (-:

================================================================================
SUMMARY                                                                 10:02:38
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-31_10:00:46.log
Runtime:     0h 1m 52s
Updated:     1
  network/whalebird/whalebird-5.0.2-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/network/whalebird/whalebird-5.0.2-x86_64-1_SBo.txz to /tmp/sbopkglint.1VYHSy ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/network/whalebird/whalebird-5.0.2-x86_64-1_SBo.txz to /tmp/sbopkglint.1VYHSy ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== whalebird-5.0.2-x86_64-1_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
LGTM - staged to my branch

**Pull request closed without merging**
