### PR TITLE
Updates for jsonlines, qpwgraph and certbot cloudflare-related plugin

### PR DESCRIPTION
**Pull request by bolokanar**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build audio/qpwgraph

**Comment by willysr** [comment]
@sbo-bot: build python/python3-jsonlines

**Comment by willysr** [comment]
@sbo-bot: build python/certbot-dns-cloudflare

**Comment by willysr** [comment]
@sbo-bot: build python/python3-cloudflare

**Comment by aclemons** [comment]
@sbo-bot: build i586 audio/qpwgraph

**Comment by aclemons** [comment]
@bolokanar Can you rebase this onto the latest master?

**Pull request closed without merging**
