### PR TITLE
development/google-go-lang: Updated for version 1.22.5.

### PR DESCRIPTION
**Pull request by aclemons**
I'm not the maintainer here, but the admins have been keeping this
package updated since quite a few builds in the repo rely on it:

https://git.slackbuilds.org/slackbuilds/log/development/google-go-lang

These patch releases include quite a few security fixes:

https://go.dev/doc/devel/release#go1.22.minor

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build i586 development/google-go-lang

**Comment by willysr** [comment]
@vbatts is it ok if we update your script?

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 development/google-go-lang

**Comment by willysr** [comment]
need to test all reverse deps?

**Comment by willysr** [comment]
@sbo-bot: build audio/Ymuse

**Comment by willysr** [comment]
@sbo-bot: build desktop/fvwm3

**Comment by willysr** [comment]
@sbo-bot: build desktop/gopsuinfo

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-bar

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-drawer

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-look

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-menu

**Comment by willysr** [comment]
@sbo-bot: build development/actionlint

**Comment by willysr** [comment]
@sbo-bot: build development/golang-googlecode-gonet

**Comment by willysr** [comment]
@sbo-bot: build development/nvidia-container-toolkit

**Comment by willysr** [comment]
@sbo-bot: build development/opentofu

**Comment by willysr** [comment]
@sbo-bot: build development/protoc-gen-go

**Comment by willysr** [comment]
@sbo-bot: build development/terraform

**Comment by willysr** [comment]
@sbo-bot: build misc/cliphist

**Comment by willysr** [comment]
@sbo-bot: build misc/go-md2man

**Comment by willysr** [comment]
@sbo-bot: build network/XD

**Comment by willysr** [comment]
@sbo-bot: build network/aerc

**Comment by willysr** [comment]
@sbo-bot: build network/bombadillo

**Comment by willysr** [comment]
@sbo-bot: build network/cni-plugins

**Comment by willysr** [comment]
@sbo-bot: build network/go-sendxmpp

**Comment by willysr** [comment]
@sbo-bot: build network/goimapnotify

**Comment by willysr** [comment]
@sbo-bot: build network/ssllabs-scan

**Comment by willysr** [comment]
@sbo-bot: build network/tut

**Comment by willysr** [comment]
@sbo-bot: build network/webhook

**Comment by willysr** [comment]
@sbo-bot: build network/zabbix_agent2

**Comment by willysr** [comment]
@sbo-bot: build network/zdns

**Comment by willysr** [comment]
@sbo-bot: build office/msee

**Comment by willysr** [comment]
@sbo-bot: build office/trello-cli

**Comment by willysr** [comment]
@sbo-bot: build system/docker-buildx

**Comment by willysr** [comment]
@sbo-bot: build system/docker-machine

**Comment by willysr** [comment]
@sbo-bot: build system/docker-proxy

**Comment by willysr** [comment]
@sbo-bot: build system/fzf

**Comment by willysr** [comment]
@sbo-bot: build system/go-mtree

**Comment by willysr** [comment]
@sbo-bot: build system/kbfs

**Comment by willysr** [comment]
@sbo-bot: build system/kitty

**Comment by willysr** [comment]
@sbo-bot: build system/lf

**Comment by willysr** [comment]
@sbo-bot: build system/local-persist

**Comment by willysr** [comment]
@sbo-bot: build system/mongo-tools

**Comment by willysr** [comment]
@sbo-bot: build system/netdata

**Comment by willysr** [comment]
@sbo-bot: build system/runc

**Comment by willysr** [comment]
@sbo-bot: build system/sargon

**Comment by willysr** [comment]
@sbo-bot: build system/slack-osquery

**Comment by willysr** [comment]
@sbo-bot: build system/yq

**Comment by willysr** [comment]
@aclemons all looks good with this new golang

**Comment by willysr** [comment]
merged

**Comment by vbatts** [comment]
thanks, @willysr

**Pull request closed without merging**
