### PR TITLE
development/Bear: Fix build.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/Bear

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/Bear

**Comment by kovmir** [comment]
https://github.com/rizsotto/Bear/issues/566

**Comment by willysr** [comment]
this is probably different issue

**Comment by willysr** [comment]
@sbo-bot: build x86_64 build libraries/spdlog

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/spdlog

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/Bear

**Comment by willysr** [comment]
@sbo-bot: build x86_64 desktop/waybar

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/REDasm

**Comment by willysr** [comment]
@sbo-bot: build x86_64 gis/osgEarth

**Comment by willysr** [comment]
@sbo-bot: build x86_64 graphics/mangohud

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/coeurl

**Comment by willysr** [comment]
@sbo-bot: build x86_64 multimedia/kodi

**Comment by willysr** [comment]
@sbo-bot: build x86_64 desktop/waybar

**Comment by willysr** [comment]
@sbo-bot: build x86_64 desktop/waybar

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
