### PR TITLE
system/redis-py: updated for version 5.0.4

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
@Ythogtha I made it so you can build your own PRs (https://github.com/aclemons/sbo-bot/commit/1ab787a7695ce98d67c5758e7576c28efc16090d). Please be respectful of the build box - with great power comes great responsibility. Just make a comment on your PR with `@sbo-bot: build category/package`

**Comment by Ythogtha** [comment]
@sbo-bot: build system/redis-py

**Comment by Ythogtha** [comment]
Thanks @aclemons !
Don't hesitate to tell me if I do something wrong.

**Comment by willysr** [comment]
merged
you are doing great @Ythogtha :)

**Pull request closed without merging**
