### PR TITLE
Marcel/cffsubr

### PR DESCRIPTION
**Pull request by lecramyajiv**
removed  the external folder this will make it to use locally installed afdko
 and also created a symlink to afdko's tx binary for it to work properly

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/python3-cffsubr

**Comment by willysr** [comment]
@sbo-bot: build system/afdko

**Comment by willysr** [comment]
@sbo-bot: build python/python3-cffsubr

**Comment by willysr** [comment]
@sbo-bot: build system/afdko

**Comment by willysr** [comment]
@sbo-bot: build python/python3-cffsubr

**Comment by willysr** [comment]
@aclemons can you take a look on cffsubr?

**Comment by willysr** [comment]
@sbo-bot: build python/python3-cffsubr

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
@lecramyajiv since cffsubr already include adfko, why would all the new deps in adfko also included in cffsubr?

**Comment by lecramyajiv** [comment]
@willysr the included afdko in cffsubr will download and build it  when i submitted the cffsubr 
update it tried to download it and resulted in an error.  
>  why would all the new deps in adfko also included in cffsubr?

I don't think there are any new deps in afdko can you please clarify on that or did you mean about 
python3-fontparts and python3-fontpens

**Comment by willysr** [comment]
yes

**Comment by lecramyajiv** [comment]
right now afdko does not depends on python3-fontparts and python3-fontpens also python3-ufonormalizer  because if you run checkoutlinesufo tool in afdko it will result in error. when I submiited the pr patch for updated dep info I had intimated the maintainer about my submission about this so far I hadn't heard from him since you had rejected it I included it in cffsubr. That is why I mentioned about installing these new deps before installing afdko. Besides fontmake needs it for creating fonts from designspace document. 

P.S: we are making sure cffsubr uses the locally installed version of afdko tool instead of downloading and building it

**Pull request closed without merging**
