### PR TITLE
audio/mixxx: Added new mandatory dependencies.

### PR DESCRIPTION
**Pull request by Ponce**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build audio/mixxx

**Comment by Ponce** [comment]
@sbo-bot: build audio/mixxx

(thanks @aclemons , I'm sorry I'm a bit slow!)

**Comment by aclemons** [comment]
Sorry, the comment needs to be only the build command right now:

https://github.com/aclemons/sbo-bot/blob/6c237e3c76bd610f1fb7d02e06846de8784a2bb9/github/src/index.ts#L61-L63

**Comment by Ponce** [comment]
np, I have a talent for breaking things! :-)

**Comment by Ponce** [comment]
@sbo-bot: build audio/mixxx

**Comment by Ponce** [comment]
@sbo-bot: build audio/mixxx

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
