### PR TITLE
audio/openvino-plugins-ai-audacity: Updated for version 3.6.4.R.3.4.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build x86_64 audio/openvino-plugins-ai-audacity

**Comment by willysr** [comment]
@aclemons can you help build and test this?

**Comment by aclemons** [comment]
> @aclemons can you help build and test this?

Shouldn't Johannes handle this? Looks like it was broken by https://github.com/SlackBuildsOrg/slackbuilds/commit/47f1e03f202699eb4cac80685efe2dc6b41b84cb

**Comment by aclemons** [comment]
I setup a truncated of the build output so it should appear now.

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 audio/openvino-plugins-ai-audacity

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 audio/openvino-plugins-ai-audacity

**Comment by aclemons** [comment]
Hmm, that truncated out anything useful. here is some more:

```sh
 1044 |       wparams.speed_up = params.speed_up;
      |               ^~~~~~~~
make[3]: *** [modules/mod-openvino/CMakeFiles/mod-openvino.dir/build.make:191: modules/mod-openvino/CMakeFiles/mod-openvino.dir/OVWhisperTranscription.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/musicgen_for_conditional_generation.cpp: In constructor ‘ov_musicgen::MusicgenForConditionalGeneration::MusicgenForConditionalGeneration(ov_musicgen::MusicGenConfig&)’:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/musicgen_for_conditional_generation.cpp:87:53: warning: narrowing conversion of ‘(num_encodec_secs * 50)’ from ‘size_t’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
   87 |          model->reshape({ 1, 1, 4, num_encodec_secs * 50 });
      |                                    ~~~~~~~~~~~~~~~~~^~~~
In file included from /tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/musicgen_model_static.cpp:4:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch2.h: In constructor ‘ov_musicgen::MusicgenDecoderModelFullStaticBatch2::MusicgenDecoderModelFullStaticBatch2(ov::Core&, ov_musicgen::MusicGenConfig&)’:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch2.h:64:87: warning: narrowing conversion of ‘(max_tokens + 1)’ from ‘size_t’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
   64 |                port_to_shape[model->input("custom_attention_mask")] = { 1, max_tokens + 1 };
      |                                                                            ~~~~~~~~~~~^~~
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch2.h:74:76: warning: narrowing conversion of ‘max_tokens’ from ‘size_t’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
   74 |                         port_to_shape[model->input(tensorname)] = { 2, 16, max_tokens, 64 };
      |                                                                            ^~~~~~~~~~
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch2.h:181:27: warning: narrowing conversion of ‘(__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type)(&(&(&((ov_musicgen::MusicgenDecoderModelFullStaticBatch2*)this)->ov_musicgen::MusicgenDecoderModelFullStaticBatch2::_past_key_values_ov.std::vector<std::vector<ov::Tensor> >::operator[](0))->std::vector<ov::Tensor>::operator[](2))->ov::Tensor::get_shape())->ov::Shape::operator[](2)’ from ‘__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
  181 |             model->reshape({ {2, _past_key_values_ov[0][2].get_shape()[2], 1024} });
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/musicgen_model_static.cpp:5:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch1.h: In constructor ‘ov_musicgen::MusicgenDecoderModelFullStaticBatch1::MusicgenDecoderModelFullStaticBatch1(ov::Core&, ov_musicgen::MusicGenConfig&)’:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_full_batch1.h:216:27: warning: narrowing conversion of ‘(__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type)(&(&(&((ov_musicgen::MusicgenDecoderModelFullStaticBatch1*)this)->ov_musicgen::MusicgenDecoderModelFullStaticBatch1::_decoder_batch[0].ov_musicgen::MusicgenDecoderModelFullStaticBatch1::DecoderBatchStuff::_past_key_values_ov.std::vector<std::vector<ov::Tensor> >::operator[](0))->std::vector<ov::Tensor>::operator[](2))->ov::Tensor::get_shape())->ov::Shape::operator[](2)’ from ‘__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
  216 |             model->reshape({ {2, _decoder_batch[0]._past_key_values_ov[0][2].get_shape()[2], 1024} });
      |             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/openvino/runtime/include/openvino/runtime/intel_gpu/ocl/ocl_wrapper.hpp:50,
                 from /usr/share/openvino/runtime/include/openvino/runtime/intel_gpu/ocl/ocl.hpp:17,
                 from /tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp:5:
/usr/include/CL/cl2.hpp:18:151: note: ‘#pragma message: cl2.hpp has been renamed to opencl.hpp to make it clear that it supports all versions of OpenCL. Please include opencl.hpp directly.’
   18 | #pragma message("cl2.hpp has been renamed to opencl.hpp to make it clear that it supports all versions of OpenCL. Please include opencl.hpp directly.")
      |                                                                                                                                                       ^
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp: In constructor ‘ov_musicgen::MusicgenDecoderModelCL::MusicgenDecoderModelCL(ov::Core&, ov_musicgen::MusicGenConfig&)’:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp:70:84: warning: narrowing conversion of ‘(max_tokens + 1)’ from ‘size_t’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
   70 |             port_to_shape[model->input("custom_attention_mask")] = { 1, max_tokens + 1 };
      |                                                                         ~~~~~~~~~~~^~~
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp:80:73: warning: narrowing conversion of ‘max_tokens’ from ‘size_t’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
   80 |                      port_to_shape[model->input(tensorname)] = { 2, 16, max_tokens, 64 };
      |                                                                         ^~~~~~~~~~
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp:232:24: warning: narrowing conversion of ‘(__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type)(&(&(&((ov_musicgen::MusicgenDecoderModelCL*)this)->ov_musicgen::MusicgenDecoderModelCL::_past_key_values_ov.std::vector<std::vector<ov::Tensor> >::operator[](0))->std::vector<ov::Tensor>::operator[](2))->ov::Tensor::get_shape())->ov::Shape::operator[](2)’ from ‘__gnu_cxx::__alloc_traits<std::allocator<long unsigned int>, long unsigned int>::value_type’ {aka ‘long unsigned int’} to ‘ov::Dimension::value_type’ {aka ‘long int’} [-Wnarrowing]
  232 |          model->reshape({ {2, _past_key_values_ov[0][2].get_shape()[2], 1024} });
      |          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp: In member function ‘virtual ov::Tensor ov_musicgen::MusicgenDecoderModelCL::run(at::Tensor, std::optional<at::Tensor>, std::optional<at::Tensor>)’:
/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/modules/mod-openvino/musicgen/music_gen_decoder_cl.cpp:524:58: warning: narrowing conversion of ‘((ov_musicgen::MusicgenDecoderModelCL*)this)->ov_musicgen::MusicgenDecoderModelCL::_past_length’ from ‘int64_t’ {aka ‘long int’} to ‘long unsigned int’ [-Wnarrowing]
  524 |                   std::array<size_t, 3> dstOrigin = { 0, _past_length,  0 };
      |                                                          ^~~~~~~~~~~~
make[3]: Leaving directory '/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/build'
make[2]: *** [CMakeFiles/Makefile2:6001: modules/mod-openvino/CMakeFiles/mod-openvino.dir/all] Error 2
make[2]: Leaving directory '/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/build'
make[1]: *** [CMakeFiles/Makefile2:6008: modules/mod-openvino/CMakeFiles/mod-openvino.dir/rule] Error 2
make[1]: Leaving directory '/tmp/SBo/repo.MOu6rV/build_openvino-plugins-ai-audacity/openvino-plugins-ai-audacity-3.6.4-R3.4/audacity-sources-3.6.4/build'
make: *** [Makefile:1349: mod-openvino] Error 2
Build time 283 sec, peak load 13.45, peak memory 11595M, peak tmp 390M
audio/openvino-plugins-ai-audacity: openvino-plugins-ai-audacity.SlackBuild failed (status 2)
                                                                        00:46:05
Unmounting chroot ... 
:-( audio/openvino-plugins-ai-audacity FAILED )-:
```

**Comment by willysr** [comment]
> > @aclemons can you help build and test this?
> 
> Shouldn't Johannes handle this? Looks like it was broken by [47f1e03](https://github.com/SlackBuildsOrg/slackbuilds/commit/47f1e03f202699eb4cac80685efe2dc6b41b84cb)

I messaged him but no reply yet

**Pull request closed without merging**
