### PR TITLE
Please update python-prometheus_client and jupyterlab_pygments

### PR DESCRIPTION
**Pull request by isaackwy**

### CODE REVIEW

**Comment by willysr** [comment]
merged

**Comment by aclemons** [comment]
@isaackwy development/jupyterlab_pygments does not seem to build:

```
[...]
jupyterlab_pygments-0.2.0/style/index.css
jupyterlab_pygments-0.2.0/style/index.js
jupyterlab_pygments-0.2.0/tsconfig.json
jupyterlab_pygments-0.2.0/yarn.lock
Traceback (most recent call last):
  File "/tmp/SBo/jupyterlab_pygments-0.2.0/setup.py", line 8, in <module>
    from jupyter_packaging import (
ModuleNotFoundError: No module named 'jupyter_packaging'
```

Did you mean to submit a build for jupyter_packaging too?

**Comment by isaackwy** [comment]
Hello Andrew,

I am very sorry for not noticing this additional dependency earlier.

I am preparing the JupyterLab SlackBuild in my own computer.
JupyterLab requires jupyter_packaging - that's why I have jupyter_packaging installed.

jupyter_packaging in return requires python-deprecation, python-tomlkit and wheel.

Here are the SlackBuilds at my own git repo - with all the required dependencies:
https://github.com/isaackwy/slackbuilds-15.0/tree/main/Data_Science/Python/python-deprecation
https://github.com/isaackwy/slackbuilds-15.0/tree/main/Data_Science/Python/python-tomlkit
https://github.com/isaackwy/slackbuilds-15.0/tree/main/Data_Science/Development/jupyter_packaging

I will upload the required dependencies in a day or 2.

- Isaac

**Comment by aclemons** [comment]
That's all good. Just wanted to check that you were aware.

**Comment by isaackwy** [comment]
I just submitted jupyter_packaging on SlackBuilds.org.
However, I requested SlackBuilds.org to revert jupyterlab_pygments to 0.1.2.
jupyterlab_pygments >= 0.2.0 depends on jupyterlab, and jupyterlab in return depends jupyterlab_pygments (circular dependency).

**Pull request closed without merging**
