### PR TITLE
Updates - kodi & inputstream.adaptive

### PR DESCRIPTION
**Pull request by bassmadrigal**
multimedia/kodi: Version bump to 20.1
multimedia/inputstream.adaptive: Version bump to 20.3.5

### CODE REVIEW

**Comment by aclemons** [comment]
This failed to build for me Jeremy (this was on 32bit, but I had the same error on x86_64). I have all optional dependencies installed:

```
Building multimedia/kodi (update for version 20.1) 2023-03-18 00:09:46
Testing SlackBuild files ...
Downloading source files ...
Verifying source files ...
Installing dependencies ...
gtest-1.10.0-i586-4_SBo: Google C++ Testing Framework .................. [ 6.0M]
zulu-openjdk11-11.0.18-i686-1_SBo: Open Implementation of JDK .......... [ 281M]
  Running profile script: /etc/profile.d/zulu-openjdk11.sh
dav1d-1.1.0-i586-1_SBo: AV1 decoder .................................... [ 1.2M]
flatbuffers-23.1.4-i586-1_SBo: Serialization Library ................... [ 5.9M]
fmt-9.1.0-i586-1_SBo: A modern formatting library ...................... [ 950K]
libass-0.14.0-i586-1_SBo: Subtitle renderer for the ASS/SSA ............ [ 280K]
platform-2.1.0-i586-1_SBo: support library ............................. [ 310K]
libcec-4.0.4-i586-1_SBo: library for the Pulse-Eight USB-HDMI CEC Adapte [ 1.5M]
libmicrohttpd-0.9.75-i586-1_SBo: HTTP server C library ................. [ 660K]
libnfs-5.0.1-i586-1_SBo: NFS client library ............................ [ 880K]
rapidjson-1.1.0-i586-3_SBo: A fast JSON parser/generator for C++ ....... [  16M]
libdaemon-0.14-i586-2_SBo: Unix daemonizing library .................... [ 110K]
Adding groups and users:
  groupadd -g 214 avahi;
  useradd  -u 214 -g avahi -c avahi -d /dev/null -s /bin/false  avahi;
avahi-0.8-i586-8_SBo: service discovery aka zeroconf ................... [ 2.3M]
Reloading system message bus configuration...
shairplay-0.1.1-i586-6_SBo: AirPlay server ............................. [ 170K]
spdlog-1.10.0-i586-1_SBo: Fast C++ logging library ..................... [ 1.5M]
tinyxml-2.6.2-i586-3_SBo: A small xml parser ........................... [ 220K]
cwiid-0.6.91_2-i586-3_SBo: tools for the Nintendo Wii remote ........... [ 450K]
lirc-0.9.3a-i586-6_SBo: linux infrared remote control .................. [ 9.6M]
Running kodi.SlackBuild ...                                         ETA 00:25:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./kodi.SlackBuild
[...]
[ 97%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/Window.cpp.o
[ 97%] Linking CXX static library utils.a
[ 97%] Built target utils
[ 97%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/String.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/ListItem.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/Settings.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/Keyboard.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/InfoTagVideo.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/InfoTagRadioRDS.cpp.o
[ 98%] Linking CXX static library network_upnp.a
[ 98%] Built target network_upnp
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/InfoTagGame.cpp.o
[ 98%] Building CXX object build/interfaces/legacy/CMakeFiles/legacy_interface.dir/Dialog.cpp.o
[100%] Generating AddonModuleXbmcaddon.i.cpp
[100%] Linking CXX static library legacy_interface.a
[100%] Built target legacy_interface
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcvfs.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcdrm.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcgui.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmc.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcplugin.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcwsgi.i.cpp.o
[100%] Linking CXX static library libpython_binding.a
[100%] Built target python_binding
[100%] Linking CXX static library libkodi.a
[100%] Built target libkodi
[100%] Building CXX object CMakeFiles/kodi.dir/xbmc/platform/posix/main.cpp.o
[100%] Linking CXX executable kodi.bin
build/network/httprequesthandler/python/network_httprequesthandlers_python.a(HTTPPythonWsgiInvoker.cpp.o):HTTPPythonWsgiInvoker.cpp:function spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>): error: undefined reference to
'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/httprequesthandler/python/network_httprequesthandlers_python.a(HTTPPythonWsgiInvoker.cpp.o):HTTPPythonWsgiInvoker.cpp:function void spdlog::logger::log<char [61]>(spdlog::level::level_enum, char const (&) [61]): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/httprequesthandler/python/network_httprequesthandlers_python.a(HTTPPythonWsgiInvoker.cpp.o):HTTPPythonWsgiInvoker.cpp:function void spdlog::logger::log<char [62]>(spdlog::level::level_enum, char const (&) [62]): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/httprequesthandler/python/network_httprequesthandlers_python.a(HTTPPythonWsgiInvoker.cpp.o):HTTPPythonWsgiInvoker.cpp:function void spdlog::logger::log_<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/utils/utils.a(log.cpp.o):log.cpp:function spdlog::sinks::dup_filter_sink<spdlog::details::null_mutex>::sink_it_(spdlog::details::log_msg const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kodi.dir/build.make:618: kodi.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:5358: CMakeFiles/kodi.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Build time 440 sec, peak load 13.96, peak memory 2855M, peak tmp 396M
multimedia/kodi: kodi.SlackBuild failed (status 2)                      00:17:40
Unmounting chroot ...
:-( multimedia/kodi FAILED )-:
```

**Comment by aclemons** [comment]
I'll try now without any optional dependencies to see if that makes a difference

**Comment by aclemons** [comment]
I get the same error without them:

```
Building multimedia/kodi (update for version 20.1) -------------------- 00:27:47
Testing SlackBuild files ... done.
Verifying source files ... done.
Testing download URLs ... done.
mount: /tmp/slackrepo.IpH1o5/chrootdir/root/.Xauthority: special device /root/.Xauthority does not exist.
Installing dependencies ...
gtest-1.10.0-i586-4_SBo: Google C++ Testing Framework ................................................................................................................................................................................................................... [ 6.0M]
zulu-openjdk11-11.0.18-i686-1_SBo: Open Implementation of JDK ........................................................................................................................................................................................................... [ 281M]
  Running profile script: /etc/profile.d/zulu-openjdk11.sh
flatbuffers-23.1.4-i586-1_SBo: Serialization Library .................................................................................................................................................................................................................... [ 5.9M]
fmt-9.1.0-i586-1_SBo: A modern formatting library ....................................................................................................................................................................................................................... [ 950K]
libass-0.14.0-i586-1_SBo: Subtitle renderer for the ASS/SSA ............................................................................................................................................................................................................. [ 280K]
rapidjson-1.1.0-i586-3_SBo: A fast JSON parser/generator for C++ ........................................................................................................................................................................................................ [  16M]
spdlog-1.10.0-i586-1_SBo: Fast C++ logging library ...................................................................................................................................................................................................................... [ 1.5M]
tinyxml-2.6.2-i586-3_SBo: A small xml parser ............................................................................................................................................................................................................................ [ 220K]
Running kodi.SlackBuild ...                                         ETA 00:44:??
[...]
[ 98%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcgui.i.cpp.o
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcwsgi.i.cpp.o
[100%] Linking CXX static library libpython_binding.a
[100%] Built target python_binding
[100%] Linking CXX static library libkodi.a
[100%] Built target libkodi
[100%] Building CXX object CMakeFiles/kodi.dir/xbmc/platform/posix/main.cpp.o
[100%] Linking CXX executable kodi.bin
build/network/upnp/network_upnp.a(UPnP.cpp.o):UPnP.cpp:function void spdlog::logger::log_<char const* const&, char const* const&>(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::basic_string_view<char>, char const* const&, char const* const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/upnp/network_upnp.a(UPnP.cpp.o):UPnP.cpp:function UPNP::CMediaBrowser::OnContainerChanged(NPT_Reference<PLT_DeviceData>&, char const*, char const*): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/upnp/network_upnp.a(UPnP.cpp.o):UPnP.cpp:function UPNP::CMediaBrowser::InvokeUpdateObject(char const*, std::set<std::pair<NPT_String, NPT_String>, std::less<std::pair<NPT_String, NPT_String> >, std::allocator<std::pair<NPT_String, NPT_String> > > const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/network/upnp/network_upnp.a(UPnP.cpp.o):UPnP.cpp:function UPNP::CMediaBrowser::InvokeUpdateObject(char const*, std::set<std::pair<NPT_String, NPT_String>, std::less<std::pair<NPT_String, NPT_String> >, std::allocator<std::pair<NPT_String, NPT_String> > > const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
build/utils/utils.a(log.cpp.o):log.cpp:function spdlog::sinks::dup_filter_sink<spdlog::details::null_mutex>::sink_it_(spdlog::details::log_msg const&): error: undefined reference to 'spdlog::details::log_msg::log_msg(fmt::v9::basic_string_view<char>, spdlog::level::level_enum, fmt::v9::basic_string_view<char>)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kodi.dir/build.make:596: kodi.bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:5253: CMakeFiles/kodi.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Build time 436 sec, peak load 14.56, peak memory 2222M, peak tmp 421M
multimedia/kodi: kodi.SlackBuild failed (status 2)                      00:35:27
Unmounting chroot ...
:-( multimedia/kodi FAILED )-:
```

**Comment by bassmadrigal** [comment]
Shoot, I think I bumped spdlog beyond what was on SBo and forgot to
document it (been testing the new Kodi for a few weeks).

Can you skip adding Kodi and inputstream.adaptive (since bumping Kodi will
break the latter) and I'll reach out to the spdlog maintainer to try and
get an update pushed to 1.11.0.

Sorry for the noise and thanks for the catch!

**Comment by bassmadrigal** [comment]
Closing to resubmit with new, correct commits.

**Pull request closed without merging**
