### PR TITLE
games/gargoyle: updated for version 2023.1

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
```
# buildpkg i586 games/gargoyle
sbolint: gargoyle checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Thu Mar  2 21:50:52 GMT 2023
revision: 3093a956e5f3cd6b31ac5f106a2e6f40016c66b0
title:    games/gargoyle: Updated for version 2023.1.

================================================================================
games/gargoyle                                                          21:51:50
================================================================================

Calculating dependencies ... 
Hints for games/gargoyle:
  PRAGMA="noexport_BUILD download_basename"

Building games/gargoyle (update for version 2023.1) ------------------- 21:51:50
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Pragma: noexport_BUILD
Pragma: download_basename
Running gargoyle.SlackBuild ...                                     ETA 21:52:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./gargoyle.SlackBuild
Built ok:  gargoyle-2023.1-i586-1_SBo.txz                               21:52:30
Testing package gargoyle-2023.1-i586-1_SBo.txz ... 
WARNING: games/gargoyle: Bad directories/files
drwxr-xr-x root/root         0 2023-03-02 21:52 usr/share/man/
drwxr-xr-x root/root         0 2023-03-02 21:52 usr/share/man/man6/
-rw-r--r-- root/root      3492 2023-02-20 06:08 usr/share/man/man6/gargoyle.6
WARNING: games/gargoyle: usr/share/icons/hicolor in package but not in doinst.sh
WARNING: games/gargoyle: Uncompressed man pages
-rw-r--r-- root/root      3492 2023-02-20 06:08 usr/share/man/man6/gargoyle.6
Test installing gargoyle-2023.1-i586-1_SBo.txz ...
gargoyle-2023.1-i586-1_SBo: interactive fiction interpreter ............ [  19M]
Unmounting chroot ... done.
Backed up: gargoyle-2022.1-i586-1_SBo.txz
:-) games/gargoyle Updated for version 2023.1 (-:

================================================================================
SUMMARY                                                                 21:52:33
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-02_21:51:50.log
Runtime:     0h 0m 43s
Updated:     1
  games/gargoyle/gargoyle-2023.1-i586-1_SBo.txz
Warnings:    3
  games/gargoyle: Bad directories/files
  games/gargoyle: Uncompressed man pages
  games/gargoyle: usr/share/icons/hicolor in package but not in doinst.sh

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/games/gargoyle/gargoyle-2023.1-i586-1_SBo.txz to /tmp/sbopkglint.YaUpDH ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/games/gargoyle/gargoyle-2023.1-i586-1_SBo.txz to /tmp/sbopkglint.YaUpDH ...OK
Running test: 05-basic-sanity...
--- forbidden directory exists: usr/share/man
FAILED
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...
--- doinst.sh exists, but is missing gtk-update-icon-cache
FAILED
--- doinst.sh exists, but is missing fc-cache
Running test: 50-icons...OK
!!! gargoyle-2023.1-i586-1_SBo.txz: 3 failures
```

**Comment by aclemons** [comment]
Could you please check on these man pages?

**Comment by Ythogtha** [comment]
Updated, right place and zipped.

**Comment by aclemons** [comment]
```
# buildpkg i586 games/gargoyle
sbolint: gargoyle checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar  3 11:38:21 GMT 2023
revision: ffd3bcb10d8beddd8b16d3ebd7076c9a17c3a213
title:    games/gargoyle: Updated for version 2023.1.

================================================================================
games/gargoyle                                                          11:38:48
================================================================================

Calculating dependencies ... 
Hints for games/gargoyle:
  PRAGMA="noexport_BUILD download_basename"

----------------------------------------------------------------------- 11:38:48
Building games/gargoyle (update for git ffd3bcb "Updated for version 2023.1")
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Pragma: noexport_BUILD
Pragma: download_basename
Running gargoyle.SlackBuild ...                                     ETA 11:40:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./gargoyle.SlackBuild
Built ok:  gargoyle-2023.1-i586-6_SBo.txz                               11:39:25
Testing package gargoyle-2023.1-i586-6_SBo.txz ... done.
Test installing gargoyle-2023.1-i586-6_SBo.txz ...
gargoyle-2023.1-i586-6_SBo: interactive fiction interpreter ............ [  19M]
Unmounting chroot ... done.
Backed up: gargoyle-2023.1-i586-5_SBo.txz
:-) games/gargoyle Updated for git ffd3bcb "Updated for version 2023.1" (-:

================================================================================
SUMMARY                                                                 11:39:30
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-03_11:38:47.log
Runtime:     0h 0m 43s
Updated:     1
  games/gargoyle/gargoyle-2023.1-i586-6_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/games/gargoyle/gargoyle-2023.1-i586-6_SBo.txz to /tmp/sbopkglint.mbw30b ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/games/gargoyle/gargoyle-2023.1-i586-6_SBo.txz to /tmp/sbopkglint.mbw30b ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== gargoyle-2023.1-i586-6_SBo.txz: All tests passed
```

```
# buildpkg x86_64 games/gargoyle
sbolint: gargoyle checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar  3 11:38:21 GMT 2023
revision: ffd3bcb10d8beddd8b16d3ebd7076c9a17c3a213
title:    games/gargoyle: Updated for version 2023.1.

================================================================================
games/gargoyle                                                          11:39:48
================================================================================

Calculating dependencies ... 
Hints for games/gargoyle:
  PRAGMA="noexport_BUILD download_basename"

----------------------------------------------------------------------- 11:39:48
Building games/gargoyle (update for git ffd3bcb "Updated for version 2023.1")
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Pragma: noexport_BUILD
Pragma: download_basename
Running gargoyle.SlackBuild ...                                     ETA 11:40:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./gargoyle.SlackBuild
Built ok:  gargoyle-2023.1-x86_64-3_SBo.txz                             11:40:23
Testing package gargoyle-2023.1-x86_64-3_SBo.txz ... done.
Test installing gargoyle-2023.1-x86_64-3_SBo.txz ...
gargoyle-2023.1-x86_64-3_SBo: interactive fiction interpreter .......... [  19M]
Unmounting chroot ... done.
Backed up: gargoyle-2023.1-x86_64-2_SBo.txz
:-) games/gargoyle Updated for git ffd3bcb "Updated for version 2023.1" (-:

================================================================================
SUMMARY                                                                 11:40:27
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-03_11:39:48.log
Runtime:     0h 0m 40s
Updated:     1
  games/gargoyle/gargoyle-2023.1-x86_64-3_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/games/gargoyle/gargoyle-2023.1-x86_64-3_SBo.txz to /tmp/sbopkglint.dSP7iZ ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/games/gargoyle/gargoyle-2023.1-x86_64-3_SBo.txz to /tmp/sbopkglint.dSP7iZ ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== gargoyle-2023.1-x86_64-3_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
LGTM - staged to my branch

**Pull request closed without merging**
