### PR TITLE
Red/master

### PR DESCRIPTION
**Pull request by RSKYS**
Rebased #1268

### CODE REVIEW

**Comment by willysr** [comment]
Does windscribe only works for 64 bit architecture?
how about 32 bit system?

**Comment by RSKYS** [comment]
Hi,
No Willy, there's no support for 32bit version.

**Comment by willysr** [comment]
are you sure? the project page doesn't mention about this but it was tested against older Ubuntu version which still have 32 bit support

**Comment by RSKYS** [comment]
Mhm.. current binary?
I don't have 32bit system to test tbh ¯\\\_(ツ)_/¯
There was only old thread on reddit and I assumed dead, if you can verify this binary works with 32bit, I'll apply fixes for /opt and I'll move source to simple DOWNLOAD in info file.

**Comment by RSKYS** [comment]
Either way, this might be better for now.
Let's investigate 32bit another time.

**Comment by willysr** [comment]
merged
please don't change the SlackBuild permission to 755

**Comment by RSKYS** [comment]
Oops, I just saw where was wrong,
sorry xD

**Pull request closed without merging**
