### PR TITLE
python/typing-extensions: Update for 4.6.0

### PR DESCRIPTION
**Pull request by isaackwy**
1. I took a look at all the SlackBuilds that depend on typing-extensions. They all can build with typing-extensions 4.6.0. None of them restrict typing-extensions to an earlier version. At most, pydantic requires typing-extensions >= 4.2.0.
2. fourtysixandtwo has already removed python3-flit_core and python3-installer from the list of dependencies (REQUIRES).

### CODE REVIEW

**Comment by willysr** [comment]
this patch doesn't apply well here

**Comment by isaackwy** [comment]
Please elaborate (ex. provide output).

I don't know if it's fourtysixandtwo's dependency updates, or if typing-extensions 4.6.0 is too new a version for Slackware 15.0.

**Comment by willysr** [comment]
it doesn't apply cleanly here, so i'm not able to merge it

**Comment by willysr** [comment]
```
git am -s 2860.patch 
Applying: python/typing-extensions: Update for 4.6.0
error: patch failed: python/typing-extensions/typing-extensions.info:1
error: python/typing-extensions/typing-extensions.info: patch does not apply
Patch failed at 0001 python/typing-extensions: Update for 4.6.0
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by isaackwy** [comment]
Okay... in that case, I'll just close this pull request (not update typing-extensions for now).
I might bring up this pull request again next week.
I don't know what's going on at your end.

**Comment by willysr** [comment]
or i can take this PR and drop the one in my branch because both update the DEP and yours also update to latest version. What do you think?

**Comment by willysr** [comment]
merged

**Comment by isaackwy** [comment]
Thanks Willy! Please include my PR!

**Pull request closed without merging**
