### PR TITLE
office/xtrkcad: Updated for version 5.3.0GA.

### PR DESCRIPTION
**Pull request by newHeiko**
- new build-time dependency FreeImage
- Removed reference to Yahoo! Group, replaced with groups.io link
- Updated copyright year
- Removed unused LIBDIRSUFFIX

### CODE REVIEW

**Comment by newHeiko** [comment]
@sbo-bot: build office/xtrkcad

(can I even do this?)

**Comment by willysr** [comment]
@sbo-bot: build office/xtrkcad

**Comment by willysr** [comment]
@newHeiko it seems it now requires inkscape

**Comment by newHeiko** [comment]
> @newHeiko it seems it now requires inkscape

Yes, sorry I didn't catch that.

Heiko

**Comment by willysr** [comment]
@sbo-bot: build office/xtrkcad

**Comment by willysr** [comment]
@newHeiko more deps are needed i guess

**Comment by newHeiko** [comment]
That's weird, I don't have MiniXML here either.

Seems like an instance of https://gitlab.com/inkscape/inkscape/-/issues/4716 - I may have to limit the number of parallel inkscape processes...

Heiko

**Comment by newHeiko** [comment]
Yes, reproduced it with MAKEFLAGS=-j24. Will have a fix in an hour or two.

Heiko

**Comment by aclemons** [comment]
@sbo-bot: build office/xtrkcad

**Comment by newHeiko** [comment]
Okay, seems I'll need to find where it gets libzip from and why that one's not i386-compatible...

**Comment by newHeiko** [comment]
...and let's give it another go... thank you @aclemons for the CI, I would never have caught this on my own.

(don't know why the pull_request_target now fails - any ideas?)

Heiko

**Comment by newHeiko** [comment]
> (don't know why the pull_request_target now fails - any ideas?)

Nevermind that, re-triggering it with a Rebase fixed it.

**Comment by aclemons** [comment]
@sbo-bot: build office/xtrkcad

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
