### PR TITLE
gis/python3-xarray: Updated for version 2024.02.0.

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build gis/python3-xarray

**Comment by aclemons** [comment]
@sbo-bot: build gis/python3-xarray

**Comment by willysr** [comment]
@ArTourter this has wrong checksum

**Comment by ArTourter** [comment]
they must have updated the file since I submitted it.
forced push an updated version

**Comment by willysr** [comment]
@sbo-bot: build gis/python3-xarray

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
