### PR TITLE
Update webkitgtk6.0.info

### PR DESCRIPTION
**Pull request by nater1983**

### CODE REVIEW

**Comment by nater1983** [comment]
Fixed Checksums

**Comment by willysr** [comment]
can you push all your changes for webkitgtk6.0 into a single change?
oh, also, If possible, can you rename the script into webkit2gtk6.0 in order to be consistent with the rest of the script?

**Comment by nater1983** [comment]
webkitgtk6.0 the name is following upstream.

**Comment by willysr** [comment]
ohh right

**Pull request closed without merging**
