### PR TITLE
Late November updates

### PR DESCRIPTION
**Pull request by RezaT4795**
- system/android-udev-rules: Updated to version 2023.11.24.
- network/nordvpn: Updated to version 3.16.8.
- network/windscribe: Updated to version 2.7.14.
- libraries/wimlib: Updated to version 1.14.3.
- system/powershell: Updated to version 7.4.0.
- development/dotnet-runtime-6.0: Updated to version 6.0.25
- development/dotnet-sdk-6.0: Updated to version 6.0.417
- libraries/aspnetcore-runtime-6.0: Updated to version 6.0.25
- development/aspnetcore-runtime-7.0: Updated to version 7.0.14
- development/dotnet-runtime-7.0: Updated to version 7.0.14
- development/dotnet-sdk-7.0: Updated to version 7.0.404

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build libraries/wimlib

**Comment by willysr** [comment]
@sbo-bot: build development/dotnet-runtime-6.0

**Comment by willysr** [comment]
@sbo-bot: build development/dotnet-sdk-7.0

**Comment by willysr** [comment]
@sbo-bot: build libraries/aspnetcore-runtime-6.0

**Comment by willysr** [comment]
@sbo-bot: build network/windscribe

**Comment by willysr** [comment]
@sbo-bot: build network/nordvpn

**Comment by willysr** [comment]
@sbo-bot: build development/aspnetcore-runtime-7.0

**Comment by willysr** [comment]
@sbo-bot: build development/dotnet-runtime-7.0

**Comment by willysr** [comment]
@sbo-bot: build system/android-udev-rules

**Comment by willysr** [comment]
@sbo-bot: build system/powershell

**Comment by willysr** [comment]
@sbo-bot: build development/dotnet-sdk-6.0

**Comment by willysr** [comment]
@RezaT4795 can you check on winscribe please?

**Comment by willysr** [comment]
merged with fixes to windscribe

**Comment by RezaT4795** [comment]
@willysr Sorry I was AFK for a few days. Thanks for your fixes.

**Pull request closed without merging**
