### PR TITLE
Take over maintainership of Larry's games

### PR DESCRIPTION
**Pull request by bassmadrigal**
I'll run a build test to see if any are currently broken and I'll (try to) fix them in the next update, but no changes to SlackBuilds have been made, just the maintainer stuff in the .info, so even if there are broken packages, this should still be merged to indicate me being the new maintainer.

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/alienarena

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/brainparty

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/chroma

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/chromium-bsu

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/cubosphere

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/cuyo

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/glestae

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/jag

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/meandmyshadow

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/megaglest

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/pasang-emas

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/peg-e

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/rezerwar

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/yabause

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
