### PR TITLE
python/buildbot: updated for version 3.4.1 and python3

### PR DESCRIPTION
**Pull request by Ythogtha**
Requires PR for python-twisted, python-automat, python-pyjwt, python-txaio, python-autobahn, python-alembic.

### CODE REVIEW

**Comment by Ythogtha** [comment]
I've decided its best to include buildbot packages directly there.
Most are mandatory (you need one view at least) for web interface.
Those are the packages maintained directly by the core buildbot team, and with matching versioning (all of them are 3.4.1).

**Comment by willysr** [comment]
is this different from buildbot-worker i have just approved? 
https://git.slackbuilds.org/slackbuilds/commit/?h=willysr&id=0cc0d794adb2fa4c36fdc6a3ff0d998787645b78

**Comment by Ythogtha** [comment]
Yes, it is the server part, a bit more complex and separate from the client part named buildbot-worker!

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
