### PR TITLE
multimedia/kodi: Add patch to fix building w/ newer fmt versions

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
Shoot, I forgot to update the BUILD number. Can you do that or should I send another commit?

**Comment by willysr** [comment]
is this to solve building issue with stable or current? if this doesn't affect stable, i think no need to bump BUILD

**Comment by bassmadrigal** [comment]
It is to fix a broken build on stable due to the newer fmt in the SBo repo.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
