### PR TITLE
libraries/DevIL: updated for version 1.8.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
There is no VERSION changes on this patch

**Comment by Ythogtha** [comment]
Yes, it's a stupid commit message, I forgot to check it.
The commit is about : "Fix build on slackware-current"

**Comment by willysr** [comment]
can you fix the commit message first?

**Comment by Ythogtha** [comment]
Ok, I forced-pushed the correct commit message, sorry for the mess !

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
