### PR TITLE
games/vcmi: updated for version 1.3.2

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build games/vcmi

**Comment by aclemons** [comment]
@Ythogtha seems there is no longer a README in the tarball

```sh
[...]
-- Installing: /tmp/SBo/repo.k72izQ/build_vcmi/package-vcmi/usr/share/vcmi/Mods/vcmi/mod.json
-- Installing: /tmp/SBo/repo.k72izQ/build_vcmi/package-vcmi/usr/bin/vcmibuilder
cp: cannot stat 'README*': No such file or directory
Build time 338 sec, peak load 13.45, peak memory 9107M, peak tmp 3123M
games/vcmi: vcmi.SlackBuild failed (status 1)                           06:24:58
```

**Comment by Ythogtha** [comment]
Well, I went a bit fast here, hoping it'd be straightforward and I could push it before weekend update.
This is fixed and ready for next update, sorry !

**Comment by Ythogtha** [comment]
Well, looks like the push is strangely messed-up, I'll close this PR and reopen a new one aside...

**Pull request closed without merging**
