### PR TITLE
Khard update to 0.19.1

### PR DESCRIPTION
**Pull request by Tonus1**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build office/khard

**Comment by willysr** [comment]
@Tonus1 i think this will require newer setuptools? https://slackbuilds.org/repository/15.0/python/python3-setuptools-opt/

**Comment by Tonus1** [comment]
Sorry for the spam. I have some hard time understanding git...
The last modification to khard uses the new setuptools.

**Comment by willysr** [comment]
@sbo-bot: build office/khard

**Comment by willysr** [comment]
@sbo-bot: build i586 office/khard

**Pull request closed without merging**
