### PR TITLE
python/python3-flufl.lock: updated for version 8.1.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/python3-flufl.lock

**Comment by Ythogtha** [comment]
@willysr Fixed.

**Comment by willysr** [comment]
@sbo-bot: build python/python3-flufl.lock

**Comment by willysr** [comment]
@sbo-bot: build python/python3-flufl.lock

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
