### PR TITLE
graphics/brlcad: updated for version 7.38.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build graphics/brlcad

**Comment by willysr** [comment]
@sbo-bot: build i586 graphics/brlcad

**Comment by willysr** [comment]
@Ythogtha this failed on 32 bit architecture since it may require OpenCV

**Comment by Ythogtha** [comment]
> @Ythogtha this failed on 32 bit architecture since it may require OpenCV

@willysr but opencv is a system library on Slackware 15.0.
Anyway, it complains the same on 64bits, and build works.
I'm looking around the lines of ON_LITTLE_ENDIAN/ON_BIG_ENDIAN.
Or dropping the 32bit altogether, I'm quite unsure of its status for previous versions, it may well be possible that it's been broken for some time, and nobody complained...

Anyway, looking into it.

**Comment by aclemons** [comment]
Sorry, I added the code to snip the build log on failures, but I did a `head` instead of `tail` which is completely useless. Let me see the error on 32bit again.

**Comment by aclemons** [comment]
@sbo-bot: build i586 graphics/brlcad

**Comment by aclemons** [comment]
>
>I'm quite unsure of its status for previous versions, it may well be possible that it's been broken for some time, and nobody complained...

Looks like I failed to build the previous version (it's in weekly failure list), but the prior one did build:

```sh
-rw-r--r--   1 root root    412027 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.lst
-rw-r--r--   1 root root       744 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.meta
-rw-r--r--   1 root root       509 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.txt
-rw-r--r--   1 root root 133506380 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.txz
-rw-r--r--   1 root root        63 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.txz.md5
-rw-r--r--   1 root root        95 Mar  3  2023 brlcad-7.34.2-i586-1_SBo.txz.sha256
```

**Comment by aclemons** [comment]
^ ok that snip has the error in it now

**Comment by aclemons** [comment]
I see gentoo and freebsd have this marked as supported on x86, but both are currently still on 7.32.x.

https://www.mail-archive.com/brlcad-devel@lists.sourceforge.net/msg06915.html

Looks like 32bit is not really being tested upstream either. Might be time to mark it as unsupported here.

Final note, the builds here are running in a docker container and there is docker for 32bit hosts, so this 32bit docker image is running on a 64bit host - there is small chance that something there is the root cause of the error. If you have an actual 32bit VM to test with that might clarify if that is the issue.

**Comment by Ythogtha** [comment]
@willysr I pushed an update, I'm unsure if it'll fix the problem, but it might...

**Comment by Ythogtha** [comment]
@aclemons If what I'm trying fails, I'll mark it as unsupported for 32bits.

**Comment by aclemons** [comment]
@sbo-bot: build i586 graphics/brlcad

**Comment by Ythogtha** [comment]
Well, looks like it worked !

**Pull request closed without merging**
