### PR TITLE
development/whisper.cpp: Updated for version 1.6.2.

### PR DESCRIPTION
**Pull request by willysr**
This reverts commit 47f1e03f202699eb4cac80685efe2dc6b41b84cb.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/whisper.cpp

**Comment by willysr** [comment]
@sbo-bot: build x86_64 audio/openvino-plugins-ai-audacity

**Comment by aclemons** [comment]
@sbo-bot: build development/whisper.cpp

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 audio/openvino-plugins-ai-audacity

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
