### PR TITLE
 development/dmd: Updated for version 2.075.1

### PR DESCRIPTION
**Pull request by belka-ew**
* I moved the standard library and runtime sources from /usr/lib{,64}/d to /usr/include/d since it seems be the directory used by others (FreeBSD, Debian). Shared libraries are untouched.
* Updated for 2.075.1
* Updated README and slack-desc, since the description on the home page has been slightly changed.

### CODE REVIEW

**Comment by willysr** [comment]
Hi @belka-ew 

can you first test whether GtkD will compile with your changes to the standard library path?

thanks

**Comment by belka-ew** [comment]
Hey,

sure, just a second, it's compiling.

**Comment by belka-ew** [comment]
yes, looks well here: just built 3.6.5 on x64.

**Comment by willysr** [comment]
Thanks

**Comment by willysr** [comment]
merged in my branch

**Pull request closed without merging**
