### PR TITLE
development/rust16: Support arm builds.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
@pghvlaans Do you mind if we add support for arm?

**Comment by pghvlaans** [comment]
Not at all. This would be for the Slackware ARM project, correct?

I'll actually be pushing the version to 1.66.1 this week (assuming everything that's added rust16 as a dependency still builds), and will incorporate the changes.

**Comment by willysr** [comment]
just FYI, we don't officially support ARM in SBo and some of us don't have machine to test on ARM platform

**Comment by aclemons** [comment]
> Not at all. This would be for the Slackware ARM project, correct?

Yes, in my case to build things for my raspberry pi. Quite a few builds are moving to use this as a dependency now since upstreams are dropping support for older rusts.

> I'll actually be pushing the version to 1.66.1 this week (assuming everything that's added rust16 as a dependency still builds), and will incorporate the changes.

Yes, everything that uses our sort of standard rust template normally builds on arm. I have not found anything that didn't build yet. (except now the things which use `rust16` as a dep don't build since this package does not yet repackage the arm binaries)

**Pull request closed without merging**
