### PR TITLE
Buildbot

### PR DESCRIPTION
**Pull request by Ythogtha**
Buildbot and dependencies update

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/python3-klein

**Comment by willysr** [comment]
@sbo-bot: build python/python3-alembic

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot-worker

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot-badges

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot

**Comment by Ythogtha** [comment]
Oh, sorry, my local file had good md5sums, but the file pushed didn't.
That's fixed...

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
