### PR TITLE
development/smlnj: Added a patch in arch-n-opsys to build on kernel 5.x series.

### PR DESCRIPTION
**Pull request by DinizBortolotto**
development/smlnj: Added a patch in arch-n-opsys to build on kernel 5.x series.

### CODE REVIEW

**Comment by DinizBortolotto** [comment]
This PR is to fix build failure of smlnj reported on #5827

**Comment by willysr** [comment]
@sbo-bot: build development/smlnj

**Comment by willysr** [comment]
@DinizBortolotto this patch failed to work

**Comment by DinizBortolotto** [comment]
> @DinizBortolotto this patch failed to work

Maybe a copy/paste error between VBox and my git repo. I'll check that and fix it.

**Comment by willysr** [comment]
@sbo-bot: build development/smlnj

**Comment by willysr** [comment]
@sbo-bot: build development/rmlmmc

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
