### PR TITLE
audio/libfreeaptx

### PR DESCRIPTION
**Pull request by thnkman**

### CODE REVIEW

**Comment by thnkman** [comment]
> @thnkman this PR doesn't apply cleanly as the second commit failed

What do you need me to do?

**Comment by willysr** [comment]
can you try to rebase against latest master and make a single commit instead of 2?

**Comment by thnkman** [comment]
> this is another mess @thnkman :) make sure to have 1 commit per branch if possible

I am so so sorry :( Still learning.

**Comment by thnkman** [comment]
Phew!

**Pull request closed without merging**
