### PR TITLE
graphics/graphviz: updated for version 3.0.0, new maintainer

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
please test the following scripts that depends on graphviz
development/darcs
development/egypt
graphics/pencil2d
graphics/pygraphviz
graphics/xdot
libraries/log4c
libraries/properties-cpp
libraries/uriparser
network/w3af
office/xournalpp
python/pydot
system/nagvis

**Comment by Ythogtha** [comment]
I'll take some time to assess them all...

**Comment by willysr** [comment]
any progress on this ?

**Comment by Ythogtha** [comment]
Not finished yet, next week I think.

**Comment by Ythogtha** [comment]
Everything I could test was working fine.
Most of them though are only using graphviz as external command (creating graphes with dot for example, and using them later), hence it may be hard to really check it fully works under the hood.
Though, the dot format and interface didn't have breaking changes.
As for libraries and all, there have been breaking changes, but if everything builds, links, and starts fine, that should be ok.

I'm good to go!

**Comment by aclemons** [comment]
Ok, this is staged to my branch. I've started a rebuild of the full repo, will report back should anything which uses this as a library fails to build.

**Comment by aclemons** [comment]
actually, I get one error when installing the newly build package:
mv: cannot stat 'etc/php.d/graphviz.ini.new': No such file or directory

**Comment by aclemons** [comment]
Thanks. Merged to my branch now and I have started the full rebuild again.

**Comment by aclemons** [comment]
Everything built fine against the new versions, so at least no compilation problems with any of them.

**Pull request closed without merging**
