### PR TITLE
python/python3-flit_core: Remove DEPS, bootstrap process changed.

### PR DESCRIPTION
**Pull request by fourtysixand2**

### CODE REVIEW

**Comment by aclemons** [comment]
I fixed a couple of downstream packages which were failing because they were relying on this package to pull in `python3-installer`. There might be a few more we need to clean up once this hits master.

**Comment by aclemons** [comment]
I fixed these already:

- python/python-jeepney
- python/typing-extensions
- python/python3-pathspec

**Comment by willysr** [comment]
there are 15 of them, so can we fix them in this batch as well? 
I'm still building webkit2gtk, it could take a while

**Comment by aclemons** [comment]
Sure - I'm building the whole python series right now - will fix the ones I find

**Comment by aclemons** [comment]
Fixed these first level dependees:

- network/yle-dl
- python/python3-mdurl
- python/python3-tomli_w
- python/python3-threadpoolctl
- python/testpath
- python/python3-flit_scm
- python/python3-Flask-Dance
- python/python3-seaborn

Making another pass now.

**Comment by aclemons** [comment]
python/* clean now.

Building all reverse dependencies of this package now.

**Comment by willysr** [comment]
python-jeepney
python3-confuse
python3-mediafile
python3-more-itertools
python3-pathspec
typing-extensions
these are other packages that requires python3-flit_core

**Comment by aclemons** [comment]
All reverse dependencies built fine.

**Comment by willysr** [comment]
but what about runtime?

**Comment by aclemons** [comment]
python3-installer is just a python package for installing wheels, should have no runtime bearing

**Pull request closed without merging**
