### PR TITLE
perl/perl-parallel-forkmanager: Version bump to 2.03 & change to noarch

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build perl/perl-parallel-forkmanager

**Comment by bassmadrigal** [comment]
@sbo-bot: build audio/acxi

**Comment by bassmadrigal** [comment]
@sbo-bot: build development/cloc

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
