### PR TITLE
perl/perl-Crypt-OpenSSL-Random: Updated for version 0.15.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build perl/perl-Crypt-OpenSSL-Random

**Comment by aclemons** [comment]
@sbo-bot: build perl/perl-Crypt-OpenSSL-Random

**Comment by aclemons** [comment]
@pyllyukko: Sorry, I made a bit of mess of your branch, but this does not build without perl-Crypt-OpenSSL-Guess. But that package currently has this package in its requires.

```
Can't locate Crypt/OpenSSL/Guess.pm in @INC (you may need to install the Crypt::OpenSSL::Guess module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at Makefile.PL line 3.
BEGIN failed--compilation aborted at Makefile.PL line 3.
```

If I remove it from ponce's perl-Crypt-OpenSSL-Guess, both build. I grepped for references to Crypt-OpenSSL-Random in Crypt-OpenSSL-Guess and found none, so I am not sure why ponce added it as a dependency.

**Comment by aclemons** [comment]
@Ponce I just realised you are the maintainer of perl-Crypt-OpenSSL-Guess

**Comment by Ponce** [comment]
I did it when I upgraded another perl package for current 3 years ago but frankly I don't remember the reason...
I'm perfectly ok with removing the dependency.
BTW thanks for catching this!

**Comment by aclemons** [comment]
Thanks @Ponce, I'll update these here and stage them!

**Comment by aclemons** [comment]
@sbo-bot: build perl/perl-Crypt-OpenSSL-Random

**Comment by aclemons** [comment]
@sbo-bot: build perl/perl-Crypt-OpenSSL-Guess

**Review by aclemons — APPROVED** [review]
LGTM - I'll tidy these commits up on my branch

**Pull request merged**
