### PR TITLE
development/heroku-cli: Updated for version 9.2.1

### PR DESCRIPTION
**Pull request by DinizBortolotto**
development/heroku-cli: Updated for version 9.2.1

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/heroku-cli

**Comment by aclemons** [comment]
@sbo-bot: build development/heroku-cli

**Comment by DinizBortolotto** [comment]
I think symlinks like  'python3 -> /usr/bin/python3' should not fail on build as far its a usual python location on Slackware.
About those empty dir, they are node module stuff that where let there on build.I'll leave the decision up to you on bypass that or, if you want, mark as WIP and I'll check it out.  ;-)

**Comment by willysr** [comment]
you can discuss that with Urchlay since that's the output of sbopkglint, part of sbo-maintainer-tools

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
