### PR TITLE
academic/nco: Updated for version 5.1.9.

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build academic/nco

**Comment by willysr** [comment]
@ArTourter can you check the doinst.sh?

**Comment by ArTourter** [comment]
I am quite confused as the check works from my end and the do{,un}inst.sh files have not changed since last time.

```
Exploding /var/share/apps/slackbuilds/current/x86_64/nco-5.1.9-x86_64-1_SBo.tlz to /tmp/SBo/sbopkglint.Lc9CnL ...OK
Running pre-doinst test...OK
Installing /var/share/apps/slackbuilds/current/x86_64/nco-5.1.9-x86_64-1_SBo.tlz to /tmp/SBo/sbopkglint.Lc9CnL ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
Running test: 60-usr_info...OK
Running test: 65-python...OK
Running test: 70-tmp_path...OK
Running test: 75-static_libs...OK
Running test: 85-perl...OK
=== nco-5.1.9-x86_64-1_SBo.tlz: All tests passed
```

and the content of doinst.sh is

```
if [ -x /usr/bin/install-info ]; then
/usr/bin/install-info --info-dir=usr/info usr/info/nco.info.gz   1> /dev/null 2>&1
/usr/bin/install-info --info-dir=usr/info usr/info/nco.info-1.gz 1> /dev/null 2>&1
/usr/bin/install-info --info-dir=usr/info usr/info/nco.info-1.gz 1> /dev/null 2>&1
/usr/bin/install-info --info-dir=usr/info usr/info/nco.info-3.gz 1> /dev/null 2>&1
/usr/bin/install-info --info-dir=usr/info usr/info/nco.info-4.gz 1> /dev/null 2>&1
fi
```

**Comment by aclemons** [comment]
Yes, this seems to be some bug when I invoke it through the build process. Let me investigate later what is happening. Directly checking cached result on the box shows it is perfectly fine:

```sh
build nco # ls -la
total 1720
drwxr-xr-x   2 root root    4096 Nov 10 00:37 .
drwxr-xr-x 356 root root   12288 Nov 10 00:37 ..
-rw-r--r--   1 root root      52 Nov 10 00:37 nco-5.1.9-i586-1_SBo.dep
-rw-r--r--   1 root root    3933 Nov 10 00:37 nco-5.1.9-i586-1_SBo.lst
-rw-r--r--   1 root root     828 Nov 10 00:37 nco-5.1.9-i586-1_SBo.meta
-rw-r--r--   1 root root     604 Nov 10 00:37 nco-5.1.9-i586-1_SBo.txt
-rw-r--r--   1 root root 1713100 Nov 10 00:37 nco-5.1.9-i586-1_SBo.txz
-rw-r--r--   1 root root      59 Nov 10 00:37 nco-5.1.9-i586-1_SBo.txz.md5
-rw-r--r--   1 root root      91 Nov 10 00:37 nco-5.1.9-i586-1_SBo.txz.sha256
build nco # sbopkglint nco-5.1.9-i586-1_SBo.txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding nco-5.1.9-i586-1_SBo.txz to /tmp/SBo/sbopkglint.D1dL50 ...OK
Running pre-doinst test...OK
Installing nco-5.1.9-i586-1_SBo.txz to /tmp/SBo/sbopkglint.D1dL50 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
Running test: 60-usr_info...OK
Running test: 65-python...OK
Running test: 70-tmp_path...OK
Running test: 75-static_libs...OK
Running test: 85-perl...OK
=== nco-5.1.9-i586-1_SBo.txz: All tests passed
```

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
> Let me investigate later what is happening.

Ok, I was missing a dependency in the docker image and the `60-usr_info` which in sbopkglint does not differentiate between not running the check and the check failing. I've added it now and an updated image is building.

https://github.com/aclemons/sbo-maintainer-tools-docker/commit/a5174c60e024b2493e3cbee457e16c97df1040ad

**Comment by willysr** [comment]
thanks @aclemons

**Pull request merged**
