### PR TITLE
development/lazarus: Updated for version 3.6

### PR DESCRIPTION
**Pull request by antonioleal**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build development/lazarus

**Comment by aclemons** [comment]
@sbo-bot: build audio/easymp3gain

**Comment by aclemons** [comment]
@sbo-bot: build ham/cqrlog

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/winff

**Comment by aclemons** [comment]
@sbo-bot: build network/transgui

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
