### PR TITLE
python/python3-twisted: updated for version 22.8.0

### PR DESCRIPTION
**Pull request by Ythogtha**
This do not rely on commit for python3-automat.

### CODE REVIEW

**Comment by Ythogtha** [comment]
Looks like some more tests are needed, on hold...

**Comment by willysr** [comment]
still no update on this PR?

**Comment by Ythogtha** [comment]
Well I can't seem to make it fail now, on a clean environment, so I guess it's ok.
The trick was to make sure to properly rebuild cryptography.
And it's kind of hard on a chrooted environment, I had to set ulimit -n 1000000 (because 400k wasn't enough).
With all being built cleanly on a fully patched 15.0, it does actually work.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
