### PR TITLE
FTBFS

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/tomb

**Comment by willysr** [comment]
@sbo-bot: build office/qtrans

**Comment by willysr** [comment]
@sbo-bot: build misc/yubioath-desktop

**Comment by willysr** [comment]
@sbo-bot: build libraries/rabbitmq-c

**Comment by willysr** [comment]
@sbo-bot: build development/openjdk7

**Comment by willysr** [comment]
@sbo-bot: build system/tomb

**Comment by willysr** [comment]
@sbo-bot: build office/qtrans

**Comment by willysr** [comment]
@sbo-bot: build libraries/rabbitmq-c

**Comment by willysr** [comment]
@sbo-bot: build libraries/rabbitmq-c

**Comment by willysr** [comment]
@sbo-bot: build x86_64 misc/yubioath-desktop

**Comment by willysr** [comment]
@aclemons can you take a look on yubioath-desktop error message?
i tested on a clean VM and it built just fine

**Comment by aclemons** [comment]
> yubioath-desktop

@willysr I think did this in the previous mass rebuild by hand by temporarily running a container with `--privileged` which I did not want to do generally.

I've fixed this now permanently here:

https://github.com/aclemons/slackbuilds-ci/commit/a35493a951c866ad1a25af7f1e9b8a9448165a30

You can retrigger a build for yubioath-desktop and it should pass now.

**Comment by willysr** [comment]
I think Urchlay fix it as well with backtick issue

**Pull request closed without merging**
