### PR TITLE
system/nix: Updated to 2.13.6.

### PR DESCRIPTION
**Pull request by RSKYS**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@RSKYS, why does this PR for system/nix contain commits covering 9 other programs?

**Comment by RSKYS** [comment]
> @RSKYS, why does this PR for system/nix contain commits covering 9 other programs?

@bassmadrigal  Oh yeah, they're rebased against willysr branch.
Because I previously committed to system/nix this week :)

**Comment by bassmadrigal** [comment]
Commits should almost always be based against the master branch.

**Comment by RSKYS** [comment]
@bassmadrigal Yeah I shouldn't, you're right
But in this very specific case if I don't do it, Willy can't merge it

**Comment by RSKYS** [comment]
Alright, my apologies for triggering too many messages, but the work is done.
Needed changes at slak-desk and had some typo.. and ofcourse, EOF warn of sbolint in doinst.sh
Success log: [0_Build against Slackware 15.txt](https://github.com/user-attachments/files/16044974/0_Build.against.Slackware.15.txt)

**Comment by willysr** [comment]
you need to pull latest master update first in your local repository and please rebase your changes to latest master

**Comment by RSKYS** [comment]
> you need to pull latest master update first in your local repository and please rebase your changes to latest master

I've sent you a email, it's already like (scenario like k3s)[https://github.com/SlackBuildsOrg/slackbuilds/pull/6921#issuecomment-2195802369], tell me if I should rebase against mater or not then
I don't have problem with either way

**Comment by willysr** [comment]
yes, you need to rebase against latest master, so only 1 commit difference not 11

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
