### PR TITLE
multimedia/gpac: Version bump to 2.4.0 + new maintainer

### PR DESCRIPTION
**Pull request by bassmadrigal**
Nishant Limbachia was last active almost 5 years ago (SEP 2019) and this was last updated by him in 2017 (the current SBo version was updated by @ponce in 2021).

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/gpac

**Comment by bassmadrigal** [comment]
Oops... I readded slack-desc to the repo instead of the new doinst.sh.

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/gpac

**Comment by bassmadrigal** [comment]
@aclemons, once approved, you'll want to update your slackrepo hintfile since optional dependencies have changed.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
