### PR TITLE
Python2 mistune

### PR DESCRIPTION
**Pull request by Ythogtha**
mistune is a dependency of python-m2r, which a legacy python2 packages used to generate better documentation for Automat (python2-automat, maybe it works also for python3-automat, who knows), for which it is an optional dependency. And jupyter-nbconvert, maintained by Issac <isaacyu1@isaacyu1.com>.
python-m2r prevents mistune for being update (0.8.4 when there is a 2.0.4 version, and soon a 3.x)

Isaac requires an update of mistune for jupyter-nbconvert.
So we decided that he'll take over mistune, with submitting a python3-mistune, and updating REQUIRES accordingly.
And I'll keep the legacy mistune, renamed as python2-mistune, and used only by python-m2r.

I am hoping Automat will drop m2r for its documentation, and we'll then be able to drop both python2-mistune and python-m2r.

So here is my part of the job, and it requires that Issac's updates are validated before so the repository doesn't ship a broken jupyter-nbconvert.

### CODE REVIEW

**Comment by slackhead** [comment]
On 21/10/22 06:34,
Ythogtha ***@***.***> put forth the proposition:
> mistune is a dependency of python-m2r, which a legacy python2 packages used to generate better documentation for Automat (python2-automat, maybe it works also for python3-automat, who knows), for which it is an optional dependency. And jupyter-nbconvert, maintained by Issac ***@***.***&gt;.
> python-m2r prevents mistune for being update (0.8.4 when there is a 2.0.4 version, and soon a 3.x)
> Isaac requires an update of mistune for jupyter-nbconvert.
> So we decided that he&#39;ll take over mistune, with submitting a python3-mistune, and updating REQUIRES accordingly.
> And I&#39;ll keep the legacy mistune, renamed as python2-mistune, and used only by python-m2r.
> I am hoping Automat will drop m2r for its documentation, and we&#39;ll then be able to drop both python2-mistune and python-m2r.
> So here is my part of the job, and it requires that Issac&#39;s updates are validated before so the repository doesn&#39;t ship a broken jupyter-nbconvert.
> You can view, comment on, or merge this pull request online at:
>   https://github.com/SlackBuildsOrg/slackbuilds/pull/2031
> -- Commit Summary --
>   * python/python2-mistune: Renamed from mistune for python2 only
>   * python/python-m2r: Updated REQUIRES
> -- File Changes --
>     M python/python-m2r/python-m2r.info (2)
>     R python/python2-mistune/README (2)
>     R python/python2-mistune/python2-mistune.SlackBuild (13)
>     R python/python2-mistune/python2-mistune.info (2)
>     R python/python2-mistune/slack-desc (24)
> -- Patch Links --
> https://github.com/SlackBuildsOrg/slackbuilds/pull/2031.patch
> https://github.com/SlackBuildsOrg/slackbuilds/pull/2031.diff
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/SlackBuildsOrg/slackbuilds/pull/2031
> You are receiving this because you are subscribed to this thread.
> Message ID: ***@***.***&gt;

This would be better submitted through the submission form.  I'll
check that the dependees build.

Thanks

Dave

**Comment by Ythogtha** [comment]
I usually do renaming that way, but if you prefer I change and add the new one through submission, and limit this PR to removing the old one and managing REQUIRES, I can.

**Comment by willysr** [comment]
yes, new submission should be done via submission form as it needs to populate the database, not just git

**Comment by Ythogtha** [comment]
OK, this PR is updated for removal of python/mistune only, and changing REQUIRES of python-m2r to python2-mistune.
Hence it needs to be merged after the submission has been approved on the website.

**Comment by willysr** [comment]
i think Dave has made the change in python-m2r in https://git.slackbuilds.org/slackbuilds/commit/?h=bedlam&id=d4b40121c6aa128770ed24b41d28afd40da8776e
can you confirm and remove it from this pR?

**Comment by Ythogtha** [comment]
Done, PR is ready.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
