### PR TITLE
Cleanup python2 - again

### PR DESCRIPTION
**Pull request by Ythogtha**
Scripts from Markus Reichelt that don't need new maintainer.

### CODE REVIEW

**Comment by willysr** [comment]
Can you make the commit message shorter than 72 characters? It will be overly long in email announcement

**Comment by Ythogtha** [comment]
Done !

**Comment by willysr** [comment]
you missed pycryptopp for darcsver

**Comment by Ythogtha** [comment]
Oh. Yeah.
Needs to be removed too, added to the list !

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
