### PR TITLE
system/nerdctl: Updated for version 2.0.1

### PR DESCRIPTION
**Pull request by earies**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/nerdctl

**Comment by willysr** [comment]
@earies we have duplicate directories for documentations
can you merge them into single directory ?

**Comment by earies** [comment]
> @earies we have duplicate directories for documentations can you merge them into single directory ?

merged via commit https://github.com/SlackBuildsOrg/slackbuilds/pull/8995/commits/cda9b72aeca5bb427ef99502f5c817dc89d12caf

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
