### PR TITLE
Some updates 

### PR DESCRIPTION
**Pull request by Fellypao**
getdp - updated for version 3.4.0
labplot2 - updated for version 2.8.2
muParser - new maintainer (see: https://lists.slackbuilds.org/pipermail/slackbuilds-users/2021-September/025868.html)
scidavis - just a small update in the build script and fixing a conflict in README

### CODE REVIEW

**Comment by Fellypao** [comment]
Update gmsh for version 4.9.2

**Comment by willysr** [comment]
hi @Fellypao can you rewrite the commit message to use <category>/<script name>: <commit message> format?

**Comment by Fellypao** [comment]
Hi @willysr  I tried to rewrite the commit messages. I'm not sure if it worked for all them. 
And sorry for the inconvenient. I'll do it correctly next time

**Comment by Fellypao** [comment]
Ok. I was able to change the commit messages.
I'm sorry if things look messy. My knowledge about _git_ is very limited.

**Comment by willysr** [comment]
yeah, it become very messy lol

**Comment by willysr** [comment]
try rebasing from master first
use git rebase -i master

**Comment by Fellypao** [comment]
Well... I guess it's better to close this PR and start from beginning tomorrow :)

**Pull request closed without merging**
