### PR TITLE
Merge request

### PR DESCRIPTION
**Pull request by RSKYS**
- Picard: Updated for version 2.7.2.
- PySDL2: Updated for version 0.9.10.
- TauonMB: Updated for version 7.0.1.

### CODE REVIEW

**Comment by willysr** [comment]
hey,

i think you haven't rebased against latest master since tauonmb is at 6.8.3 at master

**Comment by RSKYS** [comment]
Ah,
Btw, that's probably my fork(not official) and I haven't released it there,
7.0.1 is an emergency push tho
A second, I'll fix stuffs

**Comment by RSKYS** [comment]
Hi Willy,
I fixed these
Also updated my releases in fork of repo(will upload bin into releases too)

**Comment by willysr** [comment]
Oh my bad, 6.8.3 update is on my branch, not yet pushed to master

**Comment by RSKYS** [comment]
Yeah, this is unsynced mirror,
Natural to happen

**Comment by RSKYS** [comment]
"willysr" yeah
You always push commits to that branch, before major merges

**Comment by willysr** [comment]
is it ok to rework the patch based on previous PR? or rebased after i merge the changes to master?

**Comment by RSKYS** [comment]
However you're more comfortable!
I just remind that previous PR is for version 6.8.3;
Which is first version that PHAZOR officially adopted pipewire and you get different results compare to pulseaudio.
It has already committed to Willysr, you can combine commits into one directly as version 7.0.1,
or just commit them seperately

**Comment by willysr** [comment]
yeah, but i have to work on it manually since your patch is based on master branch, not my branch
it would be easier if you could wait until i merge them into master then rebase your patch again later

**Comment by RSKYS** [comment]
Can we do it quick then?
I mean update master and I commit
I guesa I have still a bit time before work

**Comment by RSKYS** [comment]
Can I give you some suggestion?
Why don't push "willysr" to this repo, so I can PR to it in these situations?

**Comment by RSKYS** [comment]
Can I give you some suggestion?
Why don't push "willysr" branch of official git to this repo, so I can PR to it in these situations?
(Not like always, only when it's necessary)
Because I don't have access to official git!

**Comment by RSKYS** [comment]
Either way it's fine tbh,
Rebase after you merged the changes to master

**Comment by willysr** [comment]
please rebase to master

**Comment by RSKYS** [comment]
Done

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
