### PR TITLE
development/spyder: Update for 5.4.0 (+new maintainer)

### PR DESCRIPTION
**Pull request by isaackwy**
I don't think Larry Hajali is maintaining SlackBuilds anymore. I have not emailed him this time - the previous time (when I was getting spyder updated to 5.3.1), I emailed him, and he has not responded.

Therefore, I plan on taking over maintenance anyway.
This update fixes the spyder SlackBuild.

The previous pull request for your reference: https://github.com/SlackBuildsOrg/slackbuilds/pull/2491

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/spyder

**Comment by willysr** [comment]
@isaackwy this need another dep?

**Comment by isaackwy** [comment]
I looked at the logs. jellyfish-vendored-sources has not been downloaded on your end. For example:

```
tar: /tmp/SBo/repo.xn2jHA/slackbuild_jellyfish/jellyfish-vendored-sources-1.0.3-2.tar.?z: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

Why did your jellyfish SlackBuild download jellyfish-vendored-sources-1.0.3-2, rather than jellyfish-vendored-sources-1.0.3-1 (that is, build version 2, rather than build version 1)?

**Comment by willysr** [comment]
build 2 is automatically upgraded by the build engine, so no worries about that

**Comment by aclemons** [comment]
Actually thanks for the reminder. I have been meaning to write to fourtysixandtwo and ask him to stop using `BUILD` for the vendoring version of his python builds since they are two separate things and it breaks the CI builds when updated dependencies are found in the CI runs and a rebuild is triggered for it. I'll flick him an email.

**Comment by aclemons** [comment]
I'll reset the jellyfish build and kick off another run

**Comment by aclemons** [comment]
@sbo-bot: build development/spyder

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
