### PR TITLE
gis/gdal: Updated for version 3.9.0.

### PR DESCRIPTION
**Pull request by ArTourter**
Shared library .so-version bump.

Java binding requires JDK 11 or above. Tested with zulu-openjdk (11 & 17) and alien openjdk17.
poppler patch not required with version 3.9.0.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build gis/gdal

**Comment by willysr** [comment]
i think this requires numpy?

**Comment by ArTourter** [comment]
> i think this requires numpy?

Huh! it is just advisable but now they have added a cmake option if one wants to compile without it. OK I'll add it to the list of reqs, check again the java reqs in case it was a red herring and send an update.

**Comment by aclemons** [comment]
@sbo-bot: build i586 gis/gdal

**Comment by ArTourter** [comment]
ok I have added numpy as a dependency. I don't see the point of making that optional or not including it.
I have also checked if the JAVA bindings compile with JDK8 and it does, so I have removed the note in the README file.

**Comment by willysr** [comment]
@sbo-bot: build gis/gdal

**Comment by ArTourter** [comment]
I am really sorry. I will get this right one day!

**Comment by aclemons** [comment]
@sbo-bot: build gis/gdal

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
