### PR TITLE
python/python3-yarl: Updated for version 1.9.11.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-yarl

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-aiohttp

**Comment by aclemons** [comment]
https://pypi.org/project/yarl/#history
https://github.com/aio-libs/yarl/tags

Did 1.10.0 get yanked? I don't see it anywhere here.

**Comment by mac-a-r0ni** [comment]
> https://pypi.org/project/yarl/#history
> 
> https://github.com/aio-libs/yarl/tags
> 
> 
> 
> Did 1.10.0 get yanked? I don't see it anywhere here.

It must have been. It's just been replaced as of 5 minutes ago, but I'd assume the md5 has changed, but I'm not in the position to check ATM. It has reappeared though.

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-aiohttp

**Comment by aclemons** [comment]
Yes, not the same sha tagged now, so I will let you review the changes again and update.

**Comment by mac-a-r0ni** [comment]
Changed back to 1.9 branch as it's the latest listed release on GitHub. It seems 1.10 may need a little more time to bake, so reverting for now.

**Comment by willysr** [comment]
@sbo-bot: build python/python3-yarl

**Comment by willysr** [comment]
@sbo-bot: build python/python3-aiohttp

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
