### PR TITLE
Update python/python3-pdm-build-locked to 0.3.2 & python/python3-pdm to 2.17.1

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm-build-locked

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-cacheyou

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
