### PR TITLE
games/warzone2100: updated for version 4.2.6

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
please rebase from latest master
this patch doesn't apply cleanly

**Comment by Ythogtha** [comment]
Oh, I guess it's because that's the second one I pushed for warzone2100 in a few days, previous one still isn't in master here on github it seems...

**Comment by willysr** [comment]
i have pushed to master here on github...
perhaps you missed it :)

**Comment by Ythogtha** [comment]
That's strange, because when I look there : https://github.com/SlackBuildsOrg/slackbuilds/tree/master/games/warzone2100
I only see the 4.2.4 update, not the 4.2.5, and my PR updates from 4.2.4 to 4.2.6...
And github tells me here that `This branch has no conflicts with the base branch`
What should I do?

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
