### PR TITLE
development/textadept: updated for version 12.1, new maintainer, building from sources

### PR DESCRIPTION
**Pull request by Ythogtha**
I put some work into that one:
 * taking ownership (that's the easy part :smiley:).
 * building from source.
 * downloading third party sources which otherwise would be downloaded during build - I hope this builds fully offline now
 * making a helper script for future management of this mess.
 * building HTML version of markdown documentation, since the local HTML files are used byt the application itself to open things from the help menu - that wasn't easy, I had to hit the code pretty hard to have something functional.
 * package all that nicely...
 
Let's hope it'll pass all the checks ;)

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build development/textadept

**Comment by Ythogtha** [comment]
Found the problem, re-pushing...

**Comment by Ythogtha** [comment]
@sbo-bot: obey my command, you machine !

*sigh* doesn't listen to me apparently, might be because of my awful french accent...

**Comment by aclemons** [comment]
@sbo-bot: build development/textadept

**Comment by Ythogtha** [comment]
Ah, I've been able to reproduce that error, and fix it.
Well, instead of adding lua as build-time requirement, since textadept takes great length to not depend on installed lua but to ship its own, I build the internal lua, and uses it for building docs.

Should be ok, :crossed_fingers:

**Comment by aclemons** [comment]
@sbo-bot: build development/textadept

**Comment by aclemons** [comment]
Ok, that built, but looks like it is not using DESTDIR etc for the install?

**Comment by Ythogtha** [comment]
Well, the build/install process really wants to make a bundle.
It is using the /usr prefix, but putting everything in /usr/share/textadept.
So I used symbolic links for binaries and desktop files.
Maybe I should mv them.
I'll try that and if the resulting package works as expected, I'll push this change.

**Comment by Ythogtha** [comment]
Well, after testing, it turns out that binaries expect to be in the same repository as other data like init.lua.
So using symbolic links in /usr/bin is the way to go.
I'll keep it as-is, I don't want to alter too much how textadept does things, we might run into bad side-effects.

Previous script was using pre-built binaries in /opt/textadept/ and symbolic links in /usr/bin/
I like mine better because it builds from sources, even if complexity follows ^^

**Comment by aclemons** [comment]
Ok merging this - the cmake install puts some symlinks on the build host, but they don't actually point to anything. The rest of the stuff goes into the package as it should, so it is mostly ok, just puts some rubbish on the build host.

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
