### PR TITLE
network/opensmtpd-extras: Added - Table backends (SQLite...) for Open…

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
Hmm, I can do better with the script, please don't merge for now.

**Comment by willysr** [comment]
new submission should go through normal submission form. You can't request a PR for this :)

**Comment by willysr** [comment]
Also, don't forget to include maintainer's information in the .info file

**Comment by Ythogtha** [comment]
> new submission should go through normal submission form. You can't request a
> PR for this :)

Oh, ok, so here it will soon go !

> Also, don't forget to include maintainer's information in the .info file

Thanks, missed that...

-- 
Arnaud <yth@ythogtha.org>

**Pull request closed without merging**
