### PR TITLE
system/catatonit: Updated for version 0.2.0-2.

### PR DESCRIPTION
**Pull request by kovmir**
Fix wrong filename for `tar` command.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/catatonit

**Comment by willysr** [comment]
@kovmir this failed to extract the source

**Comment by kovmir** [comment]
Oh my machine it failed to extract the source prior to the latest commit.

**Comment by willysr** [comment]
Somehow it works on previous build
https://github.com/SlackBuildsOrg/slackbuilds/pull/4050

**Comment by kovmir** [comment]
Would you try to build it on your computer, I don't know...

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
it seems your URL is incorrect
it should be https://github.com/openSUSE/catatonit/archive/v0.2.0/catatonit-0.2.0.tar.gz
i fixed it on my branch but it will be merged next week

**Comment by kovmir** [comment]
Thanks.

**Pull request closed without merging**
