### PR TITLE
libraries/openvino: Include ittapi.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build libraries/openvino

**Comment by willysr** [comment]
i think you need to cherry-pick this commit https://git.slackbuilds.org/slackbuilds/commit/?h=willysr&id=8fd926d26520093eab246e5857020bd5abc3556b

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 libraries/openvino

**Review by aclemons — COMMENTED** [review]
LGTM

**Pull request merged**
