### PR TITLE
network/glewlwyd: updated for version 2.7.1

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
staged to my branch, thanks

**Comment by aclemons** [comment]
Actually, the i?86 build failed (x86_64) is fine. Can you check please?

```
          --- LOG END ---
          error: downloading 'https://github.com/babelouest/yder/archive/v1.4.17.tar.gz' failed
          status_code: 6
          status_string: "Couldn't resolve host name"
          log:
          --- LOG BEGIN ---
          Could not resolve host: github.com

gmake[2]: *** [CMakeFiles/yder-download.dir/build.make:99: yder-download-prefix/src/yder-download-stamp/yder-download-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/yder-download.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
CMake Error at cmake-modules/DownloadProject.cmake:179 (message):
  Build step for yder failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:197 (download_project)
 ```

It is trying to download another dependency?

**Comment by aclemons** [comment]
The version in the repo works on i?86 without problem.

**Comment by Ythogtha** [comment]
Maybe it needs the updated version of yder.
There is a PR for that too, and it bumps the version to 1.4.17.
I'll look into ix86 anyway.

**Comment by aclemons** [comment]
Great, I will check again tonight with the updated yder.

**Comment by Ythogtha** [comment]
So, I've recreated a VM with slackware 15.0 32bit.
And everything built fine.
I guess the problem really was to upgrade yder before trying to upgrade glewlwyd.
Can you test with updated versions of yder at least and probably iddawc, rhnoabwy and hoel ?
I should have made one PR for all of them, and not separate.

**Comment by aclemons** [comment]
confirmed with the new yder, hoel, rhonabwy and iddawc this now buids on i?86

**Pull request closed without merging**
