### PR TITLE
system/pv: md5sum update 

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
Seems upstream changed the file since I merged #3057. I still have the cached file with the matching md5sum from when I built it previously.

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
staged to my branch

**Comment by Ythogtha** [comment]
Yes, they changed very little, two lines in metainfos of polish and portuguese translations.
md5sum changed.
Let's hope it won't move again...

**Pull request closed without merging**
