### PR TITLE
development/composer: Updated for version 1.6.3

### PR DESCRIPTION
**Pull request by belka-ew**

### CODE REVIEW

**Comment by willysr** [comment]
@belka-ew why include compose.phar as part of the SlackBuild script? Source should not be part in GIT

**Comment by belka-ew** [comment]
Sorry, I'll fix it in a second

**Comment by belka-ew** [comment]
Oh, this commit is correct. composer.phar is in master. It is deleted by this commit. I did the mistake by my previous update. Sorry.

**Comment by belka-ew** [comment]
Any chance to get `*.phar` in .gitignore?

**Comment by willysr** [comment]
yes, it's possible to do that. I'll add it to .gitignore

merged

**Pull request closed without merging**
