### PR TITLE
ham/liquid-dsp: Updated for version 1.6.0.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build ham/liquid-dsp

**Comment by willysr** [comment]
@sbo-bot: build ham/CubicSDR

**Comment by willysr** [comment]
@sbo-bot: build ham/inspectrum

**Comment by willysr** [comment]
@sbo-bot: build ham/redsea

**Comment by willysr** [comment]
@pyllyukko this script install in /lib{64} instead of /usr/lib{64}
this is caused by this line
https://github.com/SlackBuildsOrg/slackbuilds/blob/a6b7ce4ae019fc574e7c97cdf7dae2b7a94fb1be/ham/liquid-dsp/liquid-dsp.SlackBuild#L85 (extra / in front)

**Comment by willysr** [comment]
@sbo-bot: build ham/liquid-dsp

**Comment by pyllyukko** [comment]
> @pyllyukko this script install in /lib{64} instead of /usr/lib{64}

Good catch. Fixed.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
