### PR TITLE
perl/perl-PDF-API2: Updated for version 2.045

### PR DESCRIPTION
**Pull request by mab974**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-PDF-API2

**Comment by willysr** [comment]
@mab974 this is missing dependency

**Comment by mab974** [comment]
add missing Test::Exception
oddly not missing for me !??
perl-PDF-API2 not needed anymore just keeping it uptodate

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-PDF-API2

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
