### PR TITLE
games/endless-sky: updated for version 0.10.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
```
# buildpkg i586 games/endless-sky
sbolint: endless-sky checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Thu Mar  2 21:54:49 GMT 2023
revision: 51e6912a2d689e3b086ad3255913749b846f838b
title:    games/endless-sky: Updated for version 0.10.0.

================================================================================
games/endless-sky                                                       21:55:28
================================================================================

Calculating dependencies ... none.

Building games/endless-sky (update for version 0.10.0) ---------------- 21:55:28
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running endless-sky.SlackBuild ...                                  ETA 21:59:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./endless-sky.SlackBuild
Build time 311 sec, peak load 1.50, peak memory 1762M, peak tmp 720M
Built ok:  endless-sky-0.10.0-i586-1_SBo.txz                            22:00:50
Testing package endless-sky-0.10.0-i586-1_SBo.txz ... done.
Test installing endless-sky-0.10.0-i586-1_SBo.txz ...
endless-sky-0.10.0-i586-1_SBo: 2D space trading and combat game ........ [ 267M]
Unmounting chroot ... done.
Backed up: endless-sky-0.9.16.1-i586-1_SBo.txz
:-) games/endless-sky Updated for version 0.10.0 (-:

================================================================================
SUMMARY                                                                 22:01:39
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-02_21:55:27.log
Runtime:     0h 6m 12s
Updated:     1
  games/endless-sky/endless-sky-0.10.0-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/games/endless-sky/endless-sky-0.10.0-i586-1_SBo.txz to /tmp/sbopkglint.S89kI7 ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/games/endless-sky/endless-sky-0.10.0-i586-1_SBo.txz to /tmp/sbopkglint.S89kI7 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...usr/share/applications/endless-sky.desktop: error: value "1.5" for key "Version" in group "Desktop Entry" is not a known version
usr/share/applications/endless-sky.desktop: error: file contains key "SingleMainWindow" in group "Desktop Entry", but keys extending the format should start with "X-"

--- .desktop files fail to validate:
-rw-r--r-- 1 root root 361 Feb 19 21:37 usr/share/applications/endless-sky.desktop
FAILED
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! endless-sky-0.10.0-i586-1_SBo.txz: 1 failures
```

**Comment by aclemons** [comment]
sbopkglint complained about the desktop file. Are these worth fixing?

**Comment by Ythogtha** [comment]
This file comes from upstream sources, unmodified.
It works fine, and desktop (at least xfce) doesn't complain.
I don't really know what these options are supposed to mean, or if they serve any kind of purpose, but I don't think its worth fixing.
Maybe I'll signal it upstream, see if what they think.

**Comment by Ythogtha** [comment]
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
Here I can find this phrase :

> Version of the Desktop Entry Specification that the desktop entry conforms with.
> Entries that confirm with this version of the specification should use 1.5.
> Note that the version field is not required to be present.

Also the keys PrefersNonDefaultGPU and SingleMainWindow are part of the specification on this page.

Maybe the linter is wrong for desktop files ?
It seems this one does follow the specifications.

**Comment by aclemons** [comment]
LGTM - staged to my branch

**Pull request closed without merging**
