### PR TITLE
Red/master

### PR DESCRIPTION
**Pull request by RSKYS**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build office/lowdown

**Comment by willysr** [comment]
@sbo-bot: build development/mdbook

**Comment by willysr** [comment]
@sbo-bot: build python/python3-plexapi

**Comment by willysr** [comment]
@RSKYS mdbook failed to build here

**Comment by RSKYS** [comment]
I see, maybe mdbook needs newer cargo/rust
Let me have a brief look again
Can I also use sbo-bot for test building here too?

**Comment by willysr** [comment]
unfortunately no, only some people are allowed to run those command

**Comment by RSKYS** [comment]
> unfortunately no, only some people are allowed to run those command

No problem, hope to make it to some one day
Try new push of mdbook, I've changed nothing else

**Comment by RSKYS** [comment]
Ah actually still in progress, let me draft this for now

**Comment by willysr** [comment]
@sbo-bot: build development/mdbook

**Comment by RSKYS** [comment]
There's absolutely no reason why Cargo.toml can't be parsed..
Tried different workspace, tried to generated same error and situation, Cargo.toml is literally at the source it switches to

**Comment by RSKYS** [comment]
Added it rust16 as dependency.

**Comment by RSKYS** [comment]
@willysr Please try to build development/mdbook now
Thanks

**Comment by willysr** [comment]
@sbo-bot: build development/mdbook

**Comment by willysr** [comment]
@RSKYS latest commit works, do you want to delete it?

**Comment by willysr** [comment]
merged

**Comment by RSKYS** [comment]
Yeah I wanted to merge it with it's previous commit
Is it needed now?

**Comment by RSKYS** [comment]
Ah you did already on your branch, thanks

**Pull request closed without merging**
