### PR TITLE
perl/perl-http-message: Updated for version 6.45.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-message

**Comment by willysr** [comment]
@pyllyukko this requires a lot of new deps

**Comment by pyllyukko** [comment]
> @pyllyukko this requires a lot of new deps

I'll check those during the weekend and update into this PR.

**Comment by pyllyukko** [comment]
@sbo-bot: build perl/perl-http-message

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-message

**Comment by willysr** [comment]
same goes here, perl-test-need is needed or try removing make test

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-message

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
