### PR TITLE
development/hare: Upgrade to 0.24.2.

### PR DESCRIPTION
**Pull request by henesy**
talked to Dave, he said it was fine to take over

### CODE REVIEW

**Comment by henesy** [comment]
Note the build order here after upgrade is qbe -> harec -> hare

**Comment by willysr** [comment]
@sbo-bot: build development/hare

**Comment by willysr** [comment]
@sbo-bot: build development/hare

**Comment by henesy** [comment]
@willysr I think this one got dropped

Not sure why the above failed, but qbe and harec made it in the last web update so this should be able to build against master without any issues

**Comment by willysr** [comment]
Ups, my bad
I will merge it on my branch soon

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
