### PR TITLE
system/intelmas: Update for 2.3

### PR DESCRIPTION
**Pull request by wsdookadr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/intelmas

**Comment by willysr** [comment]
@wsdookadr you forgot to update the MD5SUM

**Comment by wsdookadr** [comment]
> @wsdookadr you forgot to update the MD5SUM

you're right, I just pushed an update now

**Comment by willysr** [comment]
@sbo-bot: build system/intelmas

**Comment by willysr** [comment]
merge

**Pull request closed without merging**
