### PR TITLE
network/discord: Version bump to 0.0.50

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 network/discord

**Comment by willysr** [comment]
merged

**Comment by bassmadrigal** [comment]
@sbo-bot: build x86_64 network/discord

**Comment by bassmadrigal** [comment]
@aclemons 

Attempted here (figure it should be easy since it doesn't face dependencies).

**Comment by aclemons** [comment]
Ok, it looks like it is working (build will fail though since the PR is closed). Thanks!

**Pull request closed without merging**
