### PR TITLE
network/microsoft-edge: Updated for version 127.0.2651.86.

### PR DESCRIPTION
**Pull request by RezaT4795**

### CODE REVIEW

**Comment by willysr** [comment]
this maintainer is still active i think, so you need to make sure you get in touch with him

**Comment by aclemons** [comment]
should be fine:

https://lists.slackbuilds.org/pipermail/slackbuilds-users/2023-November/028685.html

**Comment by willysr** [comment]
@sbo-bot: build network/microsoft-edge

**Comment by aclemons** [comment]
@RezaT4795 You might want to update the readme for this update, noting the caveats. edge does not start since it requires /etc/machine-id. This was also previously discussed on LQ:

https://www.linuxquestions.org/questions/linux-software-2/unable-to-launch-microsof-edge-on-slackware-4175730225/page2.html#post6469084

https://www.linuxquestions.org/questions/slackware-14/file-etc-machine-id-not-found-pros-cons-4175734868/#post6491158

**Comment by willysr** [comment]
@RezaT4795 i think you need to adjust doinst.sh

`WARNING: network/microsoft-edge: usr/share/icons/hicolor in doinst.sh but not in package`

**Pull request closed without merging**
