### PR TITLE
system/nix: Updated to 2.16.1.

### PR DESCRIPTION
**Pull request by RSKYS**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by RSKYS** [comment]
May I push 2.17.1 too?
If you haven't merged still

**Comment by RSKYS** [comment]
I'll push 2.17.1 too, you can decide to merge it or not.
I wanted their testing to be seperated, but if I push later this week, I might encounter with conflicts.

**Comment by willysr** [comment]
sure

**Comment by willysr** [comment]
@sbo-bot: build system/nix

**Comment by willysr** [comment]
Why do we have these directories?
 ./nix/var/nix/daemon-socket
 ./nix/var/nix/profiles
/dummy
/dummy/.nix-profile
/dummy/profiles
/dummy/profiles/default
/dummy/profiles/per-user
/dummy/profiles/per-user/root

**Comment by RSKYS** [comment]
./nix/var/nix/daemon-socket directory contains the socket for the Nix daemon, linked with rc here most likely.
./nix/var/nix/profiles directory holds system-wide profile of users for Nix, allowing upgrades and rollbacks per each.
/dummy directory is a place holder for user-specific configurations in Nix.
/dummy/.nix-profile directory contains active profile for a user, linking to package installations in the Nix store.
/dummy/profiles directory manages multiple user profiles for the users on domain.
/dummy/profiles/default directory contains /dummy user profile with symlinks to installed packages.
/dummy/profiles/per-user directory would hold profiles for individual users in the /dummy context.
And /dummy/profiles/per-user/root subdirectory manages profiles for the root user independently.

**Comment by willysr** [comment]
merged

**Comment by RSKYS** [comment]
But these should get build after running nix, are they getting generated only by running nix.SlackBuild?
If so, I should think and investigate code for more possible hard corrections..

**Comment by RSKYS** [comment]
Seems the very first patch need more updates.. they have terrible coders.

**Comment by RSKYS** [comment]
Please don't tell me that build process just spammed root partition..
I'll send you updated patch before saturday, you can commit it on my behalf or let me commit it myself.. I'm so sorry if this happened.

**Pull request closed without merging**
