### PR TITLE
network/whalebird: Updated for version 6.0.2.

### PR DESCRIPTION
**Pull request by antonioleal**
network/whalebird: Updated for version 6.0.2.

with corrected checksum...

### CODE REVIEW

**Comment by isaackwy** [comment]
Hi Antonio.

You actually haven't fixed/changed the checksum yet.
Under the line MD5SUM_x86_64:
Please change the checksum to fe3b6f1fcf5b674247080e5b825bf83b.

Thanks.

You can simply rebase your branch and edit .info there:
```
git checkout whalebird
git rebase -i HEAD~1
# After editing whalebird.info
git add whalebird.info
git commit --amend
git rebase --continue
git push origin whalebird -f
```

**Comment by antonioleal** [comment]
This one gave this

~/slackware-builds/antonioleal/slackbuilds/network/whalebird$ git rebase --continue
fatal: No rebase in progress?

But in here I can see the fix. Hope is ok.

Learned something today :-)

**Comment by willysr** [comment]
@sbo-bot: build network/whalebird

**Comment by willysr** [comment]
you issue git rebase --continue if you ran git rebase -i master previously
if you never ran git rebase before, there's no need to run git rebase --continue

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
