### PR TITLE
libraries/process-cpp: Version bump to 3.0.2

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build libraries/process-cpp

**Comment by bassmadrigal** [comment]
@sbo-bot: build  libraries/dbus-cpp

**Comment by bassmadrigal** [comment]
@sbo-bot: build libraries/dbus-cpp

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
