### PR TITLE
libraries/libgit2: Updated to 1.8.1 + new maintainer

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
We already talked about this; it's been 3 weeks since I've sent an email and according to your saying he seems to be inactive.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build libraries/libgit2

**Comment by willysr** [comment]
@sbo-bot: build development/kicad

**Comment by willysr** [comment]
@sbo-bot: build graphics/fritzing

**Comment by willysr** [comment]
@sbo-bot: build libraries/libgit2-glib

**Comment by willysr** [comment]
@sbo-bot: build misc/subsurface

**Comment by willysr** [comment]
@RSKYS do you mind taking over libgit2-glib as well? it failed to build with latest libgit2 so i think it's better if you take over and fix it as well

**Comment by RSKYS** [comment]
It's okay, I'll look into it a bit later

**Comment by RSKYS** [comment]
Okay, please test!

**Comment by willysr** [comment]
@sbo-bot: build libraries/libgit2

**Comment by willysr** [comment]
@sbo-bot: build libraries/libgit2-glib

**Comment by willysr** [comment]
@sbo-bot: build development/gnome-builder

**Comment by willysr** [comment]
@RSKYS can you enable SSH support on libgit2? 
it seems gnome-builder requires it

**Comment by RSKYS** [comment]
Sure, I'm gonna update it in few hours

**Comment by RSKYS** [comment]
There, please check if it's fixed.

**Comment by willysr** [comment]
@sbo-bot: build development/gnome-builder

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
