### PR TITLE
Buildbot

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
@sbo-bot: build buildbot

**Comment by Ythogtha** [comment]
@sbo-bot: build buildbot-worker

**Comment by Ythogtha** [comment]
@sbo-bot: build buildbot-badges

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot python/buildbot -worker python/buildbot-badges

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot
@sbo-bot: build python/buildbot -worker
@sbo-bot: build python/buildbot-badges

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot -worker

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot-badges

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot -worker

**Comment by Ythogtha** [comment]
@sbo-bot: build python/buildbot-worker

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
