### PR TITLE
system/openrc: Updated for version 0.55.

### PR DESCRIPTION
**Pull request by RezaT4795**

### CODE REVIEW

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
@sbo-bot: build system/openrc

**Comment by aclemons** [comment]
@RezaT4795 Can you check on this? Seems it is installing into `/libexec` instead of `/usr/libexec`?


It does seem like the previous version was also this way:

```sh
sbopkglint openrc-0.54.2-x86_64-2_SBo.txz
Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding openrc-0.54.2-x86_64-2_SBo.txz to /tmp/SBo/sbopkglint.e5nQwt ...OK
Running pre-doinst test...OK
Installing openrc-0.54.2-x86_64-2_SBo.txz to /tmp/SBo/sbopkglint.e5nQwt ...OK
Running test: 05-basic-sanity...
--- package root dir contains non-standard directory: libexec
FAILED
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
Running test: 60-usr_info...OK
Running test: 65-python...OK
Running test: 70-tmp_path...OK
Running test: 75-static_libs...OK
Running test: 85-perl...OK
Running test: 90-terminfo...OK
!!! openrc-0.54.2-x86_64-2_SBo.txz: 1 failures
```

**Comment by RezaT4795** [comment]
@aclemons Fixed in #8339

**Pull request closed without merging**
