### PR TITLE
nextcloud-desktop: update 3.14.1

### PR DESCRIPTION
**Pull request by afhpayne**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build network/nextcloud-desktop

**Comment by aclemons** [comment]
This can be closed now @afhpayne? After 5e48347 there is no change from master.

**Comment by willysr** [comment]
he reverted back, so i guess it has some issues. I will close this one for now

**Comment by afhpayne** [comment]
@willysr and @aclemons yes, sorry this one is a no-go for now, having a dependency issue since NC moved to qt6.

**Pull request closed without merging**
