### PR TITLE
ham/inspectrum: Updated for version 0.3.1.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build ham/inspectrum

**Comment by willysr** [comment]
@pyllyukko you forgot to change the MD5SUM

**Comment by pyllyukko** [comment]
> @pyllyukko you forgot to change the MD5SUM

Yup. Fixed.

**Comment by willysr** [comment]
@sbo-bot: build ham/inspectrum

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
