### PR TITLE
development/google-go-lang: Updated for version 1.23.4.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
I've checked all my golang builds with this. Backwards compatibility is generally very good with go, but I have not yet built all golang script in the repo with it. We can also wait until after this week's update to merge.

**Comment by willysr** [comment]
yeah, it's a bit risky with golang, so i wil wait until this week's public update

**Comment by willysr** [comment]
@sbo-bot: build development/google-go-lang

**Comment by willysr** [comment]
@sbo-bot: build network/XD

**Comment by willysr** [comment]
@sbo-bot: build audio/Ymuse

**Comment by willysr** [comment]
@sbo-bot: build desktop/fvwm3

**Comment by willysr** [comment]
@sbo-bot: build desktop/gopsuinfo

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-bar

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-drawer

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-look

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-menu

**Comment by willysr** [comment]
@sbo-bot: build development/actionlint

**Comment by willysr** [comment]
@sbo-bot: build development/golang-googlecode-gonet

**Comment by willysr** [comment]
@sbo-bot: build development/golangci-lint

**Comment by willysr** [comment]
@sbo-bot: build development/gopls

**Comment by willysr** [comment]
@sbo-bot: build development/hub

**Comment by willysr** [comment]
@sbo-bot: build development/nvidia-container-toolkit

**Comment by willysr** [comment]
@sbo-bot: build development/opentofu

**Comment by willysr** [comment]
@sbo-bot: build development/protoc-gen-go

**Comment by willysr** [comment]
@sbo-bot: build development/terraform

**Comment by willysr** [comment]
@sbo-bot: build development/terraform-ls

**Comment by willysr** [comment]
@sbo-bot: build development/tflint

**Comment by willysr** [comment]
@sbo-bot: build misc/cheat

**Comment by willysr** [comment]
@sbo-bot: build misc/cliphist

**Comment by willysr** [comment]
@sbo-bot: build misc/go-md2man

**Comment by willysr** [comment]
@sbo-bot: build network/aerc

**Comment by willysr** [comment]
@sbo-bot: build network/bombadillo

**Comment by willysr** [comment]
@sbo-bot: build network/cni-plugins

**Comment by willysr** [comment]
@sbo-bot: build network/go-sendxmpp

**Comment by willysr** [comment]
@sbo-bot: build network/goimapnotify

**Comment by willysr** [comment]
@sbo-bot: build network/nchat

**Comment by willysr** [comment]
@sbo-bot: build network/node_exporter

**Comment by willysr** [comment]
@sbo-bot: build network/senpai

**Comment by willysr** [comment]
@sbo-bot: build network/sshamble

**Comment by willysr** [comment]
@sbo-bot: build network/ssllabs-scan

**Comment by willysr** [comment]
@sbo-bot: build network/tut

**Comment by willysr** [comment]
@sbo-bot: build network/webhook

**Comment by willysr** [comment]
@sbo-bot: build network/wego

**Comment by willysr** [comment]
@sbo-bot: build network/zabbix_agent2

**Comment by willysr** [comment]
@sbo-bot: build network/zdns

**Comment by willysr** [comment]
@sbo-bot: build office/msee

**Comment by willysr** [comment]
@sbo-bot: build office/trello-cli

**Comment by willysr** [comment]
@sbo-bot: build system/apptainer

**Comment by willysr** [comment]
@sbo-bot: build system/docker-buildx

**Comment by willysr** [comment]
@sbo-bot: build system/docker-machine

**Comment by willysr** [comment]
@sbo-bot: build system/docker-proxy

**Comment by willysr** [comment]
@sbo-bot: build system/fzf

**Comment by willysr** [comment]
@sbo-bot: build system/go-mtree

**Comment by willysr** [comment]
@sbo-bot: build system/incus

**Comment by willysr** [comment]
@sbo-bot: build system/kbfs

**Comment by willysr** [comment]
@sbo-bot: build system/kitty

**Comment by willysr** [comment]
@sbo-bot: build system/lf

**Comment by willysr** [comment]
@sbo-bot: build system/local-persist

**Comment by willysr** [comment]
@sbo-bot: build system/mongo-tools

**Comment by willysr** [comment]
@sbo-bot: build system/netdata

**Comment by willysr** [comment]
@sbo-bot: build system/runc

**Comment by willysr** [comment]
@sbo-bot: build system/sargon

**Comment by willysr** [comment]
@sbo-bot: build system/slack-osquery

**Comment by willysr** [comment]
@sbo-bot: build system/yq

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
