### PR TITLE
network/teamviewer: Updated for version 15.36.8.

### PR DESCRIPTION
**Pull request by ArTourter**
Signed-off-by: ArTourter <artourter@gmail.com>

### CODE REVIEW

**Comment by ArTourter** [comment]
This PR is to replace the previously submitted PR to update to version 15.36.6.
It is created on top of the master branch not my previous change.

**Comment by willysr** [comment]
the previous PR has been merged

**Comment by ArTourter** [comment]
@willysr  how do you want me to proceed. Teamviewer very rarely release small point release that closely so the assumption is that 15.36.6 is broken in some ways, hence the new 15.36.8.
Do you want me to base the new one on the previous PR?

**Comment by willysr** [comment]
pushed to my branch

**Pull request closed without merging**
