### PR TITLE
development/rust16: Updated for version 1.80.1.

### PR DESCRIPTION
**Pull request by pghvlaans**
WIP until everything builds.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/rust16

**Comment by willysr** [comment]
@sbo-bot: build audio/ncspot

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by willysr** [comment]
@sbo-bot: build desktop/leftwm

**Comment by willysr** [comment]
@sbo-bot: build development/cargo-c

**Comment by willysr** [comment]
@sbo-bot: build development/cargo-vendor-filterer

**Comment by willysr** [comment]
@sbo-bot: build development/lean-elan

**Comment by willysr** [comment]
@sbo-bot: build development/mdbook

**Comment by willysr** [comment]
@sbo-bot: build development/rustup

**Comment by pghvlaans** [comment]
I was cleaning out my merged branches and accidentally deleted this one, too. It's back now. Sorry about that!

**Comment by willysr** [comment]
@sbo-bot: build graphics/veles

**Comment by willysr** [comment]
@sbo-bot: build network/newsboat

**Comment by willysr** [comment]
@sbo-bot: build network/noip-duc

**Comment by willysr** [comment]
@sbo-bot: build office/navi

**Comment by willysr** [comment]
@sbo-bot: build python/python3-bcrypt

**Comment by willysr** [comment]
@sbo-bot: build python/python3-maturin

**Comment by willysr** [comment]
@sbo-bot: build system/alacritty

**Comment by willysr** [comment]
@sbo-bot: build system/bat

**Comment by willysr** [comment]
@sbo-bot: build system/bottom

**Comment by willysr** [comment]
@sbo-bot: build system/clamav

**Comment by willysr** [comment]
@sbo-bot: build system/dust

**Comment by willysr** [comment]
@sbo-bot: build system/fd

**Comment by willysr** [comment]
@sbo-bot: build system/greetd

**Comment by willysr** [comment]
@sbo-bot: build system/helvum

**Comment by willysr** [comment]
@sbo-bot: build system/hyperfine

**Comment by willysr** [comment]
@sbo-bot: build system/onefetch

**Comment by willysr** [comment]
@sbo-bot: build system/ripgrep

**Comment by willysr** [comment]
@sbo-bot: build system/skim

**Comment by willysr** [comment]
@sbo-bot: build system/tzupdate

**Comment by willysr** [comment]
@sbo-bot: build system/wezterm

**Pull request closed without merging**
