### PR TITLE
proj updates

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build gis/proj

**Comment by aclemons** [comment]
@sbo-bot: build gis/proj-data

**Comment by aclemons** [comment]
@sbo-bot: build gis/python3-pyproj

**Comment by willysr** [comment]
@ArTourter the last commit failed to build

**Comment by willysr** [comment]
@sbo-bot: build gis/python3-pyproj

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
