### PR TITLE
Buildbot

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot-badges

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot

**Comment by willysr** [comment]
@Ythogtha buildbot checksum is incorrect

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot-badges

**Comment by willysr** [comment]
@sbo-bot: build python/buildbot

**Comment by Ythogtha** [comment]
Sorry, I made a mess, I tried to build from github sources, but it was more complicated, so I falled back to the previous way of doing things.
But half-way, with a wrong source package locally.

It should be fixed now, hopefully.

**Pull request closed without merging**
