### PR TITLE
multimedia/amarok: Updated for version 3.1.0.

### PR DESCRIPTION
**Pull request by RezaT4795**
I would have sent it via the submission form, but the website is giving me this error:
"File exists; a submission by the name 'amarok' is already pending approval."
Amarok was dead for 6 years and now it gets updated before my submission of the previous update gets merged :D

### CODE REVIEW

**Comment by willysr** [comment]
https://git.slackbuilds.org/slackbuilds/commit/?id=73d5af3fb
either you need to make PR based on your previous submission or wait until next week

**Comment by RezaT4795** [comment]
> either you need to make PR based on your previous submission

How can I do this?

**Comment by RezaT4795** [comment]
@willysr 
> either you need to make PR based on your previous submission

How can I do this?

**Comment by willysr** [comment]
you need to cherry-pick my commit which approves your original submission and then push PR based on it

**Pull request closed without merging**
