### PR TITLE
python/python3-platformdirs: Fix building on -current

### PR DESCRIPTION
**Pull request by bassmadrigal**
Thanks to @fourtysixand2 for the nudge.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/python3-platformdirs

**Comment by willysr** [comment]
current moves to 3.11
this will fail to build for sure

**Comment by bassmadrigal** [comment]
Why would this fail on -current? The 3.9 reference is only to grab the setuptools-scm in /opt/ on 15.0. It should still be able to reference the tools in the normal location, right?

**Comment by willysr** [comment]
You need to use dynamic python version detection instead of hard-coding it as 3.9 as current move python3 to python3 3.11

**Comment by willysr** [comment]
i fixed it and merged it

**Pull request closed without merging**
