### PR TITLE
audio/bitwig-studio: Updated for version 5.1.9

### PR DESCRIPTION
**Pull request by noisecode3**
I guess you can just take bitwig-studio update. and I think you CI have some limit or something wrong with handling the link, but that download link was changed on the website. I works for me to?

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build audio/bitwig-studio

**Comment by willysr** [comment]
i think it's caused by the redirection made by upstream
I tried to download via wget and it gives me https://downloads-secure.bitwig.com/5.1.9/bitwig-studio-5.1.9.deb?__token__=st=1717485143.0~exp=1717485743.0~hmac=991ab8d42bed2ad17e28eb8a28701a36d96b91380ecafb2cfa1c46d4402729e8&source_url=/dl/Bitwig%20Studio/5.1.9/installer_linux/

**Comment by noisecode3** [comment]
A redirection like that seems harmless to me, its the right md5sum. Will it work with sbopkg and the others?

**Comment by aclemons** [comment]
Let me try adding a hint for this one. I get the same filename (`bitwig-studio-5.1.9.deb`) with a browser clicking the link and with wget when not using `--content-disposition` so users of sbopkg and users who simply download from the website should get the same filename.

**Comment by aclemons** [comment]
@sbo-bot: build audio/bitwig-studio

**Comment by aclemons** [comment]
Looks good with sbopkg too:

```sh
root@73f81c070419:~# sbopkg -b bitwig-studio

###########################################
       New queue process started on:
       Tue Jun  4 10:43:14 GMT 2024
###########################################

+++++++++++++++++++++++++++++++++++++++++++
PRE-CHECK LOG
Using the SBo master git branch
Queue Process:  Download and build

bitwig-studio:
  GPG checks not supported for the SBo repository.
  Processing bitwig-studio 5.1.9-1
  Using original .info file
  Using original SlackBuild file
  No build options selected.

+++++++++++++++++++++++++++++++++++++++++++

Pre-check complete.

Do you wish to proceed based on the search results above? Packages not
found will be skipped during the process.

(P)roceed or (Q)uit?: p


Processing bitwig-studio

bitwig-studio:
bitwig-studio not found in /var/cache/sbopkg.
--2024-06-04 10:43:16--  https://www.bitwig.com/dl/Bitwig%20Studio/5.1.9/installer_linux/bitwig-studio-5.1.9.deb
Resolving www.bitwig.com (www.bitwig.com)... 185.31.213.113
Connecting to www.bitwig.com (www.bitwig.com)|185.31.213.113|:443... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: https://www.bitwig.com/dl/Bitwig%20Studio/5.1.9/installer_linux/bitwig-studio-5.1.9.deb/ [following]
--2024-06-04 10:43:16--  https://www.bitwig.com/dl/Bitwig%20Studio/5.1.9/installer_linux/bitwig-studio-5.1.9.deb/
Reusing existing connection to www.bitwig.com:443.
HTTP request sent, awaiting response... 302 FOUND
Location: https://downloads-secure.bitwig.com/5.1.9/bitwig-studio-5.1.9.deb?__token__=st=1717497796.0~exp=1717498396.0~hmac=d0477ac8b8c97773fd1c721b7fe36deda99c71947e249b45d1db0017ff95d5a9&source_url=/dl/Bitwig%20Studio/5.1.9/installer_linux/ [following]
--2024-06-04 10:43:16--  https://downloads-secure.bitwig.com/5.1.9/bitwig-studio-5.1.9.deb?__token__=st=1717497796.0~exp=1717498396.0~hmac=d0477ac8b8c97773fd1c721b7fe36deda99c71947e249b45d1db0017ff95d5a9&source_url=/dl/Bitwig%20Studio/5.1.9/installer_linux/
Resolving downloads-secure.bitwig.com (downloads-secure.bitwig.com)... 184.51.252.151, 184.51.252.160, 2001:2030:21::3e73:fc7a, ...
Connecting to downloads-secure.bitwig.com (downloads-secure.bitwig.com)|184.51.252.151|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 295797684 (282M) [application/octet-stream]
Saving to: ‘bitwig-studio-5.1.9.deb’

bitwig-studio-5.1.9 100%[===================>] 282.09M  59.4MB/s    in 5.4s

2024-06-04 10:43:22 (52.2 MB/s) - ‘bitwig-studio-5.1.9.deb’ saved [295797684/295797684]

Found bitwig-studio-5.1.9.deb in /var/cache/sbopkg.
Checking MD5SUM:
  MD5SUM check for bitwig-studio-5.1.9.deb ... OK
Building package for bitwig-studio...
[...]
Slackware package /tmp/sbopkg.52pQFc/sbopkg-sbooutputdir/bitwig-studio-5.1.9-x86_64-1_SBo.tgz created.

Done building package for bitwig-studio.
Built package: bitwig-studio-5.1.9-x86_64-1_SBo.tgz

+++++++++++++++++++++++++++++++++++++++++++
SUMMARY LOG
Using the SBo master git branch
Queue Process:  Download and build

bitwig-studio:
  MD5SUM check for bitwig-studio-5.1.9.deb ... OK
  Building package bitwig-studio-5.1.9-x86_64-1_SBo.tgz ... OK

+++++++++++++++++++++++++++++++++++++++++++

###########################################
          Queue process complete!
###########################################
```

**Pull request closed without merging**
