### PR TITLE
academic/root: Updated for version 6.28/02

### PR DESCRIPTION
**Pull request by arabusov**
The first patch-fix (02) for the release version 6.28 has been published a week ago, and it contains some nice features and bug fixes. The release note one can find here: https://root.cern/doc/v628/release-notes.html#release-6.28. I have tested this update on my primary host and found so far no new issues with ROOT.

### CODE REVIEW

**Comment by aclemons** [comment]
This is failing to build for me on both x86_64 and i586. (6.26.10 did not have a problem building).

```
# buildpkg x86_64 academic/root
sbolint: root checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar 31 21:34:31 GMT 2023
revision: df44fdc98a388d33ae2751463fcec93829cf7221
title:    academic/root: Updated for version 6.28.02.

================================================================================
academic/root                                                           21:35:04
================================================================================

Calculating dependencies ... 
Hints for academic/root:
  OPTIONS="QT=no"
Dependency tree:
academic/root (update for version 6.28.02)
  libraries/tbb (ok)
  libraries/libAfterImage (ok)
  libraries/gl2ps (ok)
  libraries/ftgl (ok)
  development/python3-numpy (ok)

Building academic/root (update for version 6.28.02) ------------------- 21:35:05
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
python3-numpy-1.22.3-x86_64-1_SBo: Python3 extension for scientific comp [  33M]
ftgl-2.4.0-x86_64-2_SBo: font rendering library for OpenGL applications  [ 610K]
gl2ps-1.3.7-x86_64-2_SBo: OpenGL to PostScript printing library ........ [ 540K]
libAfterImage-1.20-x86_64-2_SBo: Generic image manipulation library .... [ 1.2M]
tbb-2020u2-x86_64-1_SBo: Intel Threading Building Blocks ............... [ 2.5M]
Running root.SlackBuild ...                                         ETA 21:57:??
env MAKEFLAGS='-j24 -l13' QT=no nice -n 5 bash ./root.SlackBuild
academic/root: root.SlackBuild failed (status 2)                        21:35:32
-- Looking for pthread_create in pthreads - not found
Call Stack (most recent call first):
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm - not found
-- Not building amdgpu-arch: hsa-runtime64 not found
-- Looking for m - not found
CMake Error at googletest-stamp/googletest-download-Release.cmake:49 (message):
make[2]: *** [CMakeFiles/googletest.dir/build.make:98: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:8506: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
See /var/log/repo/SBo/academic/root/build.log
Unmounting chroot ... done.
:-( academic/root FAILED )-:

================================================================================
SUMMARY                                                                 21:35:33
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-31_21:35:03.log
Runtime:     0h 0m 30s
Failed:      1
  academic/root
```

It looks like it is trying to clone gtest. Can we tell it to use the system gtest (and add the dependency) or provide gtest already downloaded?

```
CMake Error at googletest-stamp/googletest-download-Release.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/tmp/SBo/repo.rm0QN9/build_root/root-6.28.02/build/googletest-prefix/tmp/googletest-gitclone.cmake'

  See also

    /tmp/SBo/repo.rm0QN9/build_root/root-6.28.02/build/googletest-prefix/src/googletest-stamp/googletest-download-*.log


make[2]: *** [CMakeFiles/googletest.dir/build.make:98: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:8506: CMakeFiles/googletest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by aclemons** [comment]
Sorry, I accidentally left this staged on my branch, so it did go out in today's update. It builds, but not in offline mode. If you could check on that for your next submission, that would be great thanks.

**Comment by arabusov** [comment]
Hello Andrew,

My mistake is that I didn't check this root version with a clean Slackware
environment and only on my working host where I have installed gtest (I
guess). Apparently, root's dependencies have been changed a while ago. Let
me try to fix it by the next week update.

Regards
Andrei

**Comment by arabusov** [comment]
Hello @aclemons

What I have overlooked last Friday is a new CMake option added by the root team, `builtin_gtest`. By default it is `ON` and requires network connection. So, an easy fix I'm trying to test right now is to switch off this option in the `root.Slackbuild` file directly.

**Pull request closed without merging**
