### PR TITLE
games/ags: updated for version 3.6.0.47

### PR DESCRIPTION
**Pull request by Ythogtha**
3.6.0.47 is not flagged as RC but release, that's why I stuck to 3.5 until now.

This update requires SDL_sound, newly submitted to the website, which is the SLD_sound version for SDL2.
This cannot be merged until SDL_sound is approved !

### CODE REVIEW

**Comment by Ythogtha** [comment]
Fixed this PR according to changes being made on the SDL2_sound submission.

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
waiting for SDL2_Sound submission fix

**Comment by Ythogtha** [comment]
It should be ok now, thanks!

**Comment by aclemons** [comment]
```
# buildpkg i586 games/ags
sbolint: ags checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Apr 14 13:54:41 GMT 2023
revision: 172b64a001783fc7b4c636f1b6a7e022520a8e1c
title:    libraries/SDL2_sound: Added (a sound library add-on for SDL2)

================================================================================
games/ags                                                               13:55:03
================================================================================

Calculating dependencies ... 
Dependency tree:
games/ags (update for version 3.6.0.47)
  libraries/SDL2_sound (add version 2.0.1)

Building libraries/SDL2_sound (add version 2.0.1) --------------------- 13:55:03
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running SDL2_sound.SlackBuild ...
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./SDL2_sound.SlackBuild
Built ok:  SDL2_sound-2.0.1-i586-1_SBo.txz                              13:55:12
Testing package SDL2_sound-2.0.1-i586-1_SBo.txz ... done.
Test installing SDL2_sound-2.0.1-i586-1_SBo.txz ...
SDL2_sound-2.0.1-i586-1_SBo: a sound library add-on for SDL2 ........... [1020K]
Unmounting chroot ... done.
:-) libraries/SDL2_sound Added version 2.0.1 (a sound library add-on for SDL2) (-:

Building games/ags (update for version 3.6.0.47) ---------------------- 13:55:13
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
SDL2_sound-2.0.1-i586-1_SBo: a sound library add-on for SDL2 ........... [1020K]
Running ags.SlackBuild ...                                          ETA 13:56:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./ags.SlackBuild
Built ok:  ags-3.6.0.47-i586-1_SBo.txz                                  13:55:47
Testing package ags-3.6.0.47-i586-1_SBo.txz ... done.
Test installing ags-3.6.0.47-i586-1_SBo.txz ...
ags-3.6.0.47-i586-1_SBo: Adventure Game Studio engine .................. [ 3.7M]
Unmounting chroot ... done.
Backed up: ags-3.5.1.27-i586-1_SBo.txz
:-) games/ags Updated for version 3.6.0.47 (-:

================================================================================
SUMMARY                                                                 13:55:48
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-04-14_13:55:02.log
Runtime:     0h 0m 46s
Added:       1
  libraries/SDL2_sound/SDL2_sound-2.0.1-i586-1_SBo.txz
Updated:     1
  games/ags/ags-3.6.0.47-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/games/ags/ags-3.6.0.47-i586-1_SBo.txz to /tmp/sbopkglint.fJ9zT7 ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/games/ags/ags-3.6.0.47-i586-1_SBo.txz to /tmp/sbopkglint.fJ9zT7 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== ags-3.6.0.47-i586-1_SBo.txz: All tests passed
```

```
# buildpkg x86_64 games/ags
sbolint: ags checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Apr 14 13:54:41 GMT 2023
revision: 172b64a001783fc7b4c636f1b6a7e022520a8e1c
title:    libraries/SDL2_sound: Added (a sound library add-on for SDL2)

================================================================================
games/ags                                                               13:56:04
================================================================================

Calculating dependencies ... 
Dependency tree:
games/ags (update for version 3.6.0.47)
  libraries/SDL2_sound (add version 2.0.1)

Building libraries/SDL2_sound (add version 2.0.1) --------------------- 13:56:04
Testing SlackBuild files ... done.
Verifying source files ... done.
Testing download URLs ... done.
Running SDL2_sound.SlackBuild ...
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./SDL2_sound.SlackBuild
Built ok:  SDL2_sound-2.0.1-x86_64-1_SBo.txz                            13:56:13
Testing package SDL2_sound-2.0.1-x86_64-1_SBo.txz ... done.
Test installing SDL2_sound-2.0.1-x86_64-1_SBo.txz ...
SDL2_sound-2.0.1-x86_64-1_SBo: a sound library add-on for SDL2 ......... [ 1.3M]
Unmounting chroot ... done.
:-) libraries/SDL2_sound Added version 2.0.1 (a sound library add-on for SDL2) (-:

Building games/ags (update for version 3.6.0.47) ---------------------- 13:56:14
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
SDL2_sound-2.0.1-x86_64-1_SBo: a sound library add-on for SDL2 ......... [ 1.3M]
Running ags.SlackBuild ...                                          ETA 13:57:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./ags.SlackBuild
Built ok:  ags-3.6.0.47-x86_64-1_SBo.txz                                13:56:45
Testing package ags-3.6.0.47-x86_64-1_SBo.txz ... done.
Test installing ags-3.6.0.47-x86_64-1_SBo.txz ...
ags-3.6.0.47-x86_64-1_SBo: Adventure Game Studio engine ................ [ 3.7M]
Unmounting chroot ... done.
Backed up: ags-3.5.1.27-x86_64-1_SBo.txz
:-) games/ags Updated for version 3.6.0.47 (-:

================================================================================
SUMMARY                                                                 13:56:46
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-04-14_13:56:03.log
Runtime:     0h 0m 43s
Added:       1
  libraries/SDL2_sound/SDL2_sound-2.0.1-x86_64-1_SBo.txz
Updated:     1
  games/ags/ags-3.6.0.47-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/games/ags/ags-3.6.0.47-x86_64-1_SBo.txz to /tmp/sbopkglint.EXUc0K ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/games/ags/ags-3.6.0.47-x86_64-1_SBo.txz to /tmp/sbopkglint.EXUc0K ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== ags-3.6.0.47-x86_64-1_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
Build fine for me with SDL2_sound from bedlam's branch.

Staged to my branch

**Pull request closed without merging**
