### PR TITLE
python/python3-klein: updated for version 23.5.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
in c8c3fc8ac1d43bd625fbfab8df841f366b5954c8 this package has been updated to use python3-wheel, why revert it back to the old wheel which is planned to be removed?

**Comment by Ythogtha** [comment]
Well, it clearly looks like a mistake on my part...
Fixed, sorry :)

**Comment by aclemons** [comment]
```
# buildpkg i586 python/python3-klein
sbolint: python3-klein checks out OK
it repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Sat May  6 00:54:35 GMT 2023
revision: 77e0547767f0f82053e081c97887e30414ced789
title:    python/python3-klein: Updated for version 23.5.0.

================================================================================
python/python3-klein                                                    00:55:00
================================================================================

Calculating dependencies ... 
Dependency tree:
python/python3-klein (update for version 23.5.0)
  python/werkzeug (ok)
  python/python3-wheel (ok)
    python/python3-installer (ok)
    python/python3-flit_core (ok)
  python/python3-tubes (ok)
    python/python3-twisted (ok)
      python/typing-extensions (ok)
        python/python3-installer (ok)
        python/python3-flit_core (ok)
        python/python3-build (ok)
          python/python3-pep517 (ok)
      python/python3-service-identity (ok)
        python/python3-pyasn1-modules (ok)
          python/python3-pyasn1 (ok)
        python/python3-attrs (ok)
        python/cryptography (ok)
          python/python3-wheel (ok)
            python/python3-installer (ok)
            python/python3-flit_core (ok)
          python/python3-setuptools-rust (ok)
            python/python3-semantic-version (ok)
            python/python-toml (ok)
          python/pyasn1 (ok)
          python/asn1crypto (ok)
      python/python3-automat (ok)
        python/python3-wheel (ok)
          python/python3-installer (ok)
          python/python3-flit_core (ok)
        python/python3-attrs (ok)
      python/incremental (ok)
      python/hyperlink (ok)
      python/constantly (ok)
      development/zope.interface (ok)
    python/python3-characteristic (ok)

Building python/python3-klein (update for version 23.5.0) ------------- 00:55:04
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
python3-characteristic-14.3.0-i586-1_SBo: Python attributes without boil [ 130K]
zope.interface-6.0-i586-1_SBo: Zope 3 Interface Infrastructure ......... [ 3.7M]
constantly-15.1.0-i586-2_SBo: Symbolic constants in Python ............. [ 110K]
hyperlink-21.0.0-i586-1_SBo: A featureful, correct URL for Python. ..... [ 890K]
incremental-22.10.0-i586-1_SBo: Python projects versioning ............. [ 350K]
python3-attrs-21.4.0-i586-1_SBo: Classes Without Boilerplate ........... [ 630K]
python3-flit_core-3.8.0-i586-2_SBo: Simplified pkging of Python modules, [ 140K]
python3-installer-0.5.1-i586-1_SBo: Library for installing Python packag [ 1.1M]
python3-wheel-0.40.0-i586-1_SBo: A built-package format for Python ..... [ 600K]
python3-automat-22.10.0-i586-4_SBo: Self-service finite-state machines . [ 320K]
asn1crypto-1.5.1-i586-1_SBo: Fast ASN.1 parser and serializer .......... [ 2.0M]
pyasn1-0.4.8-i586-1_SBo: ASN.1 types and codecs in Python .............. [ 1.5M]
python-toml-0.10.2-i586-2_SBo: A Python library for parsing and creating [ 240K]
python3-semantic-version-2.10.0-i586-1_SBo: Python Library ............. [ 150K]
python3-setuptools-rust-0.12.1-i586-3_SBo: Setuptools plugin for Rust ex [ 150K]
cryptography-38.0.4-i586-2_SBo: Python cryptography library ............ [ 4.9M]
python3-pyasn1-0.4.8-i586-1_SBo: ASN.1 types and codecs in Python ...... [ 710K]
python3-pyasn1-modules-0.3.0-i586-1_SBo: collection of ASN.1-based proto [ 1.5M]
python3-service-identity-21.1.0-i586-5_SBo: Service Identity Verificatio [ 110K]
python3-pep517-0.12.0-i586-1_SBo: API to call PEP 517 hooks ............ [ 140K]
python3-build-0.7.0-i586-1_SBo: a simple, correct PEP517 package builder [ 120K]
typing-extensions-4.3.0-i586-5_SBo: Backported and Experimental Type Hin [ 250K]
python3-twisted-22.10.0-i586-6_SBo: Python networking engine ........... [  26M]
python3-tubes-0.2.1-i586-2_SBo: micro-framework for web services ....... [ 480K]
werkzeug-2.1.2-i586-1_SBo: WSGI utility library for Python ............. [ 1.6M]
Running python3-klein.SlackBuild ...                                ETA 00:55:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./python3-klein.SlackBuild
Built ok:  python3-klein-23.5.0-i586-1_SBo.txz                          00:55:10
Testing package python3-klein-23.5.0-i586-1_SBo.txz ... done.
Test installing python3-klein-23.5.0-i586-1_SBo.txz ...
python3-klein-23.5.0-i586-1_SBo: micro-framework for web services ...... [ 710K]
Unmounting chroot ... done.
Backed up: python3-klein-21.8.0-i586-4_SBo.txz
:-) python/python3-klein Updated for version 23.5.0 (-:

================================================================================
SUMMARY                                                                 00:55:11
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-05-06_00:54:59.log
Runtime:     0h 0m 12s
Updated:     1
  python/python3-klein/python3-klein-23.5.0-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/python/python3-klein/python3-klein-23.5.0-i586-1_SBo.txz to /tmp/sbopkglint.zwwzrV ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/python/python3-klein/python3-klein-23.5.0-i586-1_SBo.txz to /tmp/sbopkglint.zwwzrV ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== python3-klein-23.5.0-i586-1_SBo.txz: All tests passed
```

```
# buildpkg x86_64 python/python3-klein
sbolint: python3-klein checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Sat May  6 00:54:35 GMT 2023
revision: 77e0547767f0f82053e081c97887e30414ced789
title:    python/python3-klein: Updated for version 23.5.0.

================================================================================
python/python3-klein                                                    00:55:26
================================================================================

Calculating dependencies ... 
Dependency tree:
python/python3-klein (update for version 23.5.0)
  python/werkzeug (ok)
  python/python3-wheel (ok)
    python/python3-installer (ok)
    python/python3-flit_core (ok)
  python/python3-tubes (ok)
    python/python3-twisted (ok)
      python/typing-extensions (ok)
        python/python3-installer (ok)
        python/python3-flit_core (ok)
        python/python3-build (ok)
          python/python3-pep517 (ok)
      python/python3-service-identity (ok)
        python/python3-pyasn1-modules (ok)
          python/python3-pyasn1 (ok)
        python/python3-attrs (ok)
        python/cryptography (ok)
          python/python3-wheel (ok)
            python/python3-installer (ok)
            python/python3-flit_core (ok)
          python/python3-setuptools-rust (ok)
            python/python3-semantic-version (ok)
            python/python-toml (ok)
          python/pyasn1 (ok)
          python/asn1crypto (ok)
      python/python3-automat (ok)
        python/python3-wheel (ok)
          python/python3-installer (ok)
          python/python3-flit_core (ok)
        python/python3-attrs (ok)
      python/incremental (ok)
      python/hyperlink (ok)
      python/constantly (ok)
      development/zope.interface (ok)
    python/python3-characteristic (ok)

Building python/python3-klein (update for version 23.5.0) ------------- 00:55:30
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
python3-characteristic-14.3.0-x86_64-1_SBo: Python attributes without bo [ 130K]
zope.interface-6.0-x86_64-1_SBo: Zope 3 Interface Infrastructure ....... [ 3.7M]
constantly-15.1.0-x86_64-3_SBo: Symbolic constants in Python ........... [ 110K]
hyperlink-21.0.0-x86_64-1_SBo: A featureful, correct URL for Python. ... [ 890K]
incremental-22.10.0-x86_64-1_SBo: Python projects versioning ........... [ 350K]
python3-attrs-21.4.0-x86_64-1_SBo: Classes Without Boilerplate ......... [ 630K]
python3-flit_core-3.8.0-x86_64-2_SBo: Simplified pkging of Python module [ 140K]
python3-installer-0.5.1-x86_64-1_SBo: Library for installing Python pack [ 1.1M]
python3-wheel-0.40.0-x86_64-1_SBo: A built-package format for Python ... [ 600K]
python3-automat-22.10.0-x86_64-4_SBo: Self-service finite-state machines [ 320K]
asn1crypto-1.5.1-x86_64-1_SBo: Fast ASN.1 parser and serializer ........ [ 2.0M]
pyasn1-0.4.8-x86_64-1_SBo: ASN.1 types and codecs in Python ............ [ 1.5M]
python-toml-0.10.2-x86_64-2_SBo: A Python library for parsing and creati [ 240K]
python3-semantic-version-2.10.0-x86_64-1_SBo: Python Library ........... [ 150K]
python3-setuptools-rust-0.12.1-x86_64-6_SBo: Setuptools plugin for Rust  [ 150K]
cryptography-38.0.4-x86_64-2_SBo: Python cryptography library .......... [ 4.6M]
python3-pyasn1-0.4.8-x86_64-1_SBo: ASN.1 types and codecs in Python .... [ 710K]
python3-pyasn1-modules-0.3.0-x86_64-1_SBo: pyasn1-modules A collection o [ 1.5M]
python3-service-identity-21.1.0-x86_64-7_SBo: Service Identity Verificat [ 110K]
python3-pep517-0.12.0-x86_64-1_SBo: API to call PEP 517 hooks .......... [ 140K]
python3-build-0.7.0-x86_64-1_SBo: a simple, correct PEP517 package build [ 120K]
typing-extensions-4.3.0-x86_64-5_SBo: Backported and Experimental Type H [ 250K]
python3-twisted-22.10.0-x86_64-7_SBo: Python networking engine ......... [  26M]
python3-tubes-0.2.1-x86_64-2_SBo: micro-framework for web services ..... [ 480K]
werkzeug-2.1.2-x86_64-1_SBo: WSGI utility library for Python ........... [ 1.6M]
Running python3-klein.SlackBuild ...                                ETA 00:56:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./python3-klein.SlackBuild
Built ok:  python3-klein-23.5.0-x86_64-1_SBo.txz                        00:55:35
Testing package python3-klein-23.5.0-x86_64-1_SBo.txz ... done.
Test installing python3-klein-23.5.0-x86_64-1_SBo.txz ...
python3-klein-23.5.0-x86_64-1_SBo: micro-framework for web services .... [ 710K]
Unmounting chroot ... done.
Backed up: python3-klein-21.8.0-x86_64-4_SBo.txz
:-) python/python3-klein Updated for version 23.5.0 (-:

================================================================================
SUMMARY                                                                 00:55:36
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-05-06_00:55:26.log
Runtime:     0h 0m 10s
Updated:     1
  python/python3-klein/python3-klein-23.5.0-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/python/python3-klein/python3-klein-23.5.0-x86_64-1_SBo.txz to /tmp/sbopkglint.rFg1E4 ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/python/python3-klein/python3-klein-23.5.0-x86_64-1_SBo.txz to /tmp/sbopkglint.rFg1E4 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== python3-klein-23.5.0-x86_64-1_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
LGTM - staged to my branch

**Pull request closed without merging**
