### PR TITLE
development/tiled: updated for version 1.9.2

### PR DESCRIPTION
**Pull request by Ythogtha**
The lib64 patch does not work, libs are still put in /usr/lib/
It is very hardcoded, probably hardwired inside the brain of the developers of Tiled.
I still haven't found a reliable way to force this build to put its lib in /usr/lib64/.

Anyway, it still works as it is, I see no point in not updating it.

### CODE REVIEW

**Comment by aclemons** [comment]
```
# buildpkg i586 development/tiled                                                                                                                                                                                                                                  [7/7]
sbolint: tiled checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 14:08:24 GMT 2023
revision: a41991777d8cdc4d3b894bdf779b5c1498a022c0
title:    development/tiled: Updated for version 1.9.2.

================================================================================
development/tiled                                                       14:08:56
================================================================================

Calculating dependencies ...
Dependency tree:
development/tiled (update for version 1.9.2)
  development/qbs (ok)

Building development/tiled (update for version 1.9.2) ----------------- 14:08:56
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
qbs-1.16.0-i586-1_SBo: Qt Build Suite ................................................................................................................................................................................................................................... [  14M]
Running tiled.SlackBuild ...                                        ETA 14:11:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./tiled.SlackBuild
Build time 100 sec, peak load 9.77, peak memory 1141M, peak tmp 635M
Built ok:  tiled-1.9.2-i586-1_SBo.txz                                   14:10:38
Testing package tiled-1.9.2-i586-1_SBo.txz ... done.
Test installing tiled-1.9.2-i586-1_SBo.txz ...
tiled-1.9.2-i586-1_SBo: Tiled map editor ................................................................................................................................................................................................................................ [  31M]
Unmounting chroot ... done.
Backed up: tiled-1.8.5-i586-1_SBo.txz
:-) development/tiled Updated for version 1.9.2 (-:

================================================================================
SUMMARY                                                                 14:10:43
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_14:08:55.log
Runtime:     0h 1m 48s
Updated:     1
  development/tiled/tiled-1.9.2-i586-1_SBo.txz
Warnings:    1
  development/tiled: Files/directories were modified in the chroot

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/i586/development/tiled/tiled-1.9.2-i586-1_SBo.txz to /tmp/sbopkglint.akpA1K ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== tiled-1.9.2-i586-1_SBo.txz: All tests passed
```
```
# buildpkg amd64 development/tiled                                                                                                                                                                                                                               [23/23]
sbolint: tiled checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 14:08:24 GMT 2023
revision: a41991777d8cdc4d3b894bdf779b5c1498a022c0
title:    development/tiled: Updated for version 1.9.2.

================================================================================
development/tiled                                                       14:11:55
================================================================================

Calculating dependencies ...
Dependency tree:
development/tiled (update for version 1.9.2)
  development/qbs (ok)

Building development/tiled (update for version 1.9.2) ----------------- 14:11:55
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
qbs-1.16.0-x86_64-1_SBo: Qt Build Suite ................................................................................................................................................................................................................................. [  14M]
Running tiled.SlackBuild ...                                        ETA 14:13:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./tiled.SlackBuild
Build time 98 sec, peak load 9.76, peak memory 2279M, peak tmp 778M
Built ok:  tiled-1.9.2-x86_64-1_SBo.txz                                 14:13:35
Testing package tiled-1.9.2-x86_64-1_SBo.txz ...
WARNING: development/tiled: x86-64 files in /usr/lib
usr/lib/libtiled.so
usr/lib/libtilededitor.so
usr/lib/tiled/plugins/libcsv.so
usr/lib/tiled/plugins/libdefold.so
usr/lib/tiled/plugins/libdefoldcollection.so
usr/lib/tiled/plugins/libdroidcraft.so
usr/lib/tiled/plugins/libflare.so
usr/lib/tiled/plugins/libgmx.so
usr/lib/tiled/plugins/libjson.so
usr/lib/tiled/plugins/libjson1.so
usr/lib/tiled/plugins/liblua.so
usr/lib/tiled/plugins/libpython.so
usr/lib/tiled/plugins/libreplicaisland.so
usr/lib/tiled/plugins/librpmap.so
usr/lib/tiled/plugins/libtbin.so
usr/lib/tiled/plugins/libtengine.so
usr/lib/tiled/plugins/libyy.so
Test installing tiled-1.9.2-x86_64-1_SBo.txz ...
tiled-1.9.2-x86_64-1_SBo: Tiled map editor .............................................................................................................................................................................................................................. [  32M]
Unmounting chroot ... done.
Backed up: tiled-1.8.5-x86_64-1_SBo.txz
:-) development/tiled Updated for version 1.9.2 (-:

================================================================================
SUMMARY                                                                 14:13:40
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_14:11:54.log
Runtime:     0h 1m 46s
Updated:     1
  development/tiled/tiled-1.9.2-x86_64-1_SBo.txz
Warnings:    2
  development/tiled: Files/directories were modified in the chroot
  development/tiled: x86-64 files in /usr/lib

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/x86_64/development/tiled/tiled-1.9.2-x86_64-1_SBo.txz to /tmp/sbopkglint.C67l4B ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...
--- shared lib(s) in wrong dir for ARCH:
-rwxr-xr-x 1 root root 1444928 Jan  3 14:13 usr/lib/libtiled.so
-rwxr-xr-x 1 root root 8120624 Jan  3 14:13 usr/lib/libtilededitor.so
FAILED
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! tiled-1.9.2-x86_64-1_SBo.txz: 1 failures
```

**Comment by aclemons** [comment]
I've staged this to my branch for now - I can update it if you find that just `mv`ing the files over works

**Comment by Ythogtha** [comment]
Ok, well, it works, seems that the easy way was the right way.
Thanks !
I updated my PR, removing unneeded stuff.

**Comment by aclemons** [comment]
> Ok, well, it works, seems that the easy way was the right way. Thanks ! I updated my PR, removing unneeded stuff.

LGTM. Updated on my branch now. Thanks.


```
# buildpkg amd64 development/tiled                                                                                                                                                                                                                                 [9/9]
sbolint: tiled checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 21:40:06 GMT 2023
revision: e841bf7f466ef13b0e80bcc72686a723ee98f3da
title:    development/tiled: updated for version 1.9.2

================================================================================
development/tiled                                                       21:40:44
================================================================================

Calculating dependencies ...
Dependency tree:
development/tiled (update for git e841bf7 "updated for version 1.9.2")
  development/qbs (ok)

----------------------------------------------------------------------- 21:40:45
Building development/tiled (update for git e841bf7 "updated for version 1.9.2")
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
qbs-1.16.0-x86_64-1_SBo: Qt Build Suite ................................................................................................................................................................................................................................. [  14M]
Running tiled.SlackBuild ...                                        ETA 21:43:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./tiled.SlackBuild
Build time 96 sec, peak load 9.86, peak memory 2421M, peak tmp 777M
Built ok:  tiled-1.9.2-x86_64-2_SBo.txz                                 21:42:23
Testing package tiled-1.9.2-x86_64-2_SBo.txz ... done.
Test installing tiled-1.9.2-x86_64-2_SBo.txz ...
tiled-1.9.2-x86_64-2_SBo: Tiled map editor .............................................................................................................................................................................................................................. [  32M]
Unmounting chroot ... done.
Backed up: tiled-1.9.2-x86_64-1_SBo.txz
:-) development/tiled Updated for git e841bf7 "updated for version 1.9.2" (-:

================================================================================
SUMMARY                                                                 21:42:28
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_21:40:44.log
Runtime:     0h 1m 44s
Updated:     1
  development/tiled/tiled-1.9.2-x86_64-2_SBo.txz
Warnings:    1
  development/tiled: Files/directories were modified in the chroot

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/x86_64/development/tiled/tiled-1.9.2-x86_64-2_SBo.txz to /tmp/sbopkglint.SGa3Yk ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== tiled-1.9.2-x86_64-2_SBo.txz: All tests passed
```

```
# buildpkg i586 development/tiled
sbolint: tiled checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Tue Jan  3 21:40:06 GMT 2023
revision: e841bf7f466ef13b0e80bcc72686a723ee98f3da
title:    development/tiled: updated for version 1.9.2

================================================================================
development/tiled                                                       21:53:10
================================================================================

Calculating dependencies ...
Dependency tree:
development/tiled (update for git e841bf7 "updated for version 1.9.2")
  development/qbs (ok)

----------------------------------------------------------------------- 21:53:10
Building development/tiled (update for git e841bf7 "updated for version 1.9.2")
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Installing dependencies ...
qbs-1.16.0-i586-1_SBo: Qt Build Suite ................................................................................................................................................................................................................................... [  14M]
Running tiled.SlackBuild ...                                        ETA 21:55:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./tiled.SlackBuild
Build time 99 sec, peak load 10.25, peak memory 1478M, peak tmp 635M
Built ok:  tiled-1.9.2-i586-2_SBo.txz                                   21:54:51
WARNING: development/tiled: Files/directories were modified in the chroot
/root/.config
Testing package tiled-1.9.2-i586-2_SBo.txz ... done.
Test installing tiled-1.9.2-i586-2_SBo.txz ...
tiled-1.9.2-i586-2_SBo: Tiled map editor ................................................................................................................................................................................................................................ [  31M]
Unmounting chroot ... done.
Backed up: tiled-1.9.2-i586-1_SBo.txz
:-) development/tiled Updated for git e841bf7 "updated for version 1.9.2" (-:

================================================================================
SUMMARY                                                                 21:54:57
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-01-03_21:53:09.log
Runtime:     0h 1m 48s
Updated:     1
  development/tiled/tiled-1.9.2-i586-2_SBo.txz
Warnings:    1
  development/tiled: Files/directories were modified in the chroot

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Installing /var/lib/repo/SBo/packages/15.0/i586/development/tiled/tiled-1.9.2-i586-2_SBo.txz to /tmp/sbopkglint.cmABpQ ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== tiled-1.9.2-i586-2_SBo.txz: All tests passed
```

**Pull request closed without merging**
