### PR TITLE
ham/freedv: Updated for version 1.9.9.1.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build ham/freedv

**Comment by willysr** [comment]
@sbo-bot: build ham/freedv

**Comment by willysr** [comment]
@sbo-bot: build ham/lpcnetfreedv

**Comment by willysr** [comment]
@sbo-bot: build ham/lpcnetfreedv

**Comment by willysr** [comment]
@sbo-bot: build ham/lpcnetfreedv

**Comment by willysr** [comment]
@sbo-bot: build ham/freedv

**Comment by willysr** [comment]
@sbo-bot: build ham/freedv

**Comment by willysr** [comment]
@sbo-bot: build ham/freedv

**Comment by willysr** [comment]
@sbo-bot: build ham/sdrangel

**Comment by willysr** [comment]
@sbo-bot: build ham/sdrpp

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
