### PR TITLE
pypy, pypy3, PyPy, PyPy3

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
@sbo-bot: build python/pypy

**Comment by Ythogtha** [comment]
@sbo-bot: build python/pypy3

**Comment by Ythogtha** [comment]
@sbo-bot: build python/PyPy

**Comment by Ythogtha** [comment]
@sbo-bot: build python/PyPy3

**Comment by willysr** [comment]
@Ythogtha PyPy failed to build here

**Comment by willysr** [comment]
@sbo-bot: build x86_64 python/PyPy

**Comment by willysr** [comment]
false alarm
merged

**Pull request closed without merging**
