### PR TITLE
system/pam_ssh_agent_auth: Updated for version 0.10.4.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/pam_ssh_agent_auth

**Comment by willysr** [comment]
@pyllyukko this failed as well

**Comment by pyllyukko** [comment]
> @pyllyukko this failed as well

So I noticed. But why? Was it unable to download the sources or what? Because it couldn't find the file `pam_ssh_agent_auth-0.10.4.tar.gz`.

**Comment by willysr** [comment]
yes, please refer to this guide
https://slackbuilds.org/GITHUB_URLs.txt

**Comment by pyllyukko** [comment]
> yes, please refer to this guide

I did. Both the URLs ([1](https://github.com/jbeverly/pam_ssh_agent_auth/archive/pam_ssh_agent_auth-0.10.4/pam_ssh_agent_auth-0.10.4.tar.gz) & [2](https://github.com/floodyberry/ed25519-donna/archive/8757bd4/ed25519-donna-8757bd4cd209cb032853ece0ce413f122eef212c.tar.gz)) are perfectly fine and that's why I don't understand why sbo-bot failed to download them.

**Comment by willysr** [comment]
try this instead
https://github.com/jbeverly/pam_ssh_agent_auth/archive/pam_ssh_agent_auth-0.10.4/pam_ssh_agent_auth-pam_ssh_agent_auth-0.10.4.tar.gz

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
