### PR TITLE
multimedia/vapoursynth: Updated for version R70.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build x86_64 multimedia/vapoursynth

**Comment by willysr** [comment]
@aclemons need your help to debug why configure failed to check C compilers
i tried to test this under my current desktop and it worked, so something is wrong in stable

**Comment by aclemons** [comment]
what happened to this patch?
https://github.com/SlackBuildsOrg/slackbuilds/pull/8032/files

**Comment by willysr** [comment]
@sbo-bot: build x86_64 multimedia/vapoursynth

**Comment by willysr** [comment]
@aclemons i must have skipped them :(

**Pull request closed without merging**
