### PR TITLE
academic/plus42: Updated for version 1.1.4

### PR DESCRIPTION
**Pull request by antonioleal**
academic/plus42: Updated for version 1.1.4

I'm the new maintainer

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build academic/plus42

**Comment by aclemons** [comment]
@sbo-bot: build academic/plus42

**Comment by aclemons** [comment]
@sbo-bot: build academic/plus42

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
