### PR TITLE
python/python3-dulwich: updated for version 0.22.1

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
Oh, yes, that is a mistake. Sorry. Will fiw as soon as I can.

**Comment by willysr** [comment]
@Ythogtha can you fix this before i push the public update?

**Comment by Ythogtha** [comment]
@sbo-bot: build python/python3-dulwich

**Comment by Ythogtha** [comment]
> @Ythogtha can you fix this before i push the public update?

@willysr Just had time to do it !
I wasn't home those last days...
It's fixed.

**Comment by Ythogtha** [comment]
And, uh, it's broken.

**Comment by Ythogtha** [comment]
@sbo-bot: build python/python3-dulwich

**Comment by Ythogtha** [comment]
Now that's ok...

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
