### PR TITLE
python/python3-xkbcommon: Update for 1.0.1

### PR DESCRIPTION
**Pull request by isaackwy**
The latest current version of python3-xkbcommon is at 1.5.1
However, on Slackware 15.0, I cannot get python3-xkbcommon updated to that version.
1.0.1 is the latest version that I could get built.

This is the output that I receive when building python3-xkbcommon versions 1.5 and 1.5.1:

```
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/xkbcommon
copying xkbcommon/__init__.py -> build/lib.linux-x86_64-3.9/xkbcommon
copying xkbcommon/ffi_build.py -> build/lib.linux-x86_64-3.9/xkbcommon
copying xkbcommon/xkb.py -> build/lib.linux-x86_64-3.9/xkbcommon
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.9/xkbcommon._ffi.c'
creating build/temp.linux-x86_64-3.9
building 'xkbcommon._ffi' extension
creating build/temp.linux-x86_64-3.9/build
creating build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/include/python3.9 -c build/temp.linux-x86_64-3.9/xkbcommon._ffi.c -o build/temp.linux-x86_64-3.9/build/temp.linux-x86_64-3.9/xkbcommon._ffi.o
build/temp.linux-x86_64-3.9/xkbcommon._ffi.c: In function ‘_cffi_const_XKB_CONTEXT_NO_SECURE_GETENV’:
build/temp.linux-x86_64-3.9/xkbcommon._ffi.c:1017:12: error: ‘XKB_CONTEXT_NO_SECURE_GETENV’ undeclared (first use in this function); did you mean ‘_cffi_const_XKB_CONTEXT_NO_SECURE_GETENV’?
 1017 |   int n = (XKB_CONTEXT_NO_SECURE_GETENV) <= 0;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            _cffi_const_XKB_CONTEXT_NO_SECURE_GETENV
build/temp.linux-x86_64-3.9/xkbcommon._ffi.c:1017:12: note: each undeclared identifier is reported only once for each function it appears in
error: command '/usr/bin/gcc' failed with exit code 1
```

I don't know what to put in the README indicating that python3-xkbcommon cannot be updated any further on Slackware 15.0. I don't know what is causing the error above.

### CODE REVIEW

**Comment by willysr** [comment]
have you tried to switch to meson?
it seems ARCH is using meson to build the package

**Comment by isaackwy** [comment]
What do you mean by this?

I don't think the tarball uses meson to build.
These are the files in the source python-xkbcommon-$VERSION tarball.
```
.
├── LICENSE
├── MANIFEST.in
├── README.rst
├── pyproject.toml
├── setup.cfg
├── setup.py
├── tests
│   ├── __init__.py
│   ├── data.py
│   └── test_xkb.py
└── xkbcommon
    ├── __init__.py
    ├── ffi_build.py
    └── xkb.py
```

**Comment by willysr** [comment]
my bad, it was libxkbcommon, not the python3 binding package

**Comment by willysr** [comment]
@sbo-bot: build python/python3-xkbcommon

**Comment by willysr** [comment]
@sbo-bot: build python/python3-pywlroots

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
