### PR TITLE
academic/python3-scipy: Add missing python3-mesonpy dependency.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
@bassmadrigal I think you missed actually adding the updated meson as a dependency in #3356?

https://github.com/SlackBuildsOrg/slackbuilds/blob/f8046ba12f8863df2669920f6188beddc40dfe26/academic/python3-scipy/python3-scipy.SlackBuild#L79-L80

**Comment by aclemons** [comment]
This still fails to build for me. See below.

**Comment by aclemons** [comment]
@sbo-bot: build i586 academic/python3-scipy

**Comment by aclemons** [comment]
Did you have `OpenBLAS` installed when you tested this? If I add it as a dependency, the package builds. Is this correct?

**Comment by bassmadrigal** [comment]
Shoot, I must've updated it in my chroot and forgot to change it in my local repo. I'll double check everything tomorrow unless you beat me to it.

**Comment by aclemons** [comment]
No rush - just ping me back here and we can update and test again.

**Comment by willysr** [comment]
i think adding python3-meson-opt should fix it

**Comment by willysr** [comment]
@sbo-bot: build academic/python3-scipy

**Comment by willysr** [comment]
oh openblas

**Comment by aclemons** [comment]
> i think adding python3-meson-opt should fix it

I added `python3-mesonpy` already (which depends on `python3-meson-opt`) since it fails otherwise with:

```
ERROR Backend 'mesonpy' is not available.
```

**Comment by willysr** [comment]
@sbo-bot: build academic/python3-scipy

**Comment by bassmadrigal** [comment]
That works for me. Thanks for the catch!

**Comment by willysr** [comment]
@bassmadrigal please push it to your branch
i will mark this issue solved

**Pull request closed without merging**
