### PR TITLE
network:phppgadmin: Updated for version 7.14.7

### PR DESCRIPTION
**Pull request by mab974**
new github repository

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build network/phppgadmin

**Comment by willysr** [comment]
@mab974 you put incorrect MD5SUM

**Comment by mab974** [comment]
fix md5sum directly 
can you get it ?

**Comment by willysr** [comment]
@sbo-bot: build network/phppgadmin

**Comment by willysr** [comment]
it seems your DOWNLOAD field will resulting in a non-consistent output
i would suggest you to follow the pattern here https://slackbuilds.org/GITHUB_URLs.txt or see the previous pattern before the update

**Comment by mab974** [comment]
ok 
so later

**Pull request closed without merging**
