### PR TITLE
development/rstudio-desktop: Change installation method from source to binary

### PR DESCRIPTION
**Pull request by isaackwy**
I faced difficulty building rstudio-desktop. Here is some sample output:

```
     [java]    [ERROR] Errors in 'com/google/gwt/user/cellview/client/DataGrid.java'
     [java]       [ERROR] Line 502: Failed to resolve 'com.google.gwt.user.cellview.client.DataGrid.Resources' via deferred binding

BUILD FAILED
/tmp/SBo/rstudio-2023.03.0-386/src/gwt/build.xml:176: Java returned: 1

Total time: 1 minute 16 seconds
make[2]: *** [src/gwt/CMakeFiles/gwt_build.dir/build.make:2672: src/gwt/timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:412: src/gwt/CMakeFiles/gwt_build.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Therefore, I would like to repackage the rstudio-desktop binary instead.

The 2 kinds of RStudio binaries that work on Slackware 15.0:
[Fedora 34/Red Hat 8](https://download1.rstudio.org/electron/rhel8/x86_64/rstudio-2023.03.0-386-x86_64.rpm) (the one I'm using)
[Ubuntu 18+/Debian 10+](https://download1.rstudio.org/electron/bionic/amd64/rstudio-2023.03.0-386-amd64.deb)

### CODE REVIEW

**Comment by aclemons** [comment]
I wonder if this is because more commits have been added to the `release/rstudio-cherry-blossom` branch?

I built rstudio-desktop at the weekend successfully after applying this commit:

https://git.slackbuilds.org/slackbuilds/commit/?h=user/aclemons/updates&id=a357e688d7aa4d25f6ab11a8adb8445ed8f09f2a

It's your build of course, so if you want to switch to a binary repackaging, that is also fine.

**Comment by isaackwy** [comment]
I still prefer binary repackaging.

1. It becomes easier for myself (or for other people) to update when a new version of rstudio-desktop comes out.
2. The binary for rstudio 2023.03.0+386 actually runs. I built the previous versions of rstudio because the binary did not run.

Additional note:
3. The list of dependencies is now "R postgresql". I encountered an error upon running rstudio (that was resolved by installing rstudio). Hence the rebase.

**Comment by aclemons** [comment]
Ok, I've staged this to my branch. I wonder if you should move lib to lib64 during the build though?

```
WARNING: development/rstudio-desktop: x86-64 files in /usr/lib
usr/lib/rstudio/chrome-sandbox
usr/lib/rstudio/chrome_crashpad_handler
usr/lib/rstudio/libEGL.so
usr/lib/rstudio/libGLESv2.so
usr/lib/rstudio/libffmpeg.so
usr/lib/rstudio/libvk_swiftshader.so
usr/lib/rstudio/libvulkan.so.1
usr/lib/rstudio/resources/app/.webpack/main/native_modules/build/Release/system-fonts.node
usr/lib/rstudio/resources/app/.webpack/main/native_modules/build/Release/unix_dgram.node
usr/lib/rstudio/resources/app/.webpack/main/native_modules/desktop.node
usr/lib/rstudio/resources/app/.webpack/main/native_modules/dock.node
usr/lib/rstudio/resources/app/bin/crashpad_handler
usr/lib/rstudio/resources/app/bin/crashpad_http_upload
usr/lib/rstudio/resources/app/bin/diagnostics
usr/lib/rstudio/resources/app/bin/quarto/bin/tools/dart-sass/sass
usr/lib/rstudio/resources/app/bin/quarto/bin/tools/deno-x86_64-unknown-linux-gnu/deno
usr/lib/rstudio/resources/app/bin/quarto/bin/tools/deno_dom/libplugin.so
usr/lib/rstudio/resources/app/bin/quarto/bin/tools/esbuild
usr/lib/rstudio/resources/app/bin/quarto/bin/tools/pandoc
usr/lib/rstudio/resources/app/bin/rpostback
usr/lib/rstudio/resources/app/bin/rsession
usr/lib/rstudio/rstudio
```

**Comment by isaackwy** [comment]
I tried changing the $PKG/usr/lib directory to $PKG/usr/lib64. This is what I got from sbopkglint:

```
Exploding /tmp/rstudio-desktop-2023.03.0+386-x86_64-2_SBo.tgz to /tmp/sbopkglint.bPRE8q ...OK
Running pre-doinst test...OK
Installing /tmp/rstudio-desktop-2023.03.0+386-x86_64-2_SBo.tgz to /tmp/sbopkglint.bPRE8q ...OK
Running test: 05-basic-sanity...
--- package contains broken relative symlinks:
lrwxrwxrwx 1 root root 51 May  3 00:14 ./usr/lib64/.build-id/06/a801831b336ea25d7b4b3a1842ec788e781c40 -> ../../../../usr/lib/rstudio/chrome_crashpad_handler
lrwxrwxrwx 1 root root 55 May  3 00:14 ./usr/lib64/.build-id/15/21d82cd8ce2daa7a95cf192e75dbb73d8e1a1e -> ../../../../usr/lib/rstudio/resources/app/bin/rpostback
lrwxrwxrwx 1 root root 42 May  3 00:14 ./usr/lib64/.build-id/51/74642779eb830026a665bff7d1869207a574ac -> ../../../../usr/lib/rstudio/libvulkan.so.1
lrwxrwxrwx 1 root root 37 May  3 00:14 ./usr/lib64/.build-id/7b/bde14ca6192338b4c5d44af06e90ca06276940 -> ../../../../usr/lib/rstudio/libEGL.so
lrwxrwxrwx 1 root root 40 May  3 00:14 ./usr/lib64/.build-id/8b/060bea4cd4260d05f778be1856691d20377fcb -> ../../../../usr/lib/rstudio/libffmpeg.so
lrwxrwxrwx 1 root root 42 May  3 00:14 ./usr/lib64/.build-id/90/9d0b5007ba7bf20d9e4205235b3fe5a9f3309e -> ../../../../usr/lib/rstudio/chrome-sandbox
lrwxrwxrwx 1 root root 54 May  3 00:14 ./usr/lib64/.build-id/af/82ce3b47b55b3457fb25de59eb257065515df2 -> ../../../../usr/lib/rstudio/resources/app/bin/rsession
lrwxrwxrwx 1 root root 57 May  3 00:14 ./usr/lib64/.build-id/b5/9dd0acbcd72155230b6413797b41350318a852 -> ../../../../usr/lib/rstudio/resources/app/bin/diagnostics
lrwxrwxrwx 1 root root 62 May  3 00:14 ./usr/lib64/.build-id/c0/5fa55274dbc2719d3d82db1b7f9f6dc17a470d -> ../../../../usr/lib/rstudio/resources/app/bin/crashpad_handler
lrwxrwxrwx 1 root root 66 May  3 00:14 ./usr/lib64/.build-id/cc/34daf4315e1b8212faa5558d73f036db51b4b1 -> ../../../../usr/lib/rstudio/resources/app/bin/crashpad_http_upload
lrwxrwxrwx 1 root root 40 May  3 00:14 ./usr/lib64/.build-id/cc/c779f73c7657d7b2194b1cb1afa97bfb378882 -> ../../../../usr/lib/rstudio/libGLESv2.so
lrwxrwxrwx 1 root root 48 May  3 00:14 ./usr/lib64/.build-id/ec/920f29e603a5083ff3737e27328293c7133f1c -> ../../../../usr/lib/rstudio/libvk_swiftshader.so
lrwxrwxrwx 1 root root 35 May  3 00:14 ./usr/lib64/.build-id/f7/47cd6fb23a78d3a91167fb4d6497474489f0aa -> ../../../../usr/lib/rstudio/rstudio
___ note: package contains empty dirs, are these necessary?
drwxr-xr-x 2 root root 4096 Mar  8 19:03 ./usr/lib64/rstudio/resources/app/bin/quarto/share/deno_std/cache/npm
drwxr-xr-x 2 root root 4096 Mar  8 19:03 ./usr/lib64/rstudio/resources/app/node_modules
FAILED
Running test: 10-docs...
___ note: install instructions found, is this relevant for binary package users?: usr/doc/rstudio-desktop-2023.03.0+386/INSTALL
OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
!!! rstudio-desktop-2023.03.0+386-x86_64-2_SBo.tgz: 1 failures
```

I am not moving lib to lib64 at the moment.

**Comment by slackalaxy** [comment]
in my experience, the compiled rstudio had some issues with the clipboard, with an error like this:

QXcbClipboard::setMimeData: Cannot set X11 selection owner

here's me, complaining at QT:
https://www.linuxquestions.org/questions/slackware-14/%5Bbug%5D-copy-paste-from-qt5-applications-4175723946/

No idea if a bug with the program or QT5 itself

so far, the repackaged binary _seems_ to behave...

-petar

**Pull request closed without merging**
