### PR TITLE
desktop/nwg-bar: Update for version 0.1.4

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-bar

**Comment by willysr** [comment]
hi @mac-a-r0ni this build failed, can you take a look on the error message?

**Comment by aclemons** [comment]
Is this missing a dependency on google-go-lang @mac-a-r0ni?

**Comment by aclemons** [comment]
It doesn't seem to build with cgo

**Comment by mac-a-r0ni** [comment]
> Is this missing a dependency on google-go-lang @mac-a-r0ni?

After looking at the info, yes it is missing the dep on google-go-lang. I could try and do the push on mobile, but I won't be in front of a machine to check properly until after the usual weekly update. It did build cleanly in my tests with google-go-lang installed earlier. Sorry for the oversight, last minute update I didn't expect.

**Comment by aclemons** [comment]
Ok, let me adjust it here and check. Thanks

**Comment by aclemons** [comment]
@sbo-bot: build desktop/nwg-bar

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 desktop/nwg-bar

**Comment by aclemons** [comment]
@sbo-bot: build i586 desktop/nwg-bar

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
