### PR TITLE
development/rizin: Updated for version 0.7.0

### PR DESCRIPTION
**Pull request by earies**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/rizin

**Comment by willysr** [comment]
@earies this has incorrect checksum

**Comment by earies** [comment]
> @earies this has incorrect checksum

Updated checksum in this branch https://github.com/SlackBuildsOrg/slackbuilds/compare/master...earies:slackbuilds-upstream:rizin-0.7.0 however I don't see the commit being picked up in this PR

**Comment by earies** [comment]
> did you push it?

yep - you can see in the above URL that 2 commits are pushed to this branch, associated to this PR however this PR is not displaying the commit.... something seems off (just standard PR update process w/ additional commits)

**Comment by earies** [comment]
> hm that last commit showed up

yep - added another commit but still lagged... think we're dealing w/ some github issues atm - looks to be clean now

**Comment by earies** [comment]
> or try another PR ? we can try to close this one

we're clean now - all 3 commits are showing up w/ the desired outcome (0.7.0 version bump + updated MD5 + copyright year)

**Comment by earies** [comment]
FYI - https://www.githubstatus.com/ confirms what we're seeing atm

https://github.com/orgs/community/discussions/51962#discussioncomment-8644116

**Comment by willysr** [comment]
@sbo-bot: build development/rizin

**Comment by willysr** [comment]
@earies this requires newer version of capstone

**Comment by earies** [comment]
> @earies this requires newer version of capstone

yep just saw that - capstone SBo is quite far out of date - was built against local 5.0.1 https://github.com/earies/slackbuilds/tree/master/system/capstone updated in Aug 2023

I can reissue the PR when capstone is updated

**Comment by willysr** [comment]
@sbo-bot: build development/rizin

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
