### PR TITLE
11 Version Bumps and 1 Note On Why We Can't Update

### PR DESCRIPTION
**Pull request by bassmadrigal**
multimedia/filebot: Version bump to 5.1.2
academic/xsimd: Version bump to 11.2.0
python/python3-executing: Version bump to 2.0.1
python/python3-filelock: Version bump to 3.13.1
python/python-msal: Version bump to 1.25.0
python/python3-pandas: Version bump to 2.1.3 and remove second-level deps
python/python3-platformdirs: Version bump to 4.0.0 and remove second-level dep
libraries/pymediainfo: Version bump to 6.1.0
python/ipython: Version bump to 8.17.2
network/discord: Version bump to 0.0.35
python/python3-pdm: Version bump to 2.10.3

python/python3-qbittorrent-api: Note on why we can't update (needs newer setuptools/setuptools-scm than on 15.0 or SBo)

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build academic/xsimd

**Comment by aclemons** [comment]
@sbo-bot: build libraries/pymediainfo

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/filebot

**Comment by aclemons** [comment]
@sbo-bot: build network/discord

**Comment by aclemons** [comment]
@sbo-bot: build python/ipython

**Comment by aclemons** [comment]
@sbo-bot: build python/python-msal

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-executing

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-filelock

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-pandas

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-pdm

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-platformdirs

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-qbittorrent-api

**Comment by aclemons** [comment]
@bassmadrigal xsimd fails to build on 32bit. The previous version seems to have built fine. I built it here in September:

```sh
# ls -la
total 144
drwxr-xr-x   2 root root   4096 Sep 24 07:47 .
drwxr-xr-x 356 root root  12288 Nov 17 15:17 ..
-rw-r--r--   1 root root      8 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.dep
-rw-r--r--   1 root root   7904 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.lst
-rw-r--r--   1 root root    632 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.meta
-rw-r--r--   1 root root    404 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.txt
-rw-r--r--   1 root root 101872 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.txz
-rw-r--r--   1 root root     62 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.txz.md5
-rw-r--r--   1 root root     94 Sep 24 07:47 xsimd-11.1.0-i586-3_SBo.txz.sha256
```

The rest of this is fine - I will merge those and leave out xsimd. You can resubmit a PR for that after you check the build.

**Comment by bassmadrigal** [comment]
> @bassmadrigal xsimd fails to build on 32bit. The previous version seems to have built fine. I built it here in September:
> 
> The rest of this is fine - I will merge those and leave out xsimd. You can resubmit a PR for that after you check the build.

Thanks! Once I saw the failure reported for 32bit, I spun up my VM to see if I could find a quick fix, but it seems it will take some time to figure out. It's not reported on their Issues page and I can't see any recent commits that are the obvious cause of it failing.

**Pull request closed without merging**
