### PR TITLE
system/xvfb-run updated to version 21.1.10.

### PR DESCRIPTION
**Pull request by 0xBOBF**
The existing 21.1.7 version source url is now 404'd. Updating this to the latest version which has an available source download.

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build system/xvfb-run

**Comment by willysr** [comment]
@0xBOBF just to be sure, you are the maintainer right?

**Comment by willysr** [comment]
merged

**Comment by 0xBOBF** [comment]
> @0xBOBF just to be sure, you are the maintainer right?

Yes it is I. I am just trying out the git system this time.

**Pull request closed without merging**
