### PR TITLE
graphics/autotrace: Version bump to 3.31.10 + new maintainer

### PR DESCRIPTION
**Pull request by bassmadrigal**
Citizen X hasn't been active on SBo since their initial submission of this program back in 2015.

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/autotrace

**Comment by bassmadrigal** [comment]
Oops... I forgot that others don't have the current directory added to their path.

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/autotrace

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
