### PR TITLE
DNSCrypt-proxy new version+maintainer

### PR DESCRIPTION
**Pull request by thnkman**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build network/dnscrypt-proxy

**Comment by willysr** [comment]
@sbo-bot: build audio/libfreeaptx

**Comment by willysr** [comment]
@aclemons i need your help to create a hintfile for this

**Comment by thnkman** [comment]
> @aclemons i need your help to create a hintfile for this

Do you need me to have the script create the user/group for this build?

**Comment by willysr** [comment]
no, it's for the CI engine :)
only @aclemons can do it

**Comment by aclemons** [comment]
> @aclemons i need your help to create a hintfile for this

Done - https://github.com/aclemons/slackrepo-hints/commit/9d384830a3b112b0e3614878b031b2454fdcfcf0

I triggered building a new docker image - should take about 10-15 minutes to be ready.

**Comment by aclemons** [comment]
> no, it's for the CI engine :) only @aclemons can do it

Good point - I added you as a collaborator on those repos too.

The docker build:

https://github.com/aclemons/slackrepo-docker/actions/runs/7370864735

**Comment by willysr** [comment]
@sbo-bot: build network/dnscrypt-proxy

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
