### PR TITLE
Nix v2.4

### PR DESCRIPTION
**Pull request by RSKYS**
These are finally for nix

### CODE REVIEW

**Comment by willysr** [comment]
please don't change the permission on the SlackBuild into 755. Everything must be kept at 644 for files

**Comment by RSKYS** [comment]
Aaaah I'm sorry

**Comment by RSKYS** [comment]
Also can you look into one you closed while I'm pushing other commits to this request?
I don't know what conflicts are with your tauonmb, please just add presence in .info
Also natsort was okay right?

**Comment by RSKYS** [comment]
Thank you notifying me for permission changes,
I was doing lots of tests with those directories, natural things go a bit outta hand
At first, I thought you meant installs at one of slackbuilds itself

**Comment by RSKYS** [comment]
> Also can you look into one you closed while I'm pushing other commits to this request? I don't know what conflicts are with your tauonmb, please just add "python3-pypresence" in .info Also natsort was okay right?

In this case, well just [revert this back.](https://git.slackbuilds.org/slackbuilds/tree/audio/tauonmb/tauonmb.info?id=fcfb4045f605abf9971b6512c48bcd9daf422a6e)
I'm sorry if I'm bothering you with this but [it's problem has been solved.](https://www.linuxquestions.org/questions/slackware-14/problem-with-live-notification-at-discord-possibly-dependency-or-python3-10-problem-4175702907/)

**Comment by RSKYS** [comment]
> Also can you look into one you closed while I'm pushing other commits to this request? I don't know what conflicts are with your tauonmb, please just add "python3-pypresence" in .info Also natsort was okay right?

Offtopic:
In this case, well just [revert this back.](https://github.com/RSKYS/willybuilds/blob/5e9eba5a0d192e27b9a4a30edcb6fab0acfc13d1/audio/tauonmb/tauonmb.info) (Only .info dependencies)
I'm sorry if I'm bothering you with this but [it's problem has been solved.](https://www.linuxquestions.org/questions/slackware-14/problem-with-live-notification-at-discord-possibly-dependency-or-python3-10-problem-4175702907/)

**Comment by willysr** [comment]
libeditline is not yet available on our repository yet, so i can't accept this PR

**Comment by willysr** [comment]
Did you send email to lowdown maintainer about taking over maintainership?

**Comment by RSKYS** [comment]
It doesn't work,
I really don't want to take over the ownership of it;
Just lib64 fix and version bump is okay to me.
Amyway waiting for answer, have you merged?

**Comment by willysr** [comment]
yes, it's merged to master already

**Comment by RSKYS** [comment]
Hi Willy,
I just felt to mention both nix and lowdown maintainers officially gave me right to maintain their builds,
Charles today and Cypher, last week's monday.

Regards,
Pouria.

**Pull request closed without merging**
