### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by aclemons**
These are some patches I am carrying in a private branch to add python3 support to some python libraries I use. Do you have any hesitation around adding them to the main tree?

### CODE REVIEW

**Comment by belka-ew** [comment]
Please adjust `$BUILD` if you update the script without chaning the version.

**Comment by willysr** [comment]
If this is the scripts you are maintaining, feel free to push it on your branch directly in SBo.

Otherwise, we need concent from the current maintainers as they're the one responsible

**Comment by aclemons** [comment]
> Please adjust $BUILD if you update a script without changing the version.

Normally, yes, but in this case I would only be triggering a rebuild for everyone who has the library installed and is using an automated for tracking version changes, but with no functional change.

> If this is the scripts you are maintaining, feel free to push it on your branch directly in SBo.
> Otherwise, we need concent from the current maintainers as they're the one responsible

No, these are not mine. I'll email all the maintainers. I had just seen commits like this (e.g. 3aad49765f, 2360f7ccbe, f3b8e9d4db, a849b171fe, 9cea044e34, etc) in this past and thought it might be fine.

**Comment by willysr** [comment]
We had an agreement to make those changes and maintainer agreed about it.

I can leave this merge request open until you can get approval from the maintainer

**Comment by aclemons** [comment]
I've sent Adis, Markus, Benjamin and Ruben an email.

**Comment by aclemons** [comment]
I'll post back here once I've heard back.

**Comment by willysr** [comment]
Thanks :)

**Comment by aclemons** [comment]
Ruben has written back and is fine with the addition. Benjamin has already updated his builds on his branch. I haven't heard from Markus yet. Adis has written back. If I understood him correctly, I think he is going to do a version update to greenlet and make ths addition himself.

**Comment by willysr** [comment]
I have merged the python-nbxmpp in my branch

**Comment by aclemons** [comment]
I've heard back from Markus and he's ok with us merging the pyOpenSSL, cryptography, and asn1crypto changes.

**Comment by willysr** [comment]
ok, merged all three.

One left is greenlet

**Comment by willysr** [comment]
merged the last remaining patch

**Pull request closed without merging**
