### PR TITLE
Version bump kodi to 21.0 and inputstream.adaptive to 21.4.4

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/inputstream.adaptive

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/kodi

**Comment by aclemons** [comment]
This one failed to build @bassmadrigal

**Comment by bassmadrigal** [comment]
@aclemons, I think I found the issue. 

I built spdlog after fmt, which picked up the optional fmt dependency (mentioned in spdlog's README). Since you use slackrepo and don't have a hintfile for spdlog, it doesn't pick up that optional dependency, which, Kodi requires spdlog to be built with fmt.

Rather than addressing this with an entry in the README, I'll just rework the SlackBuild when I get home to use internal versions of spdlog and fmt to make sure others don't run into similar issues if they also built spdlog before fmt.

**Comment by bassmadrigal** [comment]
@aclemons build has been updated to use internal spdlog and fmt. Hopefully you won't see other compilation issues.

**Comment by willysr** [comment]
@sbo-bot: build multimedia/kodi

**Comment by aclemons** [comment]
I'm a little bit late going through the changes this week, but Steven has updated the spdlog build to use its own version of fmt. So for you next update, it might be an option to not have to build the internal spdlog.

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/inputstream.adaptive

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/kodi

**Comment by bassmadrigal** [comment]
Yeah, I saw that and figured I'd play around with it later this week, but wanted to get the version bump out there before the public update.

**Pull request merged**
