### PR TITLE
FTBFS

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build x86_64 development/Bear

**Comment by willysr** [comment]
@sbo-bot: build x86_64 games/melonds

**Comment by willysr** [comment]
@sbo-bot: build i586 games/melonds

**Comment by aclemons** [comment]
@sbo-bot: build python/PyPy

**Comment by aclemons** [comment]
> (Ok, Sbo Bot don't listens to me here, now I know :) )

Yes sorry:

https://github.com/aclemons/sbo-bot/blob/1c60fdacb9f39d6d08a831847a1fd2f6e83a8a15/github/src/index.ts#L44-L49

**Comment by Ythogtha** [comment]
> > (Ok, Sbo Bot don't listens to me here, now I know :) )
> 
> Yes sorry:
> 
> https://github.com/aclemons/sbo-bot/blob/1c60fdacb9f39d6d08a831847a1fd2f6e83a8a15/github/src/index.ts#L44-L49

Anyway, it didn't do much.
I don't know what the problem is with PyPy and PyPy3 being on FTBFS.

**Comment by aclemons** [comment]
@sbo-bot: build PyPy3

**Comment by aclemons** [comment]
@sbo-bot: build PyPy

**Comment by aclemons** [comment]
I built them earlier in the week in a terminal and they built fine so I took them out of the table at the top of the ftbfs issue. But I am guessing that they maybe don't build in headless mode? Anyway, I just kicked them off again in headless and if that fails, that is the reason. But that's also fine to ignore, unless you are just itching to dig into why.

**Comment by aclemons** [comment]
@sbo-bot: build python/PyPy3

**Comment by aclemons** [comment]
@sbo-bot: build python/PyPy

**Comment by aclemons** [comment]
@sbo-bot: build i586 python/PyPy3

**Comment by Ythogtha** [comment]
> I built them earlier in the week in a terminal and they built fine so I took them out of the table at the top of the ftbfs issue. But I am guessing that they maybe don't build in headless mode? Anyway, I just kicked them off again in headless and if that fails, that is the reason. But that's also fine to ignore, unless you are just itching to dig into why.

Ok, no I won't dig into that.
For people needing headless, maybe the pypy/pypy3 binary repackage are quite enough.
The result is the same.
thanks !

**Comment by willysr** [comment]
@sbo-bot: build i586 games/galaxyv2

**Comment by aclemons** [comment]
These look fine. I will cancel the builds to unblock Willy's builds.

**Comment by willysr** [comment]
@sbo-bot: build games/galaxyv2

**Comment by willysr** [comment]
@sbo-bot: build games/galaxyv2

**Comment by willysr** [comment]
@sbo-bot: build i586 libraries/libtecla

**Comment by willysr** [comment]
@sbo-bot: build x86_64 libraries/libtecla

**Comment by willysr** [comment]
@sbo-bot: build development/smlnj

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by willysr** [comment]
@sbo-bot: build python/python3-sipsimple

**Comment by willysr** [comment]
@sbo-bot: build academic/R

**Pull request closed without merging**
