### PR TITLE
gis/python3-cartopy: Updated for version 0.23.0.

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build gis/python3-cartopy

**Comment by willysr** [comment]
@ArTourter invalid checksums

**Comment by ArTourter** [comment]
Hi @willysr 

it is the source of python3-shapely that somehow changed, not that of cartopy.
I have submitted an update for a newer version of shapely that was merged ( #6539 ). Can you use that to test this package?

Greg

**Comment by willysr** [comment]
@sbo-bot: build gis/python3-cartopy

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
