### PR TITLE
development/jupyter-nbconvert: Update for 7.16.0

### PR DESCRIPTION
**Pull request by isaackwy**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/jupyter-nbconvert

**Comment by willysr** [comment]
@isaackwy this failed to build

**Comment by isaackwy** [comment]
Please rebuild python3-soupsieve and BeautifulSoup4 and see what happens.
The error was with building python3-soupsieve:
`AttributeError: module 'importlib' has no attribute 'util'`

If python3-soupsieve and BeautifulSoup4 successfully builds, then jupyter-nbconvert should build as well.

**Comment by willysr** [comment]
were there any changes with those two since previous update that requires them to be rebuilt?

**Comment by willysr** [comment]
@sbo-bot: build python/python3-soupsieve

**Comment by willysr** [comment]
@sbo-bot: build development/jupyter-nbconvert

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
