### PR TITLE
Update to 3.12.1-rc1

### PR DESCRIPTION
**Pull request by notklaatu**

### CODE REVIEW

**Comment by willysr** [comment]
hi @notklaatu 

can you fix some issue with this PR?
- The version should not have "-". Probably best to change it into "_"
- The VERSION in .info doesn't match with the real version which is rc1
- The README has been fixed by Urchlay in last public update. Please wrap them.

**Comment by notklaatu** [comment]
>     * The version should not have "-". Probably best to change it into "_"

Do you mean change it in the makepkg command at the end, or throughout the entire SlackBuild script?

**Comment by willysr** [comment]
in the VERSION part

**Comment by willysr** [comment]
you can force-pushed it, so it stays in this PR

**Pull request closed without merging**
