### PR TITLE
desktop/qtile: Update for 0.25.0

### PR DESCRIPTION
**Pull request by isaackwy**
I would rather not update qtile if I can - since wlroots cannot be updated on Slackware 15.0, qtile is now unable to run on Wayland.

However, @willysr reported a build error with qtile 0.22.1 (I found out that it does not build with python3-cairocffi >= 1.6.0). Therefore, this update is necessary.

Update: I added python3-setuptools-scm-opt as a build dependency. Willy, please retry.

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build desktop/qtile

**Comment by willysr** [comment]
@isaackwy this failed to build

**Comment by willysr** [comment]
@sbo-bot: build desktop/qtile

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
