### PR TITLE
python/python3-lxml: Version bump to 5.3.0

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-lxml

**Comment by bassmadrigal** [comment]
@sbo-bot: build  audio/puddletag

**Comment by bassmadrigal** [comment]
@sbo-bot: build desktop/recoll

**Comment by bassmadrigal** [comment]
@sbo-bot: build audio/puddletag

**Comment by bassmadrigal** [comment]
@sbo-bot: build desktop/thunar-custom-actions

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/lutris

**Comment by bassmadrigal** [comment]
@sbo-bot: build gis/OWSLib

**Comment by bassmadrigal** [comment]
@sbo-bot: build gis/pytrainer

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/inkscape

**Comment by bassmadrigal** [comment]
@sbo-bot: build libraries/pyPEG2

**Comment by bassmadrigal** [comment]
@sbo-bot: build network/translate

**Comment by bassmadrigal** [comment]
@sbo-bot: build network/yle-dl

**Comment by bassmadrigal** [comment]
@sbo-bot: build office/sigil

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/jdcal

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/odoo

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/pikepdf

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-aksharamukha

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-cinemagoer

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-et_xmlfile

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-fonttools

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-obspy

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pykeepass

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-sipsimple

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-svglib

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-xmldiff

**Comment by bassmadrigal** [comment]
@sbo-bot: build system/afdko

**Comment by bassmadrigal** [comment]
@sbo-bot: build system/piper

**Comment by bassmadrigal** [comment]
@sbo-bot: build system/yelp-xsl

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
