### PR TITLE
desktop/nwg-shell: Updated for version 0.5.38.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-shell

**Comment by willysr** [comment]
@mac-a-r0ni please keep the URL format as before

**Comment by mac-a-r0ni** [comment]
I'd have done that if the URL worked when I tried it. But something had changed as it doesn't work.

**Comment by mac-a-r0ni** [comment]
> @mac-a-r0ni please keep the URL format as before

I took another look at the URL and noticed I was saving the source file incorrectly, fixed the URL and script to compensate.

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-shell

**Pull request closed without merging**
