### PR TITLE
New

### PR DESCRIPTION
**Pull request by RSKYS**
Hi Willy,
These are my SBo plans for Slackware 15.
I'm being patient due "SBo: Please be patient..",
I'm gonna add some other more builders in another commits later;
I have some couple mores too actually.

Regards,
Pouria

### CODE REVIEW

**Comment by RSKYS** [comment]
The reason I used zst package was they apply some handy extra patches to it, and I formed it the way I wanted.
I also use Manjaro's repo to keep it little back and prevent regular need of updates in insane speed.

**Comment by willysr** [comment]
firefox is already on core packages, so we can't accept it. 
As for gitignore, i can take it now

**Comment by RSKYS** [comment]
Uh, it's Firefox Developer Edition

**Comment by RSKYS** [comment]
> firefox is already on core packages, so we can't accept it.

Well I had discussion about this in LQ with Ponce, he just offered me .bz2 and I said "Ok, I know it exists, but they do some pre-patches on .tar.zst for me so I don't need to change variables everytime."
It's Firefox Developer Edition;
A little bit different than original.


> As for gitignore, i can take it now

Sure

**Comment by RSKYS** [comment]
This is very awesome program, It's my gift to KDE people on Slackware;
I actually mentioned it as surprise at LQ.

I don't know if it's more suitable under " desktop / " or not
KDE people gonna love it.

**Comment by RSKYS** [comment]
This is very awesome program, I actually mentioned it as surprise at LQ.

I don't know if it's more suitable under " desktop / " or " system / ";
KDE Plasma people gonna love it.

**Comment by willysr** [comment]
use Added (short description) as commit message for new scripts.
Also, if the new scripts is not a new dependency for existing scripts, it's better to wait for submission form to be opened again.

**Comment by RSKYS** [comment]
It's kinda optional dependecy of plasma-{desktop,workstation}..
I guess there's no such thing as conditions, right?

**Comment by RSKYS** [comment]
Firefox Developer Edition is entirely new,
I doubt Dave really approve firefox-dev through form..
Everybody think it's same as main Firefox while it's not in very few use cases.

I just close this PR, I'll approve via this git after submission gets open;
Thanks for the tip.

**Pull request closed without merging**
