### PR TITLE
desktop/nwg-drawer: Updated for version 0.4.9.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-drawer

**Comment by willysr** [comment]
@mac-a-r0ni this is not based on latest master branch, so you need to rebase it

**Comment by mac-a-r0ni** [comment]
> @mac-a-r0ni this is not based on latest master branch, so you need to rebase it

@willysr hrm I thought I had rebased on latest master... I'll look into it when I'm home from work, seems something went wrong here.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
