### PR TITLE
desktop/nwg-dock: Updated for version 0.3.9

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by aclemons** [comment]
There is already an update for nwg-dock staged for this week. Can you rebase your changes onto the github branch?

**Comment by mac-a-r0ni** [comment]
rebased

**Comment by aclemons** [comment]
@sbo-bot: build desktop/nwg-dock

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
