### PR TITLE
desktop/nwg-shell-config: Updated for version 0.5.34.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 desktop/nwg-shell-config

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 desktop/nwg-shell

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 desktop/nwg-shell

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
