### PR TITLE
multimedia/haruna: Updated for version 0.12.2

### PR DESCRIPTION
**Pull request by maravtdm**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build multimedia/haruna

**Comment by willysr** [comment]
@sbo-bot: build misc/bistwarden-desktop

**Comment by willysr** [comment]
@sbo-bot: build x86_64 misc/bistwarden-desktop

**Comment by willysr** [comment]
@maravtdm can you check on bistwarden-desktop ?

**Comment by willysr** [comment]
@sbo-bot: build misc/bitwarden-desktop

**Comment by maravtdm** [comment]
> @maravtdm can you check on bistwarden-desktop ?

"No matches found for build command"
if that means it miss make, cmake, meson, etc. command, it's normal as it's just an unarchived .deb package

**Comment by willysr** [comment]
it turns out you put wrong name, it's bitwarden instead of bistwarden

**Comment by maravtdm** [comment]
Ah ok. the title of the commit message ... got it
So, what is the best practice in this case ?

**Comment by willysr** [comment]
pay more attention :)

**Comment by maravtdm** [comment]
Indeed ;-)

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
