### PR TITLE
docker 27.2.0

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 system/containerd

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 system/docker

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 system/docker-cli

**Comment by willysr** [comment]
@aclemons 
```
--- ELF object(s) not stripped:
-rwxr-xr-x 1 root root 108681680 Aug 30 12:27 usr/bin/dockerd
```

do we need to strip this?

**Comment by aclemons** [comment]
> @aclemons
> 
> ```
> --- ELF object(s) not stripped:
> -rwxr-xr-x 1 root root 108681680 Aug 30 12:27 usr/bin/dockerd
> ```
> 
> do we need to strip this?

Looks like the stripping of docker-cli was not done by the maintainer, but by urchlay here: f0cc4f03068869d8de26b3e3c694af2577622e6a. We can add it to this build in the next update.

**Pull request closed without merging**
