### PR TITLE
graphics/dblatex: Updated for version 0.3.12.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build graphics/dblatex

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 graphics/dblatex

**Comment by aclemons** [comment]
This builds now with texlive-extra. I have not checked the package itself for functionality though.

This can't be automated as is - texlive-extra needs manual steps to be done after installation:


```sh
Cleaning /tmp/SBo ... done.
Checking whether git is clean ... yes.
Indexing SlackBuilds ... done.
git repo: /var/lib/repo/SBo/slackbuilds
branch:   dblatex
date:     Tue May 14 21:08:26 GMT 2024
revision: 46174d276ba328e9830f39651b00f89a4cd371e4
title:    graphics/dblatex: Update man page handling.
WARNING: Packages with tag _SBo are already installed
  texlive-extra-2023.230322-x86_64-1_SBo

================================================================================
graphics/dblatex                                                        21:09:27
================================================================================

Calculating dependencies ...
Dependency tree:
graphics/dblatex (update for git 46174d2 "Update man page handling")
  python/python3-wheel (ok)
    python/python3-installer (ok)
      python/python3-flit_core (ok)
  python/python3-build (ok)
    python/python3-pyproject-hooks (ok)
      python/python3-installer (ok)
        python/python3-flit_core (ok)
  office/texlive-extra (ok)

----------------------------------------------------------------------- 21:09:28
Building graphics/dblatex (update for git 46174d2 "Update man page handling")
Testing SlackBuild files ... done.
Verifying source files ... done.
Testing download URLs ... done.
mount: /tmp/repo.xxW8Ii/chrootdir/root/.Xauthority: special device /root/.Xauthority does not exist.
Installing dependencies ...
texlive-extra-2023.230322-x86_64-1_SBo is already installed
python3-flit_core-3.9.0-x86_64-2_SBo: Simplified pkging of Python modules, core backend ................................................................................................................................................................................. [ 140K]
python3-installer-0.7.0-x86_64-5_SBo: Library for installing Python packages from wheels ................................................................................................................................................................................ [ 1.1M]
python3-pyproject-hooks-1.0.0-x86_64-3_SBo: Wrappers to call PEP 517 build backend hooks ................................................................................................................................................................................ [ 110K]
python3-build-1.2.1-x86_64-3_SBo: a simple, correct PEP517 package builder .............................................................................................................................................................................................. [ 210K]
python3-wheel-0.43.0-x86_64-1_SBo: A built-package format for Python .................................................................................................................................................................................................... [ 610K]
Running dblatex.SlackBuild ...                                      ETA 21:10:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./dblatex.SlackBuild
Built ok:  dblatex-0.3.12-x86_64-2_SBo.txz                              21:09:36
Testing package dblatex-0.3.12-x86_64-2_SBo.txz ... done.
Test installing dblatex-0.3.12-x86_64-2_SBo.txz ...
dblatex-0.3.12-x86_64-2_SBo: DocBook to LaTeX Publishing ................................................................................................................................................................................................................ [ 8.0M]
Unmounting chroot ... done.
Backed up: dblatex-0.3.12-x86_64-1_SBo.txz
:-) graphics/dblatex Updated for git 46174d2 "Update man page handling" (-:

================================================================================
SUMMARY                                                                 21:09:37
================================================================================

Logfile:     /var/log/repo/SBo/repo_2024-05-14_21:09:27.log
Runtime:     0h 0m 10s
Updated:     1
  graphics/dblatex/dblatex-0.3.12-x86_64-2_SBo.txz
Warnings:    1
  Packages with tag _SBo are already installed
```

**Comment by willysr** [comment]
is it possible to move them to doinst.sh ?

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
