### PR TITLE
gis/python3-cftime: Updated for version 1.6.3.

### PR DESCRIPTION
**Pull request by ArTourter**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build gis/python3-cftime

**Comment by aclemons** [comment]
```
[...]
cftime-1.6.3rel/test/benchmark.py
cftime-1.6.3rel/test/test_cftime.py
/usr/bin/python3: No module named build
``

**Comment by ArTourter** [comment]
sorry forgot to add the requirements for the new build stuff

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
