### PR TITLE
desktop/nwg-look: Updated for version 0.2.7.

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-look

**Comment by willysr** [comment]
@mac-a-r0ni this has incorrect md5sum

**Comment by mac-a-r0ni** [comment]
> @mac-a-r0ni this has incorrect md5sum

Fixed. Thanks!

**Comment by willysr** [comment]
@sbo-bot: build desktop/nwg-look

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
