### PR TITLE
development/rust-opt: Updated for version 1.82.0.

### PR DESCRIPTION
**Pull request by pghvlaans**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build development/rust-opt

**Comment by willysr** [comment]
@sbo-bot: build audio/ncspot

**Comment by willysr** [comment]
@sbo-bot: build audio/yabridge

**Comment by willysr** [comment]
@sbo-bot: build desktop/leftwm

**Comment by willysr** [comment]
@sbo-bot: build development/cargo-c

**Comment by willysr** [comment]
@sbo-bot: build development/cargo-vendor-filterer

**Comment by willysr** [comment]
@sbo-bot: build development/mdbook

**Comment by willysr** [comment]
@sbo-bot: build development/rustup

**Comment by willysr** [comment]
@sbo-bot: build graphics/veles

**Comment by willysr** [comment]
@sbo-bot: build network/electrs

**Comment by willysr** [comment]
@sbo-bot: build network/newsboat

**Comment by willysr** [comment]
@sbo-bot: build network/noip-duc

**Comment by willysr** [comment]
@sbo-bot: build office/navi

**Comment by willysr** [comment]
@sbo-bot: build python/python3-bcrypt

**Comment by willysr** [comment]
@sbo-bot: build python/python3-maturin

**Comment by willysr** [comment]
@sbo-bot: build system/alacritty

**Comment by willysr** [comment]
@sbo-bot: build system/bottom

**Comment by willysr** [comment]
@sbo-bot: build system/clamav

**Comment by willysr** [comment]
@sbo-bot: build system/dust

**Comment by willysr** [comment]
@sbo-bot: build system/fd

**Comment by willysr** [comment]
@sbo-bot: build system/greetd

**Comment by willysr** [comment]
@sbo-bot: build system/helvum

**Comment by willysr** [comment]
@sbo-bot: build system/hyperfine

**Comment by willysr** [comment]
@sbo-bot: build system/onefetch

**Comment by willysr** [comment]
@sbo-bot: build system/skim

**Comment by willysr** [comment]
@sbo-bot: build system/tzupdate

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
