### PR TITLE
python/python3-pdm-backend: Version bump to 2.4.1

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm-backend

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-dep-logic

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-findpython

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pdm-build-locked

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-unearth

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
