### PR TITLE
ham/redsea: Updated for version 1.0.1.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build ham/redsea

**Comment by willysr** [comment]
@pyllyukko i think this requires network access or missing dependency?
can you test with unshare -n redsea.SlackBuild ?

**Comment by pyllyukko** [comment]
> @pyllyukko i think this requires network access or missing dependency?

It tries to download `nlohmann_json` if it's not found, but I added it as a dependency now. Can you run the CI pipeline again?

**Comment by willysr** [comment]
@sbo-bot: build ham/redsea

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
