### PR TITLE
python/python3-frozenlist: Updated for version 1.4.1

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build python/python3-frozenlist

**Comment by willysr** [comment]
@mac-a-r0ni : i think this is missing dep?
it failed to build without python3-build

**Comment by mac-a-r0ni** [comment]
> @mac-a-r0ni : i think this is missing dep? it failed to build without python3-build

yes it was, my apologies. Was missing python3-build & python3-expandvars. Fixed.

**Comment by willysr** [comment]
@sbo-bot: build python/python3-frozenlist

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
