### PR TITLE
network/kismet: Updated for version 2022-02-R1 + new maintainer.

### PR DESCRIPTION
**Pull request by pyllyukko**
Maintainer change agreed with @audriusk.

### CODE REVIEW

**Comment by willysr** [comment]
please make the VERSION using _ instead of - since it will messed up with slackpkg
so it should be 2022_02_R1

**Comment by pyllyukko** [comment]
I'm pretty sure the `${VERSION//-/_}` should take care of that ([here](https://github.com/pyllyukko/slackbuilds/blob/968fb30257603f91d0672bb87685586674e683cb/network/kismet/kismet.SlackBuild#L132)). So the end result will be `kismet-2022_02_R1-x86_64-1_SBo.tgz`.

**Comment by willysr** [comment]
But then the VERSION will not match the resulting package :)

**Comment by pyllyukko** [comment]
Are you talking about `sbopkg` (instead of `slackpkg`)?

**Comment by pyllyukko** [comment]
I made it into `2022.02.R1`, so it will also look nice in [Repology](https://repology.org/project/kismet/versions).

**Comment by pyllyukko** [comment]
I made it into `2022.02.R1`, so it will also look nice in [Repology](https://repology.org/project/kismet/versions).

**Comment by pyllyukko** [comment]
Fixed the `rm -rf $PRGNAM-$VERSION` also into `$PRGNAM-${VERSION//./-}`.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
