### PR TITLE
graphics/blender: Version bump to 4.1.1 + new maintainer

### PR DESCRIPTION
**Pull request by bassmadrigal**
I emailed DhabyX back in February to see if they were still interested in maintaining this package, which they haven't pushed an update to it in over 7 years. They never responded, so I'm intending to take over.

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build graphics/blender

**Comment by willysr** [comment]
@sbo-bot: build graphics/yafaray-blender

@bassmadrigal if you push an update which is being used by others, please make sure they are tested using CI so we can ensure that the update didn't break other scripts

**Comment by willysr** [comment]
@sbo-bot: build graphics/yafaray-blender

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
