### PR TITLE
python/pikepdf: updated to version 5.4.2

### PR DESCRIPTION
**Pull request by brobr**

### CODE REVIEW

**Comment by willysr** [comment]
merged

**Comment by brobr** [comment]
Hi Willy and Andrew,

My excuses, but I had not noticed that pikepdf-5.4.2 relies on qpdf-10.6 which is in current, not 15.0.
How does one accomplish that only the current branch gets the update when the 15.0 version stays at 5.3.2 (that suits qpdf-10.5)?

Cheers,

Rob

**Comment by willysr** [comment]
SBo only support 15.0 or latest stable release, so you need to push it @Ponce's repository for -current

**Comment by Ponce** [comment]
Hi @brobr, the unofficial repository for current is for fixes for stuff to be used on current, it's not for general updates or parallel maintaining simple updates for the newer unreleased version of Slackware (that I have to rebase every week).

that said, I've just tried installing pikepdf on current and tried to use the library with a bit of sample code (took it from [here](https://pikepdf.readthedocs.io/en/latest/tutorial.html))
```
#!/usr/bin/env python3
from pikepdf import Pdf
new_pdf = Pdf.new()
with Pdf.open('sample.pdf') as pdf:
    pdf.save('output.pdf')
```
but I got this as output
```
$ ./example.py 
Traceback (most recent call last):
  File "/root/./example.py", line 2, in <module>
    from pikepdf import Pdf
  File "/usr/lib64/python3.9/site-packages/pikepdf/__init__.py", line 56, in <module>
    from .models import (
  File "/usr/lib64/python3.9/site-packages/pikepdf/models/__init__.py", line 14, in <module>
    from .image import PdfImage, PdfInlineImage, UnsupportedImageTypeError
  File "/usr/lib64/python3.9/site-packages/pikepdf/models/image.py", line 16, in <module>
    from pikepdf import (
  File "/usr/lib64/python3.9/site-packages/pikepdf/jbig2.py", line 13, in <module>
    import deprecation
```
so it seems to miss python3-deprecation somewhere in its dependency chain (after installing that it seems to work).

**Comment by brobr** [comment]
Hi Matteo,

Thanks for the dependency. For the rest, an answer to my question, how
to provide pull or upgrade requests for current only is still not clear
to me (apart from making some shouts on LQ);

That said, for current you might want to update the pikepdf slackbuild
and info to suit the new qpdf in current. Version 5.4.2 no longer
compiles. Attached the diffs. Hope it works this way.

 Cheers,

Rob






On Fri, 02 Sep 2022 00:13:11 -0700
Matteo Bernardini ***@***.***> wrote:

> Hi @brobr, the unofficial repository for current is for fixes for
> stuff to be used on current, it's not for general updates or parallel
> maintaining simple updates for the newer unreleased version of
> Slackware (that I have to rebase every week).
> 
> that said, I've just tried installing pikepdf on current and tried to
> use the library with a bit of sample code (took it from
> [here](https://pikepdf.readthedocs.io/en/latest/tutorial.html)) ```
> #!/usr/bin/env python3 from pikepdf import Pdf
> new_pdf = Pdf.new()
> with Pdf.open('sample.pdf') as pdf:
>     pdf.save('output.pdf')
> ```
> but I got this as output
> ```
> $ ./example.py 
> Traceback (most recent call last):
>   File "/root/./example.py", line 2, in <module>
>     from pikepdf import Pdf
>   File "/usr/lib64/python3.9/site-packages/pikepdf/__init__.py", line
> 56, in <module> from .models import (
>   File
> "/usr/lib64/python3.9/site-packages/pikepdf/models/__init__.py", line
> 14, in <module> from .image import PdfImage, PdfInlineImage,
> UnsupportedImageTypeError File
> "/usr/lib64/python3.9/site-packages/pikepdf/models/image.py", line
> 16, in <module> from pikepdf import ( File
> "/usr/lib64/python3.9/site-packages/pikepdf/jbig2.py", line 13, in
> <module> import deprecation ``` so it seems to miss
> python3-deprecation somewhere in its dependency chain (after
> installing that it seems to work).
> 


diff pikepdf.SlackBuild.15-0 pikepdf.SlackBuild.curr 
28c28
< VERSION=${VERSION:-5.4.2}
---
> VERSION=${VERSION:-6.0.0.post1}


diff pikepdf.info.15-0 pikepdf.info.curr
2c2
< VERSION="5.4.2"
---
> VERSION="6.0.0.post1"
4,5c4,5
<
DOWNLOAD="https://pypi.python.org/packages/source/p/pikepdf/pikepdf-5.4.2.tar.gz"
< MD5SUM="97241a38b39fbd8cac1132b086ec2b87"
---
> DOWNLOAD="https://pypi.python.org/packages/source/p/pikepdf/pikepdf-6.0.0.post1.tar.gz"
> MD5SUM="21cbe6903f1c858d61d73defb4cd8047"
8c8
< REQUIRES="lxml pybind11 python3-setuptools_scm_git_archive"
---
> REQUIRES="lxml pybind11 python3-deprecation
> python3-setuptools_scm_git_archive"

**Comment by willysr** [comment]
Make a PR here https://github.com/Ponce/slackbuilds

**Pull request closed without merging**
