### PR TITLE
Python removes

### PR DESCRIPTION
**Pull request by fourtysixand2**
The majority of these have had python3 replacements for some time now.  They either have nothing that depends on them or the ones that do are in this list.

There are two that require more of an explanation:

system/docker-compose
  -replaced by python3-docker-compose which is the last python version
    -version 2.x is written in go and a completely new slackbuild should be submitted
  -maintainer has not responded to emails nor updated any builds in some time
  -holds up removal of python/jsonschema

office/calibre
  -maintainer has not responded or updated any builds in years
  -this build is seriously outdated and there is calibre-bin to replace it
  -holds up removal of python/netifaces

### CODE REVIEW

**Comment by Ponce** [comment]
sorry, but what is the reason for the removal?
can't they be kept as python2-* (and used if needed)?
IMHO python2 being unmaintained isn't enough, having a lot of things in the repository (and in Slackware) unmaintained for decades...

**Comment by Ponce** [comment]
well, I haven't checked them one by one but, besides not wanting too eventual conflicts with the python3 versions, I definitely agree with you that having a cleaner repo on the python side will surely be useful in the near future, especially when Slackware will migrate to a newer python3 and work should be done on SBo to follow this.
so, FWIW, it's green light for me.

**Comment by willysr** [comment]
cleanups are easier to be done during the development cycle for the next Slackware release since nothing has been placed in the database so removals are trivial. During normal cycle like now, it's better to keep removals at minimum.

**Comment by willysr** [comment]
i removed calibre and xlsx2csv for now

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
