### PR TITLE
Vile & XVile upstream updated to 9.8z

### PR DESCRIPTION
**Pull request by slackwhere**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build development/vile

**Comment by aclemons** [comment]
@sbo-bot: build development/xvile

**Comment by willysr** [comment]
@slackwhere can you fix this issue?

**Comment by slackwhere** [comment]
Hi Willy,

This is the same thing that happened with the plain Slackbuild that I
previously submitted. I tested both on new Slackware 15 VMs, both 32 and 64
bit, and the build works.

The difference that I see between my environment and the Slackbuild
environment are the MAKEFLAGS being set before the slackbuild is run. I
tried adding those in my environment and the build did succeed. If you
examine the updates to this slackbuild, none of them have reference to the
path that is causing the build to fail. If you have time, can you attempt
to execute that Slackbuild without the MAKEFLAGS being passed to the script
just to see if it works? That would be a datapoint that might help us debug
this issue further.

Thank you,
Wayne

**Comment by willysr** [comment]
you can add make -j1 in the SlackBuild and see if it works

**Comment by slackwhere** [comment]
Will do.

I'm not entirely clear on how the PR sequence comes into play with an
update like this. I'll update my branch and push changes to github, do I
then submit a new PR in order to trigger a new integrated build?

Thanks again.

**Comment by willysr** [comment]
just force push it or make a new commit on the same branch and push it
both works

**Comment by willysr** [comment]
@sbo-bot: build development/vile

**Comment by willysr** [comment]
@sbo-bot: build development/xvile

**Pull request closed without merging**
