### PR TITLE
python/python3-tox: Version bump to 4.20.0

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-tox

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-cinemagoer

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-lz4

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-solidpython

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
