### PR TITLE
desktop/dbgl: updated for version 0.98

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/dbgl

**Comment by willysr** [comment]
@Ythogtha this failed to build

**Comment by Ythogtha** [comment]
Sorry @willysr I missed the JDK update.
I've pushed an update using JDK17, this is what I tested at home.

**Comment by willysr** [comment]
@sbo-bot: build desktop/dbgl

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
