### PR TITLE
desktop/nwg-shell: upgrade to version 0.5.10

### PR DESCRIPTION
**Pull request by mac-a-r0ni**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 desktop/nwg-shell

**Comment by aclemons** [comment]
@sbo-bot: build i586 desktop/nwg-shell

**Review by aclemons — APPROVED** [review]
@mac-a-r0ni This LGTM, but it looks like `desktop/swayidle` might not build on 32bit. It seems that is also your build. Could you check on that for your next submission? Thanks.

I'll stage this now since that error is already on master and is not related to this change.

**Comment by mac-a-r0ni** [comment]
Yes I'll look into it. Thanks for the notification!

**Pull request merged**
