### PR TITLE
updates for qpwgraph, python3-cloudflare and certbot-dns-cloudflare

### PR DESCRIPTION
**Pull request by bolokanar**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-cloudflare

**Comment by aclemons** [comment]
@sbo-bot: build python/certbot-dns-cloudflare

**Comment by aclemons** [comment]
@sbo-bot: build audio/qpwgraph

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
