### PR TITLE
development/arduino-cli: Added (tool to manage arduino).

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build development/arduino-cli

**Comment by willysr** [comment]
@earies : it works fine now
please resubmit using this source

**Comment by willysr** [comment]
oh perhaps, you should change the BUID to 1 instead of 2

**Comment by earies** [comment]
> oh perhaps, you should change the BUID to 1 instead of 2

resubmitted through slackbuilds.org - I am not sure why you are seeing a BUID of 2 above as the sources even indicate 1

```
$ sudo ./arduino-cli.SlackBuild 
arduino-cli
LICENSE.txt

Slackware package maker, version 3.14159265.

Searching for symbolic links:

No symbolic links were found, so we won't make an installation script.
You can make your own later in ./install/doinst.sh and rebuild the
package if you like.

This next step is optional - you can set the directories in your package
to some sane permissions. If any of the directories in your package have
special permissions, then DO NOT reset them here!

Would you like to reset all directory permissions to 755 (drwxr-xr-x) and
directory ownerships to root.root ([y]es, [n]o)? n

Creating Slackware package:  /tmp/arduino-cli-0.34.2-x86_64-1_SBo.tgz

./
install/
install/slack-desc
usr/
usr/bin/
usr/bin/arduino-cli
usr/doc/
usr/doc/arduino-cli-0.34.2/
usr/doc/arduino-cli-0.34.2/LICENSE.txt
usr/doc/arduino-cli-0.34.2/arduino-cli.SlackBuild

Slackware package /tmp/arduino-cli-0.34.2-x86_64-1_SBo.tgz created.
```

**Comment by aclemons** [comment]
> oh perhaps, you should change the BUID to 1 instead of 2

That's the builder tracking how many times it has built the package by passing `BUILD` in through the env - you can ignore that. (it keeps a backup of the last built package)

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
