### PR TITLE
Zep update

### PR DESCRIPTION
**Pull request by mab974**

### CODE REVIEW

**Comment by mab974** [comment]
better like this ?

**Comment by willysr** [comment]
it hasn't been rebased

**Comment by mab974** [comment]
I have done this within my cloned version :

   git remote add upstream git://github.com/SlackBuildsOrg/slackbuilds.git
   git remote -v
   git co master
   git fetch upstream
   git rebase upstream/master
   git push -f origin master

I keep zep branch. Should I have pushed the zep branch too?

**Comment by mab974** [comment]
Ok! ,in fact, I didn’t dare clone the original repository and now I understand more about the mirroring principle of SlackBuilds.org.

I guess it works for multiple branches-pull requests too.( for dependent packages)

What is the periodicity of master update right now? 

Thanks Wily

**Comment by willysr** [comment]
master is updated once in few days during development cycle to keep everything up to date once we have enough fixes, but after 15.0 is available, it will be weekly update.

You push it to your github repository, not directly to our SBo repository.

**Comment by mab974** [comment]
ok

**Pull request closed without merging**
