### PR TITLE
system/unionfs-fuse: updated for version 3.3

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by aclemons** [comment]
```
# buildpkg i586 system/unionfs-fuse
sbolint: unionfs-fuse checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar  3 13:39:52 GMT 2023
revision: f0943d0b66b36400b9ce555a88fde498415784fd
title:    system/unionfs-fuse: Updated for version 3.3.

================================================================================
system/unionfs-fuse                                                     13:40:37
================================================================================

Calculating dependencies ... none.

Building system/unionfs-fuse (update for version 3.3) ----------------- 13:40:37
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running unionfs-fuse.SlackBuild ...                                 ETA 13:41:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./unionfs-fuse.SlackBuild
system/unionfs-fuse: unionfs-fuse.SlackBuild failed (status 2)          13:40:38
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
make[1]: *** [<builtin>: debug.o] Error 1
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
make[1]: *** [<builtin>: string.o] Error 1
make[1]: *** [<builtin>: unionfs.o] Error 1
make[1]: *** [<builtin>: unlink.o] Error 1
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
make[1]: *** [<builtin>: readdir.o] Error 1
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
/usr/include/fuse3/fuse_common.h:853:1: error: static assertion failed: "fuse: off_t must be 64bit"
make[1]: *** [<builtin>: usyslog.o] Error 1
make[1]: *** [<builtin>: rmdir.o] Error 1
make[1]: *** [<builtin>: opts.o] Error 1
make[1]: *** [<builtin>: findbranch.o] Error 1
make[1]: *** [<builtin>: cow.o] Error 1
make[1]: *** [<builtin>: cow_utils.o] Error 1
make[1]: *** [<builtin>: general.o] Error 1
make[1]: *** [<builtin>: fuse_ops.o] Error 1
make: *** [Makefile:6: build] Error 2
See /var/log/repo/SBo/system/unionfs-fuse/build.log
Unmounting chroot ... done.
:-( system/unionfs-fuse FAILED )-:

================================================================================
SUMMARY                                                                 13:40:38
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-03_13:40:37.log
Runtime:     0h 0m 1s
Failed:      1
  system/unionfs-fuse

```

```
# buildpkg x86_64 system/unionfs-fuse
Fetching origin
HEAD is now at f0943d0b66 system/unionfs-fuse: Updated for version 3.3.
docker.io/aclemons/sbo-maintainer-tools:latest
Untagged: aclemons/sbo-maintainer-tools:latest
sbolint: unionfs-fuse checks out OK
docker.io/aclemons/repo:slack-15.0
Untagged: aclemons/repo:slack-15.0
Creating hintfile directory: /etc/repo/SBo/hintfiles
Checking whether git is clean ... yes.
Indexing SlackBuilds ... done.
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Fri Mar  3 13:39:52 GMT 2023
revision: f0943d0b66b36400b9ce555a88fde498415784fd
title:    system/unionfs-fuse: Updated for version 3.3.

================================================================================
system/unionfs-fuse                                                     13:41:05
================================================================================

Calculating dependencies ... none.

Building system/unionfs-fuse (update for version 3.3) ----------------- 13:41:05
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running unionfs-fuse.SlackBuild ...                                 ETA 13:41:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./unionfs-fuse.SlackBuild
Built ok:  unionfs-fuse-3.3-x86_64-1_SBo.txz                            13:41:06
Testing package unionfs-fuse-3.3-x86_64-1_SBo.txz ... done.
Test installing unionfs-fuse-3.3-x86_64-1_SBo.txz ...
unionfs-fuse-3.3-x86_64-1_SBo: unionfs filesystem ...................... [ 180K]
Unmounting chroot ... done.
Backed up: unionfs-fuse-3.2-x86_64-1_SBo.txz
:-) system/unionfs-fuse Updated for version 3.3 (-:

================================================================================
SUMMARY                                                                 13:41:07
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-03_13:41:04.log
Runtime:     0h 0m 3s
Updated:     1
  system/unionfs-fuse/unionfs-fuse-3.3-x86_64-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/system/unionfs-fuse/unionfs-fuse-3.3-x86_64-1_SBo.txz to /tmp/sbopkglint.UzRsJN ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/system/unionfs-fuse/unionfs-fuse-3.3-x86_64-1_SBo.txz to /tmp/sbopkglint.UzRsJN ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== unionfs-fuse-3.3-x86_64-1_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
Building on i586 failed.

**Comment by willysr** [comment]
i'm afraid this project has dropped 32 bit support looking at the error?

**Comment by Ythogtha** [comment]
Following the error message I found a comment on fuse3, and fixed the build on ix86 !

**Comment by aclemons** [comment]
```
# buildpkg i586 system/unionfs-fuse
sbolint: unionfs-fuse checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Wed Mar  8 10:50:43 GMT 2023
revision: b2a91463059901b72ca42db5901fb46848e77d0d
title:    system/unionfs-fuse: Updated for version 3.3.

================================================================================
system/unionfs-fuse                                                     10:52:01
================================================================================

Calculating dependencies ... none.

Building system/unionfs-fuse (update for version 3.3) ----------------- 10:52:01
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running unionfs-fuse.SlackBuild ...                                 ETA 10:52:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./unionfs-fuse.SlackBuild
Built ok:  unionfs-fuse-3.3-i586-1_SBo.txz                              10:52:03
Testing package unionfs-fuse-3.3-i586-1_SBo.txz ... done.
Test installing unionfs-fuse-3.3-i586-1_SBo.txz ...
unionfs-fuse-3.3-i586-1_SBo: unionfs filesystem ........................ [ 170K]
Unmounting chroot ... done.
Backed up: unionfs-fuse-2.2-i586-1_SBo.txz
:-) system/unionfs-fuse Updated for version 3.3 (-:

================================================================================
SUMMARY                                                                 10:52:04
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-08_10:52:01.log
Runtime:     0h 0m 3s
Updated:     1
  system/unionfs-fuse/unionfs-fuse-3.3-i586-1_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/i586/system/unionfs-fuse/unionfs-fuse-3.3-i586-1_SBo.txz to /tmp/sbopkglint.HVqpi5 ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/i586/system/unionfs-fuse/unionfs-fuse-3.3-i586-1_SBo.txz to /tmp/sbopkglint.HVqpi5 ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== unionfs-fuse-3.3-i586-1_SBo.txz: All tests passed
```

```
# buildpkg x86_64 system/unionfs-fuse
sbolint: unionfs-fuse checks out OK
git repo: /var/lib/repo/SBo/slackbuilds
branch:   user/aclemons/updates
date:     Wed Mar  8 10:50:43 GMT 2023
revision: b2a91463059901b72ca42db5901fb46848e77d0d
title:    system/unionfs-fuse: Updated for version 3.3.

================================================================================
system/unionfs-fuse                                                     10:52:19
================================================================================

Calculating dependencies ... none.

----------------------------------------------------------------------- 10:52:19
Building system/unionfs-fuse (update for git b2a9146 "Updated for version 3.3")
Testing SlackBuild files ... done.
Downloading source files ...
Verifying source files ... done.
Running unionfs-fuse.SlackBuild ...                                 ETA 10:52:??
env MAKEFLAGS='-j24 -l13' nice -n 5 bash ./unionfs-fuse.SlackBuild
Built ok:  unionfs-fuse-3.3-x86_64-2_SBo.txz                            10:52:21
Testing package unionfs-fuse-3.3-x86_64-2_SBo.txz ... done.
Test installing unionfs-fuse-3.3-x86_64-2_SBo.txz ...
unionfs-fuse-3.3-x86_64-2_SBo: unionfs filesystem ...................... [ 150K]
Unmounting chroot ... done.
Backed up: unionfs-fuse-3.3-x86_64-1_SBo.txz
:-) system/unionfs-fuse Updated for git b2a9146 "Updated for version 3.3" (-:

================================================================================
SUMMARY                                                                 10:52:21
================================================================================

Logfile:     /var/log/repo/SBo/repo_2023-03-08_10:52:18.log
Runtime:     0h 0m 3s
Updated:     1
  system/unionfs-fuse/unionfs-fuse-3.3-x86_64-2_SBo.txz

Using tests from /usr/share/sbo-maintainer-tools/sbopkglint.d
Exploding /var/lib/repo/SBo/packages/15.0/x86_64/system/unionfs-fuse/unionfs-fuse-3.3-x86_64-2_SBo.txz to /tmp/sbopkglint.Lkdj4D ...OK
Running pre-doinst test...OK
Installing /var/lib/repo/SBo/packages/15.0/x86_64/system/unionfs-fuse/unionfs-fuse-3.3-x86_64-2_SBo.txz to /tmp/sbopkglint.Lkdj4D ...OK
Running test: 05-basic-sanity...OK
Running test: 10-docs...OK
Running test: 15-noarch...OK
Running test: 20-arch...OK
Running test: 25-lafiles...OK
Running test: 30-manpages...OK
Running test: 35-desktop...OK
Running test: 40-newconfig...OK
Running test: 45-doinst...OK
Running test: 50-icons...OK
=== unionfs-fuse-3.3-x86_64-2_SBo.txz: All tests passed
```

**Comment by aclemons** [comment]
Builds fine on both now for me. I did not test running it.

LGTM - staged to my branch.

**Pull request closed without merging**
