### PR TITLE
Update qtile and dependencies (+new maintainer)

### PR DESCRIPTION
**Pull request by isaackwy**
The previous maintainer, Dimitris Zlatanidis (d.zlatanidis@gmail.com), has provided me permission to maintain qtile (and cairocffi).

cairocffi and python3-xcffib are dependencies of qtile (qtile is purely built in python3).
I have removed trollius from the list of qtile dependencies (trollius is no longer needed).

python/python3-xcffib: Uploaded at 0.11.1
python/cairocffi: Updated for 1.3.0. (+new maintainer)
desktop/qtile: Updated for 0.20.0 (+new maintainer)

### CODE REVIEW

**Comment by willysr** [comment]
Can you change the commit message into category/package: commit-message format??

**Comment by isaackwy** [comment]
I changed the commit messages accordingly.

**Comment by willysr** [comment]
can you keep all files in repository under 644 permission instead of 755?

**Comment by isaackwy** [comment]
I changed qtile.SlackBuild permission to 644.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
