### PR TITLE
perl/perl-http-daemon: Updated for version 6.16.

### PR DESCRIPTION
**Pull request by pyllyukko**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-daemon

**Comment by willysr** [comment]
@pyllyukko you may need to install the Module::Build::Tiny module

**Comment by pyllyukko** [comment]
> @pyllyukko you may need to install the Module::Build::Tiny module

I'll check and fix that during the weekend and force push here in the same PR.

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-daemon

**Comment by willysr** [comment]
@pyllyukko i think you also need perl-Test-Needs

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-http-daemon

**Comment by willysr** [comment]
ok this works fine

**Pull request closed without merging**
