### PR TITLE
VMware-horizon-client Slackbuild updated for v8.4.0 and Slackware 15.0

### PR DESCRIPTION
**Pull request by m-elagin**
The previous version was not working with the current version of the Horizon client (8.4.0) and Slackware 15.0. This version unbundles some libraries and uses patchelf instead of sed to modify the executable. NOTE: this version no longer allows to select components, but rather unconditionally installs the components client, pcoip and hosted-apps, because I can only test those.

### CODE REVIEW

**Comment by willysr** [comment]
@m-elagin are you the maintainer of this script?

**Comment by willysr** [comment]
please try to contact him to take over

**Comment by willysr** [comment]
Hi, i don't think the maintainer is active anymore
Do you want to step up and take over this script ? or else i would have to delete this script

**Comment by m-elagin** [comment]
Hi, I will be glad to take over. Could you please refer me to the "rules"? Like, where is the script to be maintained -- here on github or e.g. on slackbuilds.org? Is the maintainer supposed to be monitoring a mailing list?

**Comment by willysr** [comment]
It's in SBo
github is just an external tool to help people who don't have direct access to Git Server in SBo

**Comment by willysr** [comment]
hi @m-elagin do you still want to push this update?

**Pull request closed without merging**
