### PR TITLE
Version bump multimedia/kodi to 21.1 and multimedia/inputstream.adaptive to 21.5.2

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/kodi

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/inputstream.adaptive

**Comment by bassmadrigal** [comment]
@sbo-bot: build multimedia/inputstream.adaptive

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
