### PR TITLE
python/python3-tox: Version bump to 4.18.0

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-tox

**Comment by bassmadrigal** [comment]
> #### ⛔️ sbolint - python/python3-tox ⛔️
> ```
> python3-tox: ERR: python3-tox.info: github URLs should not have refs/tags/
> python3-tox: WARN: python3-tox.info: canonical github URL should be: https://github.com/tox-dev/tox/archive/4.18.0/tox-4.18.0.tar.gz
> sbolint: python3-tox: errors 1, warnings 1
> ```

@aclemons, I discussed this with B. Watson and it was agreed the check was too aggressive and dialed back. The latest version of sbolint in sbo-maintainer-tools, 0.9.2.1, does not flag this as an error or warning.

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-cinemagoer

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-solidpython

**Comment by willysr** [comment]
merged

**Comment by aclemons** [comment]
> > #### ⛔️ sbolint - python/python3-tox ⛔️
> > ```
> > python3-tox: ERR: python3-tox.info: github URLs should not have refs/tags/
> > python3-tox: WARN: python3-tox.info: canonical github URL should be: https://github.com/tox-dev/tox/archive/4.18.0/tox-4.18.0.tar.gz
> > sbolint: python3-tox: errors 1, warnings 1
> > ```
> 
> @aclemons, I discussed this with B. Watson and it was agreed the check was too aggressive and dialed back. The latest version of sbolint in sbo-maintainer-tools, 0.9.2.1, does not flag this as an error or warning.

Yes, sorry. I had this staged but did not get it merged into the public release yesterday. Will happen here now: #7588

**Pull request closed without merging**
