### PR TITLE
libraries/openvino: Add cpu inference.

### PR DESCRIPTION
**Pull request by aclemons**

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build libraries/openvino

**Comment by aclemons** [comment]
@sbo-bot: build libraries/openvino

**Comment by aclemons** [comment]
@sbo-bot: build libraries/openvino

**Comment by aclemons** [comment]
typo

**Comment by aclemons** [comment]
@sbo-bot: build libraries/openvino

**Comment by willysr** [comment]
seems not supporting i586?

**Comment by aclemons** [comment]
Yes, I'll send this back to Johannes to check on. He sent me the tarball since the submission is already staged this week.

**Pull request closed without merging**
