### PR TITLE
Updates for 8 programs (discord, grainy, inputstream.adaptive, kodi, libmediainfo, lirc, mediainfo, shairplay)

### PR DESCRIPTION
**Pull request by bassmadrigal**
Version bump 4 programs (inputstream.adaptive, discord, libmediainfo, mediainfo).
Remove optional dep from kodi and add instructions on how to upgrade python to fix kodi crashes (should be temporary until Pat next updates python3).
Optionally take over maintenance of kodi since Larry seems to be MIA. He has not responded to any emails and it seems others are having the same issue.
Finally, I updated my email in 3 programs (gbrainy, lirc, and shairplay), so I have a consistent email in all my packages.

### CODE REVIEW

**Comment by bassmadrigal** [comment]
Of course, after I submitted these yesterday, within a few hours I got notification updates for 3 newly released versions.

If you'd prefer, I can just delete this branch and resubmit everything without the unnecessary initial version bumps. Just let me know.

**Comment by aclemons** [comment]
That's ok, I can pull those in too.

**Comment by aclemons** [comment]
kodi is installing documentation in usr/share/doc/:

```
tree usr/share/doc/
usr/share/doc/
└── kodi
    ├── LICENSE.md
    ├── README.Linux.md
    ├── kodi-eventclients-dev
    │   └── examples
    │       ├── C#
    │       │   └── XBMCDemoClient1.cs
    │       ├── C++
    │       │   ├── example_button1.cpp
    │       │   ├── example_button2.cpp
    │       │   ├── example_log.cpp
    │       │   ├── example_mouse.cpp
    │       │   └── example_notification.cpp
    │       ├── java
    │       │   └── XBMCDemoClient1.java
    │       └── python
    │           ├── example_action.py
    │           ├── example_button1.py
    │           ├── example_button2.py
    │           ├── example_mouse.py
    │           ├── example_notification.py
    │           └── example_simple.py
    └── version.txt

7 directories, 16 files
```

**Comment by bassmadrigal** [comment]
Thanks for the heads up. Nobody else caught it and I updated the SlackBuild before I was aware of sbolint.

I think adding `-DCMAKE_INSTALL_DOCDIR=$PKG/usr/doc/$PRGNAM-$VERSION \` to the cmake lines will fix it, but I'm running through a build right now to check. We'll see how long it takes...

**Comment by aclemons** [comment]
Cool, thanks. I've also started a build here with that added.

**Comment by bassmadrigal** [comment]
Build finished and now I have an unwanted /tmp directory. I think it needs to leave off the $PKG from that option. Trying again.

**Comment by bassmadrigal** [comment]
I confirmed that removing the $PKG from that option fixed the installation. I've pushed a new commit to fix that.

Thanks for doing in-depth checks. I need to be better about that :)

**Comment by aclemons** [comment]
Thanks, staged to my branch now.

**Pull request closed without merging**
