### PR TITLE
games/0ad: Fix build.

### PR DESCRIPTION
**Pull request by willysr**

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build x86_64 games/0ad

**Comment by willysr** [comment]
@sbo-bot: build x86_64 perl/perl-Module-Build-Tiny

**Comment by willysr** [comment]
@sbo-bot: build x86_64 perl/perl-Module-Build-Tiny

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-CPAN-Requirements-Dynamic

**Comment by willysr** [comment]
@sbo-bot: build x86_64 perl/perl-CPAN-Requirements-Dynamic

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Meta-Requirements-Range

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Meta-Requirements-Range

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Meta-Requirements-Range

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Meta-Requirements-Range

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-CPAN-Requirements-Dynamic

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-CPAN-Requirements-Dynamic

**Comment by willysr** [comment]
@sbo-bot: build perl/perl-Module-Build-Tiny

**Comment by willysr** [comment]
@sbo-bot: build x86_64 misc/yubioath-desktop

**Comment by aclemons** [comment]
@sbo-bot: build x86_64 misc/yubioath-desktop

**Comment by willysr** [comment]
@sbo-bot: build misc/par2cmdline-tbb

**Comment by willysr** [comment]
@sbo-bot: build libraries/googlebenchmark

**Comment by willysr** [comment]
@sbo-bot: build x86_64 desktop/waybar

**Comment by willysr** [comment]
@sbo-bot: build x86_64 games/0ad

**Comment by willysr** [comment]
@sbo-bot: build x86_64 games/0ad

**Pull request closed without merging**
