### PR TITLE
python/python3-pytest: Version bump to 8.3.2

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pytest

**Comment by bassmadrigal** [comment]
@sbo-bot: build academic/rpy2

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/i3ipc

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-cinemagoer

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-openstep-plist

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pytest-cov

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-pytest-runner

**Comment by bassmadrigal** [comment]
@sbo-bot: build python/python3-userpath

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
