### PR TITLE
python/python3-incremental: updated for version 24.7.0

### PR DESCRIPTION
**Pull request by Ythogtha**

### CODE REVIEW

**Comment by Ythogtha** [comment]
@sbo-bot: build python/python3-incremental

**Review by aclemons — APPROVED** [review]
LGTM

**Comment by aclemons** [comment]
@Ythogtha I think you are also the maintainer of python3-twisted. It does not build any more with this newer version of incremental:

https://github.com/SlackBuildsOrg/slackbuilds/issues/7307#issuecomment-2254139581

**Comment by aclemons** [comment]
I probably should have checked the one dependency here: https://github.com/SlackBuildsOrg/slackbuilds/pull/7297#issuecomment-2252970685

**Pull request merged**
