### PR TITLE
network/newsboat: Updated for version 2.14.

### PR DESCRIPTION
**Pull request by aclemons**
Taking over maintenance from Ben.

### CODE REVIEW

**Comment by willysr** [comment]
No changes in REQUIRES?

**Comment by aclemons** [comment]
This builds fine for mean in a clean, up-to-date Slackware64 14.2 environment with only stfl installed.

**Comment by willysr** [comment]
ok, let me try to test them

**Comment by aclemons** [comment]
👍

**Comment by willysr** [comment]
make: cargo is not found :D

**Comment by aclemons** [comment]
We removed rust from slackbuilds.org in c7f55b9513 after Pat added it to patches.

**Comment by willysr** [comment]
yeah, i just noticed that you removed it

**Comment by willysr** [comment]
ok, working great here

**Pull request closed without merging**
