### PR TITLE
11 Version Bumps

### PR DESCRIPTION
**Pull request by bassmadrigal**
libraries/qutepart: Version bump to 3.3.3
development/enki: Version bump to 22.08.0
python/python3-validators: Version bump to 0.22.0
python/cppy: Version bump to 1.2.1
misc/recode: Switch to maintained upstream and bump version to 3.7.13
multimedia/picard: Version bump to 2.9.2
python/python3-pdm: Version bump to 2.9.2
libraries/libmediainfo: Version bump to 23.09
multimedia/mediainfo: Version bump to 23.09
python/traitlets: Version bump to 5.10.0
python/python3-filelock: Version bump to 3.12.4

NOTE: @Ponce can remove the source for qutepart and enki from his server once this goes live. Thanks for hosting it!

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build libraries/qutepart

**Comment by aclemons** [comment]
@sbo-bot: build development/enki

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-validators

**Comment by aclemons** [comment]
@sbo-bot: build python/cppy

**Comment by aclemons** [comment]
@sbo-bot: build misc/recode

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/picard

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-pdm

**Comment by aclemons** [comment]
@sbo-bot: build libraries/libmediainfo

**Comment by aclemons** [comment]
@sbo-bot: build multimedia/mediainfo

**Comment by aclemons** [comment]
@sbo-bot: build python/traitlets

**Comment by aclemons** [comment]
@sbo-bot: build python/python3-filelock

**Review by aclemons — APPROVED** [review]
A few nits you might want to check on for your next submission @bassmadrigal, but otherwise LGTM

**Comment by bassmadrigal** [comment]
> A few nits you might want to check on for your next submission @bassmadrigal, but otherwise LGTM

Yep. I'm adding sbolint pre-commit hooks to my local repo tomorrow. I forgot about it after last week's update.

I still need to update my python template on my SlackBuild generator to remove those variables as well.

**Pull request merged**
