### PR TITLE
Changed dotnet package names and updated them to their latest version

### PR DESCRIPTION
**Pull request by RezaT4795**
development/dotnet-sdk: Changed package name to dotnet-sdk-3.1 and updated for version 3.1.415.
development/dotnet-runtime: Changed package name to dotnet-runtime-3.1 and updated for version 3.1.21.
libraries/aspnetcore-runtime: Changed package name to aspnetcore-runtime-3.1 and updated for version 3.1.21.

### CODE REVIEW

**Comment by willysr** [comment]
@RezaT4795 
can you split those renames into 3 different commits?

**Comment by RezaT4795** [comment]
> @RezaT4795 can you split those renames into 3 different commits?

Sure. I did it.

**Comment by willysr** [comment]
merged

**Comment by willysr** [comment]
development/dotnet-sdk: please change the permission back to 644 and don't remove the changes from new template

**Comment by RezaT4795** [comment]
There. I changed the permission back to 644 and used the new template. Sorry for the Inconvenience.

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
