### PR TITLE
Raku version 2024.12

### PR DESCRIPTION
**Pull request by mab974**
MoarVM, nqp and rakudo updated for version 2024.12
zef updated for version 0.22.6

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build perl/MoarVM

**Comment by aclemons** [comment]
@sbo-bot: build perl/nqp

**Comment by aclemons** [comment]
@sbo-bot: build perl/rakudo

**Comment by aclemons** [comment]
@sbo-bot: build perl/zef

**Comment by willysr** [comment]
merged

**Pull request closed without merging**
