### PR TITLE
games/alienarena: Version bump to 7.71.6

### PR DESCRIPTION
**Pull request by bassmadrigal**

### CODE REVIEW

**Comment by bassmadrigal** [comment]
@sbo-bot: build games/alienarena

**Comment by willysr** [comment]
merged

**Comment by bassmadrigal** [comment]
@ponce, forgot to mention this when I submitted this, but once the public update is pushed, you can delete the old source for this off your server.

**Comment by Ponce** [comment]
> @Ponce, forgot to mention this when I submitted this, but once the public update is pushed, you can delete the old source for this off your server.

thanks for the heads-up!

**Pull request closed without merging**
