### PR TITLE
Red/master

### PR DESCRIPTION
**Pull request by RSKYS**

### CODE REVIEW

**Review by RezaT4795 — APPROVED** [review]

**Review by RSKYS — COMMENTED** [review]
Windscribe is a little bit different from before;
I requested some changes, made some changes to it myself, and now the program has decent GUI in newer versions rather than CLI,
I think we make these changes to "windscribe" for now, and maybe add 1.4+ back as "windscribe-cli" later, one day that 15 got pushed eventually.

**Comment by RSKYS** [comment]
I've pushed tauonmb 7.1.3 a little bit ago,
make sure to fetch + pull incase please

**Comment by RSKYS** [comment]
I've pushed 2 new commits while ago

**Comment by RSKYS** [comment]
There you go,
you can merge.

**Comment by willysr** [comment]
You hard-coded to lib64.
Does this application no longer support 32 bit?

**Pull request closed without merging**
