### PR TITLE
network/gui-ufw: Update for version 24.04.0

### PR DESCRIPTION
**Pull request by mac-a-r0ni**
Fixed mistake in SlackBuild.

### CODE REVIEW

**Comment by aclemons** [comment]
@sbo-bot: build network/gui-ufw

**Comment by willysr** [comment]
hm.. sbopkglint is not executed?

**Comment by willysr** [comment]
merged

**Comment by mac-a-r0ni** [comment]
> hm.. sbopkglint is not executed?

It did run it again on the webui when I re-submitted it. Not sure why it appears it didn't. But I watched it on screen, very odd.

**Comment by aclemons** [comment]
> hm.. sbopkglint is not executed?

My fault. I added some error handling to post here when there is a problem checking out the repo, like the merge conflict in #3552, and broke posting the sbopkglint output (it was running it, just not commenting).

**Comment by aclemons** [comment]
@sbo-bot: lint network/gui-ufw

**Comment by aclemons** [comment]
@sbo-bot: lint network/gui-ufw

**Pull request closed without merging**
