### PR TITLE
desktop/todoman: update to 4.3.2 patched for Slackware 15.0

### PR DESCRIPTION
**Pull request by Tonus1**
update and revert 2 commits as they would break with python < 3.10
Issue opened upstream
Added pytz as runtime dependency

### CODE REVIEW

**Comment by willysr** [comment]
@sbo-bot: build desktop/todoman

**Comment by Tonus1** [comment]
> @Tonus1 can you fix this issue?

Sorry, must have messaed something. Should be ok now.

**Comment by aclemons** [comment]
@sbo-bot: build desktop/todoman

**Review by aclemons — APPROVED** [review]
LGTM

**Pull request merged**
